import '../dialog/flint-dialog.js';
import { FlintTimeField, FlintDigitalClock, FlintMultiSectionDigitalClock, FlintTimeClock, FlintDesktopTimePicker, FlintMobileTimePicker, FlintStaticTimePicker, FlintTimePicker } from './flint-time-picker.component.js';
export * from './flint-time-picker.component.js';
FlintTimeField.define('flint-time-field');
FlintDigitalClock.define('flint-digital-clock');
FlintMultiSectionDigitalClock.define('flint-multi-section-digital-clock');
FlintTimeClock.define('flint-time-clock');
FlintDesktopTimePicker.define('flint-desktop-time-picker');
FlintMobileTimePicker.define('flint-mobile-time-picker');
FlintStaticTimePicker.define('flint-static-time-picker');
FlintTimePicker.define('flint-time-picker');
