// Auto-generated by scripts/generate-react-wrappers.ts — do not edit

export { FlintIcon, type FlintIconProps } from './components/FlintIcon.js';
export { FlintIconEvents } from './events/flint-icon.js';
