// Auto-generated by scripts/generate-react-wrappers.ts — do not edit

export { FlintTextarea, type FlintTextareaProps, type FlintTextareaInputDetail, type FlintTextareaChangeDetail } from './components/FlintTextarea.js';
export { FlintTextareaEvents } from './events/flint-textarea.js';
