// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/carousel/flint-carousel.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintCarousel as FlintCarouselElement } from 'flint-ui/carousel/flint-carousel';

export const FlintCarousel = createComponent({
    tagName: 'flint-carousel',
    elementClass: FlintCarouselElement,
    react: React,
    events: {
        onFlintCarouselChange: 'flint-carousel-change' as EventName<CustomEvent>,
    },
});

export type FlintCarouselProps = React.ComponentProps<typeof FlintCarousel>;
