// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/format-number/flint-format-number.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintFormatNumber as FlintFormatNumberElement } from '@getufy/flint-ui/format-number/flint-format-number';

/**
 * Formats a number using the specified locale and options.
Localization is handled by the browser's `Intl.NumberFormat` API — no language packs required.
 */
export interface FlintFormatNumberProps extends Omit<React.HTMLAttributes<FlintFormatNumberElement>, 'lang'> {
    /** The number to format. */
    value?: number;
    /** The formatting style to use. */
    type?: 'currency' | 'decimal' | 'percent' | 'unit';
    /** Turns off grouping separators (e.g. thousands separator). */
    noGrouping?: boolean;
    /** The ISO 4217 currency code to use when formatting (e.g. 'USD', 'EUR', 'GBP'). */
    currency?: string;
    /** How to display the currency. */
    currencyDisplay?: 'symbol' | 'narrowSymbol' | 'code' | 'name';
    /** Number notation style. 'compact' renders e.g. "1.2K" or "3.4M". */
    notation?: 'standard' | 'scientific' | 'engineering' | 'compact';
    /** How to display compact notation — 'short' (1K) or 'long' (1 thousand). */
    compactDisplay?: 'short' | 'long';
    /** When to show the sign. */
    signDisplay?: 'auto' | 'never' | 'always' | 'exceptZero';
    /** ECMA-402 unit identifier (e.g. 'kilometer', 'kilogram', 'celsius'). Required when type='unit'. */
    unit?: string;
    /** How to display the unit when type='unit'. */
    unitDisplay?: 'short' | 'long' | 'narrow';
    /** The minimum number of integer digits (1–21). */
    minimumIntegerDigits?: number | undefined;
    /** The minimum number of fraction digits (0–20). */
    minimumFractionDigits?: number | undefined;
    /** The maximum number of fraction digits (0–20). */
    maximumFractionDigits?: number | undefined;
    /** The minimum number of significant digits (1–21). */
    minimumSignificantDigits?: number | undefined;
    /** The maximum number of significant digits (1–21). */
    maximumSignificantDigits?: number | undefined;
    /** BCP 47 language tag for formatting locale. Inherits from the document when unset. */
    lang?: string;
}

export const FlintFormatNumber = createComponent({
    tagName: 'flint-format-number',
    elementClass: FlintFormatNumberElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintFormatNumberProps & React.RefAttributes<FlintFormatNumberElement>>;
