// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/image-list/flint-image-list-item-bar.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintImageListItemBar as FlintImageListItemBarElement } from '@getufy/flint-ui/image-list/flint-image-list-item-bar';

export const FlintImageListItemBar = createComponent({
    tagName: 'flint-image-list-item-bar',
    elementClass: FlintImageListItemBarElement,
    react: React,
});

export type FlintImageListItemBarProps = React.ComponentProps<typeof FlintImageListItemBar>;
