// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintMenubarCheckboxItem as FlintMenubarCheckboxItemElement } from 'flint-ui/menubar/flint-menubar';

export const FlintMenubarCheckboxItem = createComponent({
    tagName: 'flint-menubar-checkbox-item',
    elementClass: FlintMenubarCheckboxItemElement,
    react: React,
    events: {
        onFlintMenubarCheckboxChange: 'flint-menubar-checkbox-change' as EventName<CustomEvent>,
    },
});

export type FlintMenubarCheckboxItemProps = React.ComponentProps<typeof FlintMenubarCheckboxItem>;
