// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/flint-command.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCommandSeparator as FlintCommandSeparatorElement } from '@getufy/flint-ui/command/flint-command';

/**
 * A hairline separator between command groups.
 */
export interface FlintCommandSeparatorProps extends React.HTMLAttributes<FlintCommandSeparatorElement> {
}

export const FlintCommandSeparator = createComponent({
    tagName: 'flint-command-separator',
    elementClass: FlintCommandSeparatorElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintCommandSeparatorProps & React.RefAttributes<FlintCommandSeparatorElement>>;
