// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintMenubarTrigger as FlintMenubarTriggerElement } from '@getufy/flint-ui/menubar/flint-menubar';

/**
 * The trigger button for a menubar menu.
 *
 * @slot (default) - Trigger label text.
 */
export interface FlintMenubarTriggerProps extends React.HTMLAttributes<FlintMenubarTriggerElement> {
    /** Whether the trigger's associated menu is currently open. */
    active?: boolean;
    /** Whether the trigger is non-interactive. */
    disabled?: boolean;
}

export const FlintMenubarTrigger = createComponent({
    tagName: 'flint-menubar-trigger',
    elementClass: FlintMenubarTriggerElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintMenubarTriggerProps & React.RefAttributes<FlintMenubarTriggerElement>>;
