// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/flint-command.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCommandSeparator as FlintCommandSeparatorElement } from '@getufy/flint-ui/command/flint-command';

export const FlintCommandSeparator = createComponent({
    tagName: 'flint-command-separator',
    elementClass: FlintCommandSeparatorElement,
    react: React,
});

export type FlintCommandSeparatorProps = React.ComponentProps<typeof FlintCommandSeparator>;
