// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/fab/flint-fab.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintFab as FlintFabElement } from '@getufy/flint-ui/fab/flint-fab';

export const FlintFab = createComponent({
    tagName: 'flint-fab',
    elementClass: FlintFabElement,
    react: React,
});

export type FlintFabProps = React.ComponentProps<typeof FlintFab>;
