// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/split-panel/flint-split-panel.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintSplitPanel as FlintSplitPanelElement } from 'flint-ui/split-panel/flint-split-panel';

export const FlintSplitPanel = createComponent({
    tagName: 'flint-split-panel',
    elementClass: FlintSplitPanelElement,
    react: React,
    events: {
        onFlintSplitPanelReposition: 'flint-split-panel-reposition' as EventName<CustomEvent>,
    },
});

export type FlintSplitPanelProps = React.ComponentProps<typeof FlintSplitPanel>;
