// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/rating/flint-rating.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintRating as FlintRatingElement } from 'flint-ui/rating/flint-rating';

export const FlintRating = createComponent({
    tagName: 'flint-rating',
    elementClass: FlintRatingElement,
    react: React,
    events: {
        onFlintRatingChange: 'flint-rating-change' as EventName<CustomEvent>,
    },
});

export type FlintRatingProps = React.ComponentProps<typeof FlintRating>;
