// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/sonner/flint-sonner.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintToaster as FlintToasterElement } from 'flint-ui/sonner/flint-sonner';

export const FlintToaster = createComponent({
    tagName: 'flint-toaster',
    elementClass: FlintToasterElement,
    react: React,
});

export type FlintToasterProps = React.ComponentProps<typeof FlintToaster>;
