// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/table/flint-table-pagination.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTablePagination as FlintTablePaginationElement } from '@getufy/flint-ui/table/flint-table-pagination';

/**
 * Table Pagination: pagination controls for tabular data.
 */
export interface FlintTablePaginationProps extends React.HTMLAttributes<FlintTablePaginationElement> {
    /** Total number of rows. */
    count?: number;
    /** Controlled current page (0-indexed). */
    page?: number;
    /** Controlled rows per page. */
    rowsPerPage?: number;
    /** Available rows-per-page options. */
    rowsPerPageOptions?: number[];
    /** Uncontrolled default page (applied on first render). */
    defaultPage?: number;
    /** Uncontrolled default rows per page. */
    defaultRowsPerPage?: number;
    /** Show First/Last page buttons. */
    showFirstLast?: boolean;
    /** Label for the rows-per-page selector. */
    labelRowsPerPage?: string;
    /** Fired when the current page changes. */
    onFlintPaginationPageChange?: (event: CustomEvent) => void;
    /** Fired when rows per page changes. */
    onFlintPaginationRowsPerPageChange?: (event: CustomEvent) => void;
}

export const FlintTablePagination = createComponent({
    tagName: 'flint-table-pagination',
    elementClass: FlintTablePaginationElement,
    react: React,
    events: {
        onFlintPaginationPageChange: 'flint-pagination-page-change' as EventName<CustomEvent>,
        onFlintPaginationRowsPerPageChange: 'flint-pagination-rows-per-page-change' as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintTablePaginationProps & React.RefAttributes<FlintTablePaginationElement>>;
