// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/carousel/flint-carousel.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCarouselPrevious as FlintCarouselPreviousElement } from 'flint-ui/carousel/flint-carousel';

export const FlintCarouselPrevious = createComponent({
    tagName: 'flint-carousel-previous',
    elementClass: FlintCarouselPreviousElement,
    react: React,
});

export type FlintCarouselPreviousProps = React.ComponentProps<typeof FlintCarouselPrevious>;
