// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/date-range-picker/flint-single-input-date-range-field.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintSingleInputDateRangeField as FlintSingleInputDateRangeFieldElement } from '@getufy/flint-ui/date-range-picker/flint-single-input-date-range-field';

export const FlintSingleInputDateRangeField = createComponent({
    tagName: 'flint-single-input-date-range-field',
    elementClass: FlintSingleInputDateRangeFieldElement,
    react: React,
    events: {
        onFlintDateRangePickerClear: 'flint-date-range-picker-clear' as EventName<CustomEvent>,
        onFlintDateRangePickerChange: 'flint-date-range-picker-change' as EventName<CustomEvent>,
    },
});

export type FlintSingleInputDateRangeFieldProps = React.ComponentProps<typeof FlintSingleInputDateRangeField>;
