// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/flint-range-slider/flint-range-slider.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintRangeSlider as FlintRangeSliderElement } from '@getufy/flint-ui/flint-range-slider/flint-range-slider';

/**
 * A range slider that lets users select a start and end value within a range.
 */
export interface FlintRangeSliderProps extends React.HTMLAttributes<FlintRangeSliderElement> {
    /** Current [start, end] values. */
    value?: [number, number];
    /** Minimum bound (default: 0). */
    min?: number;
    /** Maximum bound (default: 100). */
    max?: number;
    /** Step increment (default: 1). */
    step?: number;
    /** Visual size of track and thumbs (default: 'md'). */
    size?: 'sm'|'md'|'lg';
    /** Disables both thumbs. */
    disabled?: boolean;
    /** Label text shown above the track. */
    label?: string;
    /** Show the current [start, end] values. */
    showValue?: boolean;
    /** When either thumb moves. detail: { value: [number, number] } */
    onFlintRangeSliderChange?: (event: CustomEvent) => void;
}

export const FlintRangeSlider = createComponent({
    tagName: 'flint-range-slider',
    elementClass: FlintRangeSliderElement,
    react: React,
    events: {
        onFlintRangeSliderChange: 'flint-range-slider-change' as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintRangeSliderProps & React.RefAttributes<FlintRangeSliderElement>>;
