// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/flint-time-picker.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintMobileTimePicker as FlintMobileTimePickerElement } from '@getufy/flint-ui/time-picker/flint-time-picker';

export const FlintMobileTimePicker = createComponent({
    tagName: 'flint-mobile-time-picker',
    elementClass: FlintMobileTimePickerElement,
    react: React,
    events: {
        onChange: 'change' as EventName<CustomEvent>,
    },
});

export type FlintMobileTimePickerProps = React.ComponentProps<typeof FlintMobileTimePicker>;
