// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/breadcrumbs/flint-breadcrumb-item.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintBreadcrumbItem as FlintBreadcrumbItemElement } from '@getufy/flint-ui/breadcrumbs/flint-breadcrumb-item';

/**
 * A breadcrumb item for use inside `<FlintBreadcrumbs>`.
 * Renders as a plain text span or an anchor link when `href` is provided.
 *
 * @slot (default) - Item content (text or rich content).
 */
export interface FlintBreadcrumbItemProps extends React.HTMLAttributes<FlintBreadcrumbItemElement> {
    /** When provided, renders the item as an anchor link. */
    href?: string;
}

export const FlintBreadcrumbItem = createComponent({
    tagName: 'flint-breadcrumb-item',
    elementClass: FlintBreadcrumbItemElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintBreadcrumbItemProps & React.RefAttributes<FlintBreadcrumbItemElement>>;
