// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintDialog as FlintDialogElement } from '@getufy/flint-ui/dialog/flint-dialog';

export interface FlintDialogCloseDetail {
    open: false;
}

/**
 * flint-dialog: a modal dialog component.
 *
 * @slot (default) - Default slot for dialog content (title, content, actions sub-components).
 */
export interface FlintDialogProps extends React.HTMLAttributes<FlintDialogElement> {
    dependencies?: object;
    /** Controls the open / closed state of the dialog. */
    open?: boolean;
    /** Initial open state for uncontrolled usage. */
    defaultOpen?: boolean;
    /** Animation style: 'scale' (default), 'slide-up', or 'slide-down'. */
    transition?: 'scale' | 'slide-up' | 'slide-down';
    /** When true, clicking the backdrop will NOT close the dialog. */
    disableBackdropClose?: boolean;
    /** Dispatched when the dialog requests to be closed (backdrop click or an explicit call to `requestClose()`). The host is responsible for setting `open = false` in response. detail: `{ open: false }` */
    onFlintDialogClose?: (event: CustomEvent<FlintDialogCloseDetail>) => void;
}

export const FlintDialog = createComponent({
    tagName: 'flint-dialog',
    elementClass: FlintDialogElement,
    react: React,
    events: {
        onFlintDialogClose: 'flint-dialog-close' as EventName<CustomEvent<FlintDialogCloseDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintDialogProps & React.RefAttributes<FlintDialogElement>>;
