// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintMenubarShortcut as FlintMenubarShortcutElement } from '@getufy/flint-ui/menubar/flint-menubar';

/**
 * Displays a keyboard shortcut hint inside a menu item.
 *
 * @slot (default) - Shortcut text, e.g. `⌘T` or `Ctrl+N`.
 */
export interface FlintMenubarShortcutProps extends React.HTMLAttributes<FlintMenubarShortcutElement> {
}

export const FlintMenubarShortcut = createComponent({
    tagName: 'flint-menubar-shortcut',
    elementClass: FlintMenubarShortcutElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintMenubarShortcutProps & React.RefAttributes<FlintMenubarShortcutElement>>;
