// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/table/flint-table.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintTableBody as FlintTableBodyElement } from 'flint-ui/table/flint-table';

export const FlintTableBody = createComponent({
    tagName: 'flint-table-body',
    elementClass: FlintTableBodyElement,
    react: React,
});

export type FlintTableBodyProps = React.ComponentProps<typeof FlintTableBody>;
