// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/stepper/flint-stepper.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintStepConnector as FlintStepConnectorElement } from '@getufy/flint-ui/stepper/flint-stepper';

export interface FlintStepConnectorProps extends React.HTMLAttributes<FlintStepConnectorElement> {
    /** Layout direction of the connector line. */
    orientation?: 'horizontal' | 'vertical';
    /** Whether the connector represents a completed step transition. */
    completed?: boolean;
}

export const FlintStepConnector = createComponent({
    tagName: 'flint-step-connector',
    elementClass: FlintStepConnectorElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintStepConnectorProps & React.RefAttributes<FlintStepConnectorElement>>;
