// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/collapsible/flint-collapsible.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCollapsibleContent as FlintCollapsibleContentElement } from 'flint-ui/collapsible/flint-collapsible';

export const FlintCollapsibleContent = createComponent({
    tagName: 'flint-collapsible-content',
    elementClass: FlintCollapsibleContentElement,
    react: React,
});

export type FlintCollapsibleContentProps = React.ComponentProps<typeof FlintCollapsibleContent>;
