// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/flint-item.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintItemMedia as FlintItemMediaElement } from '@getufy/flint-ui/item/flint-item';

export const FlintItemMedia = createComponent({
    tagName: 'flint-item-media',
    elementClass: FlintItemMediaElement,
    react: React,
});

export type FlintItemMediaProps = React.ComponentProps<typeof FlintItemMedia>;
