// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/stepper/flint-stepper.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintMobileStepper as FlintMobileStepperElement } from '@getufy/flint-ui/stepper/flint-stepper';
import { FlintMobileStepperEvents } from '../events/flint-mobile-stepper.js';

/**
 * Mobile Stepper: a compact stepper for mobile layouts.
 *
 * @slot back-button - Back navigation button.
 * @slot next-button - Next navigation button.
 */
export interface FlintMobileStepperProps extends React.HTMLAttributes<FlintMobileStepperElement> {
    /** Total number of steps. */
    steps?: number;
    /** Zero-based index of the currently active step. */
    activeStep?: number;
    /** Progress indicator style: text counter, dot indicators, or a progress bar. */
    variant?: 'text' | 'dots' | 'progress';
    /** Positioning of the mobile stepper within its container. */
    position?: 'top' | 'bottom' | 'static';
    /** Label text for the Back navigation button (supports i18n). */
    backLabel?: string;
    /** Label text for the Next navigation button (supports i18n). */
    nextLabel?: string;
    /** Fired when the back button is clicked. */
    onFlintMobileStepBack?: (event: CustomEvent) => void;
    /** Fired when the next button is clicked. */
    onFlintMobileStepNext?: (event: CustomEvent) => void;
}

export const FlintMobileStepper = createComponent({
    tagName: 'flint-mobile-stepper',
    elementClass: FlintMobileStepperElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintMobileStepBack: FlintMobileStepperEvents.MOBILE_STEP_BACK as EventName<CustomEvent>,
        onFlintMobileStepNext: FlintMobileStepperEvents.MOBILE_STEP_NEXT as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintMobileStepperProps & React.RefAttributes<FlintMobileStepperElement>>;
