// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintDialogTitle as FlintDialogTitleElement } from 'flint-ui/dialog/flint-dialog';

export const FlintDialogTitle = createComponent({
    tagName: 'flint-dialog-title',
    elementClass: FlintDialogTitleElement,
    react: React,
});

export type FlintDialogTitleProps = React.ComponentProps<typeof FlintDialogTitle>;
