// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tooltip/flint-tooltip.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTooltip as FlintTooltipElement } from '@getufy/flint-ui/tooltip/flint-tooltip';
import { FlintTooltipEvents } from '../events/flint-tooltip.js';

/**
 * flint-tooltip
A component that displays a text label when users hover over or focus on an element.
 */
export interface FlintTooltipProps extends React.HTMLAttributes<FlintTooltipElement> {
    /** Text content displayed inside the tooltip. */
    label?: string;
    /**
     * Preferred placement of the tooltip relative to the trigger element.
     * Allowed values: 'top' | 'right' | 'bottom' | 'left'
     */
    placement?: 'top' | 'right' | 'bottom' | 'left';
    /** Show a small arrow pointing toward the trigger element. */
    arrow?: boolean;
    /** Disables the tooltip so it never appears. */
    disabled?: boolean;
    /** Delay in ms before showing the tooltip. */
    openDelay?: number;
    /** Delay in ms before hiding the tooltip. */
    closeDelay?: number;
    /** When true, the tooltip popup uses `position: fixed` instead of `position: absolute` */
    hoist?: boolean;
    /**
     * Dispatched when the tooltip becomes visible.
     * DOM event: `flint-tooltip-show`
     */
    onFlintTooltipShow?: (event: CustomEvent) => void;
    /**
     * Dispatched when the tooltip is dismissed.
     * DOM event: `flint-tooltip-hide`
     */
    onFlintTooltipHide?: (event: CustomEvent) => void;
}

export const FlintTooltip = createComponent({
    tagName: 'flint-tooltip',
    elementClass: FlintTooltipElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintTooltipShow: FlintTooltipEvents.SHOW as EventName<CustomEvent>,
        onFlintTooltipHide: FlintTooltipEvents.HIDE as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintTooltipProps & React.RefAttributes<FlintTooltipElement>>;
