// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintDialog as FlintDialogElement } from '@getufy/flint-ui/dialog/flint-dialog';
import { FlintDialogEvents } from '../events/flint-dialog.js';

export interface FlintDialogProps extends React.HTMLAttributes<FlintDialogElement> {
    dependencies?: object;
    /** Current open state (controlled). When set, the component reflects this state and does not manage its own state. */
    open?: boolean;
    /** Initial open state (uncontrolled). Only used on first render; ignored after mount. */
    defaultOpen?: boolean;
    /**
     * Size variant of the dialog panel.
     * Allowed values: 'sm' | 'md' | 'lg' | 'full'
     */
    size?: 'sm' | 'md' | 'lg' | 'full';
    /**
     * Animation style for open/close.
     * Allowed values: 'scale' | 'slide-up' | 'slide-down'
     */
    transition?: 'scale' | 'slide-up' | 'slide-down';
    /** When true, clicking the backdrop will NOT close the dialog. */
    disableBackdropClose?: boolean;
    /** CSS selector for the element to focus when the dialog opens. */
    initialFocus?: string;
    onFlintDialogOpen?: (event: CustomEvent) => void;
    onFlintDialogClose?: (event: CustomEvent) => void;
}

export const FlintDialog = createComponent({
    tagName: 'flint-dialog',
    elementClass: FlintDialogElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintDialogOpen: FlintDialogEvents.OPEN as EventName<CustomEvent>,
        onFlintDialogClose: FlintDialogEvents.CLOSE as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintDialogProps & React.RefAttributes<FlintDialogElement>>;
