// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/flint-item.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintItemDescription as FlintItemDescriptionElement } from '@getufy/flint-ui/item/flint-item';

export const FlintItemDescription = createComponent({
    tagName: 'flint-item-description',
    elementClass: FlintItemDescriptionElement,
    react: React,
});

export type FlintItemDescriptionProps = React.ComponentProps<typeof FlintItemDescription>;
