// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tree-view/flint-simple-tree-view.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintSimpleTreeView as FlintSimpleTreeViewElement } from '@getufy/flint-ui/tree-view/flint-simple-tree-view';
import { FlintSimpleTreeViewEvents } from '../events/flint-simple-tree-view.js';

/**
 * A simple tree-view container that manages keyboard navigation, focus,
and item selection/expansion for nested `flint-tree-item` elements.
 *
 * @slot (default) - Place `flint-tree-item` elements here.
 */
export interface FlintSimpleTreeViewProps extends React.HTMLAttributes<FlintSimpleTreeViewElement> {
    /** When `true`, disabled items can receive keyboard focus. */
    disabledItemsFocusable?: boolean;
    /** Callback invoked when a tree item is clicked or activated via keyboard. */
    onItemClick?: FlintSimpleTreeViewElement['onItemClick'];
    /** **Controlled mode.** The set of item IDs that should be expanded. */
    expandedItems?: string[] | undefined;
    /** **Uncontrolled mode.** Item IDs to expand on initial mount. */
    defaultExpandedItems?: string[];
    /** Callback fired when the user toggles an item's expansion. */
    onExpandedItemsChange?: FlintSimpleTreeViewElement['onExpandedItemsChange'];
    /** What interaction triggers expand/collapse. */
    expansionTrigger?: 'content' | 'iconContainer';
    /** When the expanded set changes (detail: { expandedItems }) */
    onFlintTreeViewExpandedItemsChange?: (event: CustomEvent) => void;
    /** When a tree item is activated (detail: { itemId }) */
    onFlintTreeViewItemClick?: (event: CustomEvent) => void;
}

export const FlintSimpleTreeView = createComponent({
    tagName: 'flint-simple-tree-view',
    elementClass: FlintSimpleTreeViewElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintTreeViewExpandedItemsChange: FlintSimpleTreeViewEvents.TREE_VIEW_EXPANDED_ITEMS_CHANGE as EventName<CustomEvent>,
        onFlintTreeViewItemClick: FlintSimpleTreeViewEvents.TREE_VIEW_ITEM_CLICK as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintSimpleTreeViewProps & React.RefAttributes<FlintSimpleTreeViewElement>>;
