// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/empty/flint-empty.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintEmptyHeader as FlintEmptyHeaderElement } from '@getufy/flint-ui/empty/flint-empty';

/**
 * Groups the media, title, and description of an empty state.
 *
 * @slot (default) - Accepts `flint-empty-media`, `flint-empty-title`, `flint-empty-description`.
 */
export interface FlintEmptyHeaderProps extends React.HTMLAttributes<FlintEmptyHeaderElement> {
}

export const FlintEmptyHeader = createComponent({
    tagName: 'flint-empty-header',
    elementClass: FlintEmptyHeaderElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintEmptyHeaderProps & React.RefAttributes<FlintEmptyHeaderElement>>;
