// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/flint-item.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintItemSeparator as FlintItemSeparatorElement } from '@getufy/flint-ui/item/flint-item';

/**
 * Visual separator between items in a group.
 */
export interface FlintItemSeparatorProps extends React.HTMLAttributes<FlintItemSeparatorElement> {
}

export const FlintItemSeparator = createComponent({
    tagName: 'flint-item-separator',
    elementClass: FlintItemSeparatorElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintItemSeparatorProps & React.RefAttributes<FlintItemSeparatorElement>>;
