// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/resizable/flint-resizable.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintResizableHandle as FlintResizableHandleElement } from 'flint-ui/resizable/flint-resizable';

export const FlintResizableHandle = createComponent({
    tagName: 'flint-resizable-handle',
    elementClass: FlintResizableHandleElement,
    react: React,
});

export type FlintResizableHandleProps = React.ComponentProps<typeof FlintResizableHandle>;
