// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintDialogContent as FlintDialogContentElement } from 'flint-ui/dialog/flint-dialog';

export const FlintDialogContent = createComponent({
    tagName: 'flint-dialog-content',
    elementClass: FlintDialogContentElement,
    react: React,
});

export type FlintDialogContentProps = React.ComponentProps<typeof FlintDialogContent>;
