// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/flint-time-picker.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintDesktopTimePicker as FlintDesktopTimePickerElement } from 'flint-ui/time-picker/flint-time-picker';

export const FlintDesktopTimePicker = createComponent({
    tagName: 'flint-desktop-time-picker',
    elementClass: FlintDesktopTimePickerElement,
    react: React,
    events: {
        onChange: 'change' as EventName<CustomEvent>,
    },
});

export type FlintDesktopTimePickerProps = React.ComponentProps<typeof FlintDesktopTimePicker>;
