// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/transfer-list/flint-transfer-list.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTransferList as FlintTransferListElement } from 'flint-ui/transfer-list/flint-transfer-list';

export const FlintTransferList = createComponent({
    tagName: 'flint-transfer-list',
    elementClass: FlintTransferListElement,
    react: React,
    events: {
        onChange: 'change' as EventName<CustomEvent>,
    },
});

export type FlintTransferListProps = React.ComponentProps<typeof FlintTransferList>;
