// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/relative-time/flint-relative-time.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintRelativeTime as FlintRelativeTimeElement } from '@getufy/flint-ui/relative-time/flint-relative-time';

/**
 * Displays a localized time phrase relative to the current date and time.
Uses the browser's `Intl.RelativeTimeFormat` API — no language packs needed.
 */
export interface FlintRelativeTimeProps extends Omit<React.HTMLAttributes<FlintRelativeTimeElement>, 'lang'> {
    /**
     * The date to calculate time from. Accepts a Date, ISO string, or Unix ms timestamp. Defaults to the current date/time.
     * Type: `Date | string | number`
     */
    date?: FlintRelativeTimeElement['date'];
    /**
     * The formatting style to use.
     * Allowed values: 'long' | 'short' | 'narrow'
     */
    format?: 'long' | 'short' | 'narrow';
    /**
     * When `auto`, values such as "yesterday" and "tomorrow" will be shown when
     * Allowed values: 'always' | 'auto'
     */
    numeric?: 'always' | 'auto';
    /** Keep the displayed value up to date as time passes. */
    sync?: boolean;
    /** BCP 47 language tag for formatting (e.g. "en", "de", "ja"). Inherits from the document when unset. */
    lang?: string;
}

export const FlintRelativeTime = createComponent({
    tagName: 'flint-relative-time',
    elementClass: FlintRelativeTimeElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintRelativeTimeProps & React.RefAttributes<FlintRelativeTimeElement>>;
