// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/flint-command.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCommandEmpty as FlintCommandEmptyElement } from '@getufy/flint-ui/command/flint-command';

/**
 * Empty state message shown when no command items match the current query.
Managed automatically by the parent `flint-command` element.
 *
 * @slot (default) - Message text, e.g. "No results found."
 */
export interface FlintCommandEmptyProps extends React.HTMLAttributes<FlintCommandEmptyElement> {
}

export const FlintCommandEmpty = createComponent({
    tagName: 'flint-command-empty',
    elementClass: FlintCommandEmptyElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintCommandEmptyProps & React.RefAttributes<FlintCommandEmptyElement>>;
