// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/switch/flint-switch.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintSwitch as FlintSwitchElement } from 'flint-ui/switch/flint-switch';

export const FlintSwitch = createComponent({
    tagName: 'flint-switch',
    elementClass: FlintSwitchElement,
    react: React,
    events: {
        onFlintSwitchChange: 'flint-switch-change' as EventName<CustomEvent>,
    },
});

export type FlintSwitchProps = React.ComponentProps<typeof FlintSwitch>;
