// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/card/flint-card-action-area.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCardActionArea as FlintCardActionAreaElement } from '@getufy/flint-ui/card/flint-card-action-area';

export const FlintCardActionArea = createComponent({
    tagName: 'flint-card-action-area',
    elementClass: FlintCardActionAreaElement,
    react: React,
});

export type FlintCardActionAreaProps = React.ComponentProps<typeof FlintCardActionArea>;
