// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/input-otp/flint-input-otp.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintInputOtp as FlintInputOtpElement } from 'flint-ui/input-otp/flint-input-otp';

export const FlintInputOtp = createComponent({
    tagName: 'flint-input-otp',
    elementClass: FlintInputOtpElement,
    react: React,
    events: {
        onFlintOtpChange: 'flint-otp-change' as EventName<CustomEvent>,
        onFlintOtpComplete: 'flint-otp-complete' as EventName<CustomEvent>,
    },
});

export type FlintInputOtpProps = React.ComponentProps<typeof FlintInputOtp>;
