// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintDialogActions as FlintDialogActionsElement } from '@getufy/flint-ui/dialog/flint-dialog';

/**
 * flint-dialog-actions: footer button row for a dialog.
Use the `align` prop to control button alignment.
 */
export interface FlintDialogActionsProps extends React.HTMLAttributes<FlintDialogActionsElement> {
    /** Alignment of action buttons: 'end' (default), 'start', 'center', 'space-between'. */
    align?: 'start' | 'center' | 'end' | 'space-between';
}

export const FlintDialogActions = createComponent({
    tagName: 'flint-dialog-actions',
    elementClass: FlintDialogActionsElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintDialogActionsProps & React.RefAttributes<FlintDialogActionsElement>>;
