// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/radio/flint-radio.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintRadioGroup as FlintRadioGroupElement } from 'flint-ui/radio/flint-radio';

export const FlintRadioGroup = createComponent({
    tagName: 'flint-radio-group',
    elementClass: FlintRadioGroupElement,
    react: React,
    events: {
        onFlintRadioGroupChange: 'flint-radio-group-change' as EventName<CustomEvent>,
    },
});

export type FlintRadioGroupProps = React.ComponentProps<typeof FlintRadioGroup>;
