// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintDialogTitle as FlintDialogTitleElement } from '@getufy/flint-ui/dialog/flint-dialog';

/**
 * flint-dialog-title: heading area of a dialog.
The parent `<flint-dialog>` reads this element's text content via slotchange
to set `aria-label` on the dialog panel.
 */
export interface FlintDialogTitleProps extends React.HTMLAttributes<FlintDialogTitleElement> {
}

export const FlintDialogTitle = createComponent({
    tagName: 'flint-dialog-title',
    elementClass: FlintDialogTitleElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintDialogTitleProps & React.RefAttributes<FlintDialogTitleElement>>;
