// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/button/flint-button-group.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintButtonGroup as FlintButtonGroupElement } from '@getufy/flint-ui/button/flint-button-group';

export interface FlintButtonGroupProps extends React.HTMLAttributes<FlintButtonGroupElement> {
}

export const FlintButtonGroup = createComponent({
    tagName: 'flint-button-group',
    elementClass: FlintButtonGroupElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintButtonGroupProps & React.RefAttributes<FlintButtonGroupElement>>;
