// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/input-otp/flint-input-otp.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintInputOtpSlot as FlintInputOtpSlotElement } from 'flint-ui/input-otp/flint-input-otp';

export const FlintInputOtpSlot = createComponent({
    tagName: 'flint-input-otp-slot',
    elementClass: FlintInputOtpSlotElement,
    react: React,
});

export type FlintInputOtpSlotProps = React.ComponentProps<typeof FlintInputOtpSlot>;
