// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/flint-time-picker.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintStaticTimePicker as FlintStaticTimePickerElement } from '@getufy/flint-ui/time-picker/flint-time-picker';

/**
 * Static Time Picker: an always-visible inline clock.
 */
export interface FlintStaticTimePickerProps extends React.HTMLAttributes<FlintStaticTimePickerElement> {
    /** Time value in HH:MM:SS format. */
    value?: string;
    /** Whether to use 12-hour (AM/PM) format instead of 24-hour. */
    ampm?: boolean;
    /** Whether to show a seconds section. */
    seconds?: boolean;
    /** Fired when the time value changes. detail: `{ value: string }` */
    onFlintStaticTimePickerChange?: (event: CustomEvent) => void;
}

export const FlintStaticTimePicker = createComponent({
    tagName: 'flint-static-time-picker',
    elementClass: FlintStaticTimePickerElement,
    react: React,
    events: {
        onFlintStaticTimePickerChange: 'flint-static-time-picker-change' as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintStaticTimePickerProps & React.RefAttributes<FlintStaticTimePickerElement>>;
