// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/stack/flint-stack.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintStack as FlintStackElement } from '@getufy/flint-ui/stack/flint-stack';

export const FlintStack = createComponent({
    tagName: 'flint-stack',
    elementClass: FlintStackElement,
    react: React,
});

export type FlintStackProps = React.ComponentProps<typeof FlintStack>;
