// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/accordion/flint-accordion.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintAccordionActions as FlintAccordionActionsElement } from '@getufy/flint-ui/accordion/flint-accordion';

/**
 * Accordion Actions: an optional wrapper that groups a set of buttons.
 */
export interface FlintAccordionActionsProps extends React.HTMLAttributes<FlintAccordionActionsElement> {
}

export const FlintAccordionActions = createComponent({
    tagName: 'flint-accordion-actions',
    elementClass: FlintAccordionActionsElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintAccordionActionsProps & React.RefAttributes<FlintAccordionActionsElement>>;
