// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintDialogContentText as FlintDialogContentTextElement } from '@getufy/flint-ui/dialog/flint-dialog';

/**
 * flint-dialog-content-text: body text inside a dialog content area.
 */
export interface FlintDialogContentTextProps extends React.HTMLAttributes<FlintDialogContentTextElement> {
}

export const FlintDialogContentText = createComponent({
    tagName: 'flint-dialog-content-text',
    elementClass: FlintDialogContentTextElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintDialogContentTextProps & React.RefAttributes<FlintDialogContentTextElement>>;
