// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintMenubarItem as FlintMenubarItemElement } from '@getufy/flint-ui/menubar/flint-menubar';

export const FlintMenubarItem = createComponent({
    tagName: 'flint-menubar-item',
    elementClass: FlintMenubarItemElement,
    react: React,
    events: {
        onFlintMenubarItemSelect: 'flint-menubar-item-select' as EventName<CustomEvent>,
    },
});

export type FlintMenubarItemProps = React.ComponentProps<typeof FlintMenubarItem>;
