// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/date-field/flint-date-field.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintDateField as FlintDateFieldElement } from '@getufy/flint-ui/date-field/flint-date-field';

export const FlintDateField = createComponent({
    tagName: 'flint-date-field',
    elementClass: FlintDateFieldElement,
    react: React,
    events: {
        onFlintDateFieldClear: 'flint-date-field-clear' as EventName<CustomEvent>,
        onFlintDateFieldChange: 'flint-date-field-change' as EventName<CustomEvent>,
    },
});

export type FlintDateFieldProps = React.ComponentProps<typeof FlintDateField>;
