// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintMenubarSeparator as FlintMenubarSeparatorElement } from 'flint-ui/menubar/flint-menubar';

export const FlintMenubarSeparator = createComponent({
    tagName: 'flint-menubar-separator',
    elementClass: FlintMenubarSeparatorElement,
    react: React,
});

export type FlintMenubarSeparatorProps = React.ComponentProps<typeof FlintMenubarSeparator>;
