// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintDialogContent as FlintDialogContentElement } from '@getufy/flint-ui/dialog/flint-dialog';

/**
 * flint-dialog-content: scrollable content area of a dialog.
 */
export interface FlintDialogContentProps extends React.HTMLAttributes<FlintDialogContentElement> {
}

export const FlintDialogContent = createComponent({
    tagName: 'flint-dialog-content',
    elementClass: FlintDialogContentElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintDialogContentProps & React.RefAttributes<FlintDialogContentElement>>;
