// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/flint-command.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCommandList as FlintCommandListElement } from '@getufy/flint-ui/command/flint-command';

/**
 * Scrollable list container for command items and groups.
 *
 * @slot - `flint-command-group`, `flint-command-item`, `flint-command-empty`, `flint-command-separator`.
 */
export interface FlintCommandListProps extends React.HTMLAttributes<FlintCommandListElement> {
}

export const FlintCommandList = createComponent({
    tagName: 'flint-command-list',
    elementClass: FlintCommandListElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintCommandListProps & React.RefAttributes<FlintCommandListElement>>;
