// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintMenubarItem as FlintMenubarItemElement } from '@getufy/flint-ui/menubar/flint-menubar';
import { FlintMenubarItemEvents } from '../events/flint-menubar-item.js';

export interface FlintMenubarItemSelectDetail {
    value: string;
}

/**
 * A single interactive option inside a menubar dropdown.
 *
 * @slot (default) - Item label text plus optional `<flint-menubar-shortcut>`.
 */
export interface FlintMenubarItemProps extends React.HTMLAttributes<FlintMenubarItemElement> {
    /** Whether the item is non-interactive. */
    disabled?: boolean;
    /** Whether the item is visually highlighted (e.g. via keyboard or hover). */
    highlighted?: boolean;
    /** Whether the item label is inset to align with checkbox/radio items. */
    inset?: boolean;
    /** Explicit value for the select event. Falls back to label text (excludes shortcut). */
    value?: string;
    /** Fired on activation. detail: `{ value: string }` */
    onFlintMenubarItemSelect?: (event: CustomEvent<FlintMenubarItemSelectDetail>) => void;
}

export const FlintMenubarItem = createComponent({
    tagName: 'flint-menubar-item',
    elementClass: FlintMenubarItemElement,
    react: React,
    events: {
        onFlintMenubarItemSelect: FlintMenubarItemEvents.SELECT as EventName<CustomEvent<FlintMenubarItemSelectDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintMenubarItemProps & React.RefAttributes<FlintMenubarItemElement>>;
