// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/resizable/flint-resizable.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintResizablePanel as FlintResizablePanelElement } from '@getufy/flint-ui/resizable/flint-resizable';

export const FlintResizablePanel = createComponent({
    tagName: 'flint-resizable-panel',
    elementClass: FlintResizablePanelElement,
    react: React,
});

export type FlintResizablePanelProps = React.ComponentProps<typeof FlintResizablePanel>;
