// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/bottom-navigation/flint-bottom-navigation.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintBottomNavigation as FlintBottomNavigationElement } from '@getufy/flint-ui/bottom-navigation/flint-bottom-navigation';
import { FlintBottomNavigationEvents } from '../events/flint-bottom-navigation.js';

export interface FlintBottomNavigationChangeDetail {
    value: number | string;
}

/**
 * Bottom Navigation bars allow movement between primary destinations in an app.
 *
 * @slot (default) - destinations (flint-bottom-navigation-action).
 */
export interface FlintBottomNavigationProps extends Omit<React.HTMLAttributes<FlintBottomNavigationElement>, 'defaultValue'> {
    /** The value of the currently selected action. */
    value?: unknown;
    /** Initial selected value for uncontrolled usage. */
    defaultValue?: unknown | undefined;
    /** If true, all labels are shown at all times. */
    showLabels?: boolean;
    /** Dispatched when the selected value changes. detail: `{ value: number | string }` */
    onFlintBottomNavigationChange?: (event: CustomEvent<FlintBottomNavigationChangeDetail>) => void;
}

export const FlintBottomNavigation = createComponent({
    tagName: 'flint-bottom-navigation',
    elementClass: FlintBottomNavigationElement,
    react: React,
    events: {
        onFlintBottomNavigationChange: FlintBottomNavigationEvents.CHANGE as EventName<CustomEvent<FlintBottomNavigationChangeDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintBottomNavigationProps & React.RefAttributes<FlintBottomNavigationElement>>;
