// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/image-comparer/flint-image-comparer.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintImageComparer as FlintImageComparerElement } from '@getufy/flint-ui/image-comparer/flint-image-comparer';
import { FlintImageComparerEvents } from '../events/flint-image-comparer.js';

export interface FlintImageComparerChangeDetail {
    position: number;
}

/**
 * `flint-image-comparer` — Compare two images side-by-side with a draggable slider.
 *
 * @slot before - The before image (`<img>` or `<svg>`).
 * @slot after - The after image (`<img>` or `<svg>`).
 * @slot handle - Custom handle content (replaces the default arrows icon).
 */
export interface FlintImageComparerProps extends React.HTMLAttributes<FlintImageComparerElement> {
    /** The position of the divider as a percentage (0–100). */
    position?: number;
    /** Whether the comparer is disabled. */
    disabled?: boolean;
    /** Fired when the position changes. Detail: `{ position: number }`. */
    onFlintImageComparerChange?: (event: CustomEvent<FlintImageComparerChangeDetail>) => void;
}

export const FlintImageComparer = createComponent({
    tagName: 'flint-image-comparer',
    elementClass: FlintImageComparerElement,
    react: React,
    events: {
        onFlintImageComparerChange: FlintImageComparerEvents.CHANGE as EventName<CustomEvent<FlintImageComparerChangeDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintImageComparerProps & React.RefAttributes<FlintImageComparerElement>>;
