// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/date-range-picker/flint-date-range-calendar.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintDateRangeCalendar as FlintDateRangeCalendarElement } from 'flint-ui/date-range-picker/flint-date-range-calendar';

export const FlintDateRangeCalendar = createComponent({
    tagName: 'flint-date-range-calendar',
    elementClass: FlintDateRangeCalendarElement,
    react: React,
    events: {
        onRangeSelect: 'flint-date-range-picker-select' as EventName<CustomEvent>,
    },
});

export type FlintDateRangeCalendarProps = React.ComponentProps<typeof FlintDateRangeCalendar>;
