// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/stepper/flint-stepper.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintStep as FlintStepElement } from '@getufy/flint-ui/stepper/flint-stepper';

export const FlintStep = createComponent({
    tagName: 'flint-step',
    elementClass: FlintStepElement,
    react: React,
    events: {
        onFlintStepClick: 'flint-step-click' as EventName<CustomEvent>,
    },
});

export type FlintStepProps = React.ComponentProps<typeof FlintStep>;
