// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/stepper/flint-stepper.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintStepLabel as FlintStepLabelElement } from '@getufy/flint-ui/stepper/flint-stepper';

export const FlintStepLabel = createComponent({
    tagName: 'flint-step-label',
    elementClass: FlintStepLabelElement,
    react: React,
});

export type FlintStepLabelProps = React.ComponentProps<typeof FlintStepLabel>;
