// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintMenubarSubContent as FlintMenubarSubContentElement } from 'flint-ui/menubar/flint-menubar';

export const FlintMenubarSubContent = createComponent({
    tagName: 'flint-menubar-sub-content',
    elementClass: FlintMenubarSubContentElement,
    react: React,
});

export type FlintMenubarSubContentProps = React.ComponentProps<typeof FlintMenubarSubContent>;
