// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/card/flint-card-content.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCardContent as FlintCardContentElement } from 'flint-ui/card/flint-card-content';

export const FlintCardContent = createComponent({
    tagName: 'flint-card-content',
    elementClass: FlintCardContentElement,
    react: React,
});

export type FlintCardContentProps = React.ComponentProps<typeof FlintCardContent>;
