// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/drawer/flint-drawer.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintDrawer as FlintDrawerElement } from '@getufy/flint-ui/drawer/flint-drawer';
import { FlintDrawerEvents } from '../events/flint-drawer.js';

export interface FlintDrawerCloseDetail {
    open: false;
}

/**
 * Navigation drawers provide ergonomic access to destinations in a site or app.
 *
 * @slot (default) - Drawer content.
 */
export interface FlintDrawerProps extends React.HTMLAttributes<FlintDrawerElement> {
    dependencies?: object;
    /** Whether the drawer is open. */
    open?: boolean;
    /** Initial open state for uncontrolled usage. */
    defaultOpen?: boolean;
    /** Side from which the drawer slides in. */
    anchor?: 'left' | 'right' | 'top' | 'bottom';
    /** Drawer behavior mode. */
    variant?: 'temporary' | 'persistent' | 'mini';
    /** Whether the drawer uses edge spacing. */
    edge?: boolean;
    /** Whether the drawer is contained within its parent. */
    container?: boolean;
    /** Accessible label for the drawer panel (used as aria-label on the panel). */
    label?: string;
    /** Dispatched when the drawer requests to be closed (backdrop click or Escape). detail: `{ open: false }` */
    onFlintDrawerClose?: (event: CustomEvent<FlintDrawerCloseDetail>) => void;
}

export const FlintDrawer = createComponent({
    tagName: 'flint-drawer',
    elementClass: FlintDrawerElement,
    react: React,
    events: {
        onFlintDrawerClose: FlintDrawerEvents.CLOSE as EventName<CustomEvent<FlintDrawerCloseDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintDrawerProps & React.RefAttributes<FlintDrawerElement>>;
