// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/flint-command.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCommandInput as FlintCommandInputElement } from 'flint-ui/command/flint-command';

export const FlintCommandInput = createComponent({
    tagName: 'flint-command-input',
    elementClass: FlintCommandInputElement,
    react: React,
});

export type FlintCommandInputProps = React.ComponentProps<typeof FlintCommandInput>;
