// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tabs/flint-tabs.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTabs as FlintTabsElement } from '@getufy/flint-ui/tabs/flint-tabs';
import { FlintTabsEvents } from '../events/flint-tabs.js';

export interface FlintTabChangeDetail {
    value: string;
}

/**
 * Tabs: container that coordinates tab selection and panel visibility.
 */
export interface FlintTabsProps extends Omit<React.HTMLAttributes<FlintTabsElement>, 'defaultValue'> {
    /** Current active tab value (controlled). When set, the component reflects this value and does not manage its own state. */
    value?: string;
    /** Layout direction of the tabs. */
    orientation?: 'horizontal' | 'vertical';
    /** Display variant controlling tab sizing and scrollability. */
    variant?: 'standard' | 'fullWidth' | 'scrollable';
    /** Whether to center the tabs. */
    centered?: boolean;
    /** Whether to show scroll buttons in scrollable mode. */
    scrollButtons?: 'auto' | 'false';
    /** Text color: 'primary' | 'secondary' | 'inherit' | any CSS color. */
    textColor?: string;
    /** Indicator color: 'primary' | 'secondary' | any CSS color. */
    indicatorColor?: string;
    /** Initial value (uncontrolled). Only used on first render; ignored after mount. */
    defaultValue?: string;
    /** Fired when the active tab changes. detail: `{ value: string }` */
    onFlintTabChange?: (event: CustomEvent<FlintTabChangeDetail>) => void;
}

export const FlintTabs = createComponent({
    tagName: 'flint-tabs',
    elementClass: FlintTabsElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintTabChange: FlintTabsEvents.TAB_CHANGE as EventName<CustomEvent<FlintTabChangeDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintTabsProps & React.RefAttributes<FlintTabsElement>>;
