// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/flint-item.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintItemContent as FlintItemContentElement } from '@getufy/flint-ui/item/flint-item';

export const FlintItemContent = createComponent({
    tagName: 'flint-item-content',
    elementClass: FlintItemContentElement,
    react: React,
});

export type FlintItemContentProps = React.ComponentProps<typeof FlintItemContent>;
