// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/resizable/flint-resizable.component.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintResizableHandle as FlintResizableHandleElement } from '@getufy/flint-ui/resizable/flint-resizable';

export interface FlintResizableHandleProps extends React.HTMLAttributes<FlintResizableHandleElement> {
    /** Show a visible drag grip. */
    withHandle?: boolean;
    /** Disable interaction. */
    disabled?: boolean;
}

export const FlintResizableHandle = createComponent({
    tagName: 'flint-resizable-handle',
    elementClass: FlintResizableHandleElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintResizableHandleProps & React.RefAttributes<FlintResizableHandleElement>>;
