// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/flint-command.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCommandEmpty as FlintCommandEmptyElement } from 'flint-ui/command/flint-command';

export const FlintCommandEmpty = createComponent({
    tagName: 'flint-command-empty',
    elementClass: FlintCommandEmptyElement,
    react: React,
});

export type FlintCommandEmptyProps = React.ComponentProps<typeof FlintCommandEmpty>;
