// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/checkbox/flint-checkbox.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintCheckbox as FlintCheckboxElement } from '@getufy/flint-ui/checkbox/flint-checkbox';

export const FlintCheckbox = createComponent({
    tagName: 'flint-checkbox',
    elementClass: FlintCheckboxElement,
    react: React,
    events: {
        onFlintCheckboxChange: 'flint-checkbox-change' as EventName<CustomEvent>,
    },
});

export type FlintCheckboxProps = React.ComponentProps<typeof FlintCheckbox>;
