// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/button/flint-toggle-button-group.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintToggleButtonGroup as FlintToggleButtonGroupElement } from 'flint-ui/button/flint-toggle-button-group';

export const FlintToggleButtonGroup = createComponent({
    tagName: 'flint-toggle-button-group',
    elementClass: FlintToggleButtonGroupElement,
    react: React,
    events: {
        onFlintToggleButtonGroupChange: 'flint-toggle-button-group-change' as EventName<CustomEvent>,
    },
});

export type FlintToggleButtonGroupProps = React.ComponentProps<typeof FlintToggleButtonGroup>;
