// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/flint-time-picker.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTimeClock as FlintTimeClockElement } from '@getufy/flint-ui/time-picker/flint-time-picker';

export interface ChangeDetail {
    value: string;
}

/**
 * Time Clock: an analog clock face for selecting hours, minutes, and seconds.
 */
export interface FlintTimeClockProps extends Omit<React.HTMLAttributes<FlintTimeClockElement>, 'onChange'> {
    /** Time value in HH:MM:SS format. */
    value?: string;
    /** Whether to use 12-hour (AM/PM) format instead of 24-hour. */
    ampm?: boolean;
    /** Whether to show a seconds face on the clock. */
    seconds?: boolean;
    /** Currently active clock face view. */
    view?: FlintTimeClockElement['view'];
    /** Fired when the time value changes. */
    onChange?: (event: CustomEvent<ChangeDetail>) => void;
    /** Fired when the clock face view switches. */
    onFlintTimeClockViewChange?: (event: CustomEvent) => void;
}

export const FlintTimeClock = createComponent({
    tagName: 'flint-time-clock',
    elementClass: FlintTimeClockElement,
    react: React,
    events: {
        onChange: 'change' as EventName<CustomEvent<ChangeDetail>>,
        onFlintTimeClockViewChange: 'flint-time-clock-view-change' as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintTimeClockProps & React.RefAttributes<FlintTimeClockElement>>;
