// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/stepper/flint-stepper.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintMobileStepper as FlintMobileStepperElement } from 'flint-ui/stepper/flint-stepper';

export const FlintMobileStepper = createComponent({
    tagName: 'flint-mobile-stepper',
    elementClass: FlintMobileStepperElement,
    react: React,
});

export type FlintMobileStepperProps = React.ComponentProps<typeof FlintMobileStepper>;
