// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tree-view/flint-tree-item.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTreeItem as FlintTreeItemElement } from '@getufy/flint-ui/tree-view/flint-tree-item';
import { FlintTreeItemEvents } from '../events/flint-tree-item.js';

/**
 * A single item inside a `flint-simple-tree-view` or `flint-rich-tree-view`.
 *
 * @slot lead - Leading icon or content.
 * @slot (default) - Item label text.
 */
export interface FlintTreeItemProps extends React.HTMLAttributes<FlintTreeItemElement> {
    /** Unique identifier for this item within the tree */
    itemId?: string;
    /** Label text displayed for this item */
    label?: string;
    /** Whether this item is disabled (non-interactive) */
    disabled?: boolean;
    /** Whether this item's children are visible */
    expanded?: boolean;
    /** When `true`, forces the expand button to render even if no `flint-tree-item` */
    hasChildren?: boolean;
    /** Visual drop position indicator — reflected so CSS :host selectors match */
    dropPosition?: 'before' | 'after' | 'inside' | null;
    /** Whether to show a dedicated drag handle icon */
    showDragHandle?: boolean;
    /**
     * Fired when the item is clicked (detail: { itemId })
     * DOM event: `flint-tree-item-click`
     */
    onFlintTreeItemClick?: (event: CustomEvent) => void;
    /**
     * Fired when expanded state changes (detail: { itemId, expanded })
     * DOM event: `flint-tree-item-toggle`
     */
    onFlintTreeItemToggle?: (event: CustomEvent) => void;
}

export const FlintTreeItem = createComponent({
    tagName: 'flint-tree-item',
    elementClass: FlintTreeItemElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintTreeItemClick: FlintTreeItemEvents.CLICK as EventName<CustomEvent>,
        onFlintTreeItemToggle: FlintTreeItemEvents.TOGGLE as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintTreeItemProps & React.RefAttributes<FlintTreeItemElement>>;
