// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/container/flint-container.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintContainer as FlintContainerElement } from '@getufy/flint-ui/container/flint-container';

export const FlintContainer = createComponent({
    tagName: 'flint-container',
    elementClass: FlintContainerElement,
    react: React,
});

export type FlintContainerProps = React.ComponentProps<typeof FlintContainer>;
