// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/animation/flint-animation.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintAnimation as FlintAnimationElement } from '@getufy/flint-ui/animation/flint-animation';
import { FlintAnimationEvents } from '../events/flint-animation.js';

/**
 * flint-animation: a declarative wrapper that applies Web Animations API
animations to its slotted content.
 *
 * @slot (default) - Content to animate.
 */
export interface FlintAnimationProps extends React.HTMLAttributes<FlintAnimationElement> {
    /** Animation preset name (e.g., 'fade-in', 'slide-up', 'bounce') or */
    name?: string;
    /** Duration in milliseconds. */
    duration?: number;
    /** CSS easing function. */
    easing?: string;
    /** Number of iterations. Use `Infinity` for infinite looping. */
    iterations?: number;
    /** Delay before the animation starts, in milliseconds. */
    delay?: number;
    /** Animation fill mode. */
    fill?: FlintAnimationElement['fill'];
    /** Animation direction. */
    direction?: FlintAnimationElement['direction'];
    /** Set to true to trigger/play the animation. */
    play?: boolean;
    /** Whether to play the animation automatically on first render. */
    playOnConnect?: boolean;
    /** Custom keyframes. When provided, overrides the `name` preset. */
    keyframes?: FlintAnimationElement['keyframes'];
    /** Dispatched when the animation finishes. */
    onFlintAnimationFinish?: (event: CustomEvent) => void;
    /** Dispatched when the animation is cancelled. */
    onFlintAnimationCancel?: (event: CustomEvent) => void;
}

export const FlintAnimation = createComponent({
    tagName: 'flint-animation',
    elementClass: FlintAnimationElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintAnimationFinish: FlintAnimationEvents.FINISH as EventName<CustomEvent>,
        onFlintAnimationCancel: FlintAnimationEvents.CANCEL as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintAnimationProps & React.RefAttributes<FlintAnimationElement>>;
