// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/drawer/flint-drawer.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintDrawer as FlintDrawerElement } from 'flint-ui/drawer/flint-drawer';

export const FlintDrawer = createComponent({
    tagName: 'flint-drawer',
    elementClass: FlintDrawerElement,
    react: React,
    events: {
        onFlintDrawerClose: 'flint-drawer-close' as EventName<CustomEvent>,
    },
});

export type FlintDrawerProps = React.ComponentProps<typeof FlintDrawer>;
