// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/table/flint-table.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintTableCell as FlintTableCellElement } from '@getufy/flint-ui/table/flint-table';

export const FlintTableCell = createComponent({
    tagName: 'flint-table-cell',
    elementClass: FlintTableCellElement,
    react: React,
});

export type FlintTableCellProps = React.ComponentProps<typeof FlintTableCell>;
