// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/flint-range-slider/flint-range-slider.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintRangeSlider as FlintRangeSliderElement } from 'flint-ui/flint-range-slider/flint-range-slider';

export const FlintRangeSlider = createComponent({
    tagName: 'flint-range-slider',
    elementClass: FlintRangeSliderElement,
    react: React,
    events: {
        onFlintRangeSliderChange: 'flint-range-slider-change' as EventName<CustomEvent>,
    },
});

export type FlintRangeSliderProps = React.ComponentProps<typeof FlintRangeSlider>;
