// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/flint-time-picker.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTimePicker as FlintTimePickerElement } from '@getufy/flint-ui/time-picker/flint-time-picker';

/**
 * Time Picker: a configurable time input supporting desktop, mobile, and static variants.
 */
export interface FlintTimePickerProps extends React.HTMLAttributes<FlintTimePickerElement> {
    /** Time value in HH:MM:SS format. */
    value?: string;
    /** Field label text. */
    label?: string;
    /** Picker variant controlling the UI style. */
    variant?: 'desktop' | 'mobile' | 'static' | 'auto';
    /** Whether to use 12-hour (AM/PM) format instead of 24-hour. */
    ampm?: boolean;
    /** Whether to show a seconds segment. */
    seconds?: boolean;
    /** Disables the picker and prevents interaction. */
    disabled?: boolean;
    /** Displays the picker in an error state. */
    error?: boolean;
    /** Helper text shown below the field. */
    helperText?: string;
    /** Error message displayed below the field when in error state. */
    errorMessage?: string;
    /** Fired when the time value changes. detail: `{ value: string }` */
    onFlintTimePickerChange?: (event: CustomEvent) => void;
}

export const FlintTimePicker = createComponent({
    tagName: 'flint-time-picker',
    elementClass: FlintTimePickerElement,
    react: React,
    events: {
        onFlintTimePickerChange: 'flint-time-picker-change' as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintTimePickerProps & React.RefAttributes<FlintTimePickerElement>>;
