// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/flint-dialog.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintDialogActions as FlintDialogActionsElement } from 'flint-ui/dialog/flint-dialog';

export const FlintDialogActions = createComponent({
    tagName: 'flint-dialog-actions',
    elementClass: FlintDialogActionsElement,
    react: React,
});

export type FlintDialogActionsProps = React.ComponentProps<typeof FlintDialogActions>;
