// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/flint-time-picker.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTimePicker as FlintTimePickerElement } from '@getufy/flint-ui/time-picker/flint-time-picker';
import { FlintTimePickerEvents } from '../events/flint-time-picker.js';

export interface FlintTimePickerChangeDetail {
    value: string;
}

/**
 * Time Picker: a configurable time input supporting desktop, mobile, and static variants.
 */
export interface FlintTimePickerProps extends Omit<React.HTMLAttributes<FlintTimePickerElement>, 'defaultValue'> {
    /** Time value in HH:MM:SS format. */
    value?: string;
    /** Field label text. */
    label?: string;
    /**
     * Picker variant controlling the UI style.
     * Allowed values: 'desktop' | 'mobile' | 'static' | 'auto'
     */
    variant?: 'desktop' | 'mobile' | 'static' | 'auto';
    /** Whether to use 12-hour (AM/PM) format instead of 24-hour. */
    ampm?: boolean;
    /** Whether to show a seconds segment. */
    seconds?: boolean;
    /** Disables the picker and prevents interaction. */
    disabled?: boolean;
    /** Displays the picker in an error state. */
    error?: boolean;
    /** Helper text shown below the field. */
    helperText?: string;
    /** Error message displayed below the field when in error state. */
    errorMessage?: string;
    /** Form field name used when submitting form data. */
    name?: string;
    /** Marks the time picker as required for form validation. */
    required?: boolean;
    /** Initial value for uncontrolled usage (HH:MM:SS format). */
    defaultValue?: string;
    /**
     * Fired when the time value changes. detail: `{ value: string }`
     * DOM event: `flint-time-picker-change`
     */
    onFlintTimePickerChange?: (event: CustomEvent<FlintTimePickerChangeDetail>) => void;
}

export const FlintTimePicker = createComponent({
    tagName: 'flint-time-picker',
    elementClass: FlintTimePickerElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintTimePickerChange: FlintTimePickerEvents.CHANGE as EventName<CustomEvent<FlintTimePickerChangeDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintTimePickerProps & React.RefAttributes<FlintTimePickerElement>>;
