// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/combobox/flint-combobox.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintCombobox as FlintComboboxElement } from '@getufy/flint-ui/combobox/flint-combobox';
import { FlintComboboxEvents } from '../events/flint-combobox.js';

export interface FlintComboboxChangeDetail {
    value: string;
}

/**
 * Combobox: a free-text input with dropdown suggestions.
 */
export interface FlintComboboxProps extends Omit<React.HTMLAttributes<FlintComboboxElement>, 'defaultValue'> {
    shadowRootOptions?: object;
    /** The list of suggestion options. */
    options?: FlintComboboxElement['options'];
    /** The current text value. */
    value?: string;
    /** Placeholder text shown when the input is empty. */
    placeholder?: string;
    /** Whether the combobox is disabled. */
    disabled?: boolean;
    /** Marks the combobox as required for form validation. */
    required?: boolean;
    /** Form field name used when submitting form data. */
    name?: string;
    /** Initial value for uncontrolled usage. */
    defaultValue?: string;
    /** Fired when the value changes. detail: `{ value: string }` */
    onFlintComboboxChange?: (event: CustomEvent<FlintComboboxChangeDetail>) => void;
}

export const FlintCombobox = createComponent({
    tagName: 'flint-combobox',
    elementClass: FlintComboboxElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintComboboxChange: FlintComboboxEvents.CHANGE as EventName<CustomEvent<FlintComboboxChangeDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintComboboxProps & React.RefAttributes<FlintComboboxElement>>;
