// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/rating/flint-rating.component.ts
//
// Event naming: onFlint[ComponentName][EventType] (e.g. onFlintPaginationChange).
// The props interface is strict — misspelled event names like onFlintPageChange
// will cause a TypeScript error. No index signature is used.

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintRating as FlintRatingElement } from '@getufy/flint-ui/rating/flint-rating';
import { FlintRatingEvents } from '../events/flint-rating.js';

export interface FlintRatingChangeDetail {
    value: number;
}

/**
 * Rating: a star-based rating input.
 */
export interface FlintRatingProps extends Omit<React.HTMLAttributes<FlintRatingElement>, 'defaultValue'> {
    shadowRootOptions?: object;
    /** Current rating value. */
    value?: number;
    /** Maximum number of stars. */
    max?: number;
    /** Whether the rating is read-only. */
    readonly?: boolean;
    /** Whether the rating is disabled. */
    disabled?: boolean;
    /** Whether clicking the current value clears the rating. */
    clearable?: boolean;
    /** Initial rating value for uncontrolled mode. */
    defaultValue?: number;
    /**
     * Size of the rating stars.
     * Allowed values: 'sm' | 'md' | 'lg'
     */
    size?: 'sm' | 'md' | 'lg';
    /** Form field name for the hidden input. */
    name?: string;
    /** Accessible label for the rating group. */
    label?: string;
    /**
     * Rating step precision (1 for full stars, 0.5 for half stars).
     * Type: `1 | 0.5`
     */
    precision?: FlintRatingElement['precision'];
    /** Marks the rating as required for form validation. */
    required?: boolean;
    /**
     * Fired when the rating value changes. detail: `{ value: number }`
     * DOM event: `flint-rating-change`
     */
    onFlintRatingChange?: (event: CustomEvent<FlintRatingChangeDetail>) => void;
}

export const FlintRating = createComponent({
    tagName: 'flint-rating',
    elementClass: FlintRatingElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintRatingChange: FlintRatingEvents.CHANGE as EventName<CustomEvent<FlintRatingChangeDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintRatingProps & React.RefAttributes<FlintRatingElement>>;
