// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/card/flint-card-actions.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintCardActions as FlintCardActionsElement } from '@getufy/flint-ui/card/flint-card-actions';

export interface FlintCardActionsProps extends React.HTMLAttributes<FlintCardActionsElement> {
}

export const FlintCardActions = createComponent({
    tagName: 'flint-card-actions',
    elementClass: FlintCardActionsElement,
    react: React,
}) as unknown as React.ForwardRefExoticComponent<FlintCardActionsProps & React.RefAttributes<FlintCardActionsElement>>;
