// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tree-view/flint-rich-tree-view.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintRichTreeView as FlintRichTreeViewElement } from '@getufy/flint-ui/tree-view/flint-rich-tree-view';
import { FlintRichTreeViewEvents } from '../events/flint-rich-tree-view.js';

/**
 * A data-driven tree view that renders its structure from an `items` array.
 */
export interface FlintRichTreeViewProps extends React.HTMLAttributes<FlintRichTreeViewElement> {
    dependencies?: object;
    /** Array of item data objects. */
    items?: FlintRichTreeViewElement['items'];
    /** Optional lazy-load data source. */
    dataSource?: FlintRichTreeViewElement['dataSource'];
    /** Extract unique ID (default: `item.id`). */
    getItemId?: FlintRichTreeViewElement['getItemId'];
    /** Extract label (default: `item.label`). */
    getItemLabel?: FlintRichTreeViewElement['getItemLabel'];
    /** Extract children (default: `item.children`). */
    getItemChildren?: FlintRichTreeViewElement['getItemChildren'];
    /** Return true to disable an item. */
    isItemDisabled?: FlintRichTreeViewElement['isItemDisabled'];
    /** When `true`, disabled items can receive keyboard focus. */
    disabledItemsFocusable?: boolean;
    /** Callback invoked when a tree item is clicked or activated via keyboard. */
    onItemClick?: FlintRichTreeViewElement['onItemClick'];
    /** What interaction triggers expand/collapse. */
    expansionTrigger?: 'content' | 'iconContainer';
    /** **Controlled mode.** The set of item IDs that should be expanded. */
    expandedItems?: string[] | undefined;
    /** **Uncontrolled mode.** Item IDs to expand on initial mount. */
    defaultExpandedItems?: string[];
    /** Callback fired when the user toggles an item's expansion. */
    onExpandedItemsChange?: FlintRichTreeViewElement['onExpandedItemsChange'];
    /** When `true`, enables drag-and-drop reordering of items. */
    itemsReordering?: boolean;
    /** Function that determines if a specific item can be reordered. */
    isItemReorderable?: FlintRichTreeViewElement['isItemReorderable'];
    /** Function that determines if an item can be moved to a specific target position. */
    canMoveItemToNewPosition?: FlintRichTreeViewElement['canMoveItemToNewPosition'];
    /** Whether to use a drag handle icon for reordering. */
    itemsReorderingHandle?: boolean;
    /** Fired when an item's position changes via reordering. */
    onItemPositionChange?: FlintRichTreeViewElement['onItemPositionChange'];
    /** When a lazy-loading dataSource call fails (detail: { message, id, error }) */
    onFlintTreeViewError?: (event: CustomEvent) => void;
    /** When the expanded set changes (detail: { expandedItems }) */
    onFlintTreeViewExpandedItemsChange?: (event: CustomEvent) => void;
    onFlintTreeViewItemPositionChange?: (event: CustomEvent) => void;
    /** When a tree item is activated (detail: { itemId }) */
    onFlintTreeViewItemClick?: (event: CustomEvent) => void;
}

export const FlintRichTreeView = createComponent({
    tagName: 'flint-rich-tree-view',
    elementClass: FlintRichTreeViewElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintTreeViewError: FlintRichTreeViewEvents.TREE_VIEW_ERROR as EventName<CustomEvent>,
        onFlintTreeViewExpandedItemsChange: FlintRichTreeViewEvents.TREE_VIEW_EXPANDED_ITEMS_CHANGE as EventName<CustomEvent>,
        onFlintTreeViewItemPositionChange: FlintRichTreeViewEvents.TREE_VIEW_ITEM_POSITION_CHANGE as EventName<CustomEvent>,
        onFlintTreeViewItemClick: FlintRichTreeViewEvents.TREE_VIEW_ITEM_CLICK as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintRichTreeViewProps & React.RefAttributes<FlintRichTreeViewElement>>;
