// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/flint-command.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintCommandDialog as FlintCommandDialogElement } from 'flint-ui/command/flint-command';

export const FlintCommandDialog = createComponent({
    tagName: 'flint-command-dialog',
    elementClass: FlintCommandDialogElement,
    react: React,
    events: {
        onFlintCommandDialogClose: 'flint-command-dialog-close' as EventName<CustomEvent>,
    },
});

export type FlintCommandDialogProps = React.ComponentProps<typeof FlintCommandDialog>;
