// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tabs/flint-tabs.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintTabs as FlintTabsElement } from '@getufy/flint-ui/tabs/flint-tabs';

/**
 * Tabs: container that coordinates tab selection and panel visibility.
 */
export interface FlintTabsProps extends Omit<React.HTMLAttributes<FlintTabsElement>, 'defaultValue'> {
    /** The currently active tab value. */
    value?: string;
    /** Layout direction of the tabs. */
    orientation?: 'horizontal' | 'vertical';
    /** Display variant controlling tab sizing and scrollability. */
    variant?: 'standard' | 'fullWidth' | 'scrollable';
    /** Whether to center the tabs. */
    centered?: boolean;
    /** Whether to show scroll buttons in scrollable mode. */
    scrollButtons?: 'auto' | 'false';
    /** 'primary' | 'secondary' | 'inherit' | any CSS color */
    textColor?: string;
    /** 'primary' | 'secondary' | any CSS color */
    indicatorColor?: string;
    /** Uncontrolled mode: initial value if `value` not set */
    defaultValue?: string;
    /** Fired when the active tab changes. */
    onFlintTabChange?: (event: CustomEvent) => void;
}

export const FlintTabs = createComponent({
    tagName: 'flint-tabs',
    elementClass: FlintTabsElement,
    react: React,
    events: {
        onFlintTabChange: 'flint-tab-change' as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintTabsProps & React.RefAttributes<FlintTabsElement>>;
