// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/speed-dial/flint-speed-dial.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintSpeedDial as FlintSpeedDialElement } from '@getufy/flint-ui/speed-dial/flint-speed-dial';

export const FlintSpeedDial = createComponent({
    tagName: 'flint-speed-dial',
    elementClass: FlintSpeedDialElement,
    react: React,
});

export type FlintSpeedDialProps = React.ComponentProps<typeof FlintSpeedDial>;
