// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintMenubarContent as FlintMenubarContentElement } from '@getufy/flint-ui/menubar/flint-menubar';
import { FlintMenubarContentEvents } from '../events/flint-menubar-content.js';

/**
 * The dropdown content panel for a menubar menu.
Positioned absolutely below the trigger.
 */
export interface FlintMenubarContentProps extends React.HTMLAttributes<FlintMenubarContentElement> {
    /** Whether the content dropdown panel is visible. */
    open?: boolean;
    onFlintMenubarRequestClose?: (event: CustomEvent) => void;
}

export const FlintMenubarContent = createComponent({
    tagName: 'flint-menubar-content',
    elementClass: FlintMenubarContentElement,
    react: React,
    events: {
        onFlintMenubarRequestClose: FlintMenubarContentEvents.MENUBAR_REQUEST_CLOSE as EventName<CustomEvent>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintMenubarContentProps & React.RefAttributes<FlintMenubarContentElement>>;
