// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/format-number/flint-format-number.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintFormatNumber as FlintFormatNumberElement } from 'flint-ui/format-number/flint-format-number';

export const FlintFormatNumber = createComponent({
    tagName: 'flint-format-number',
    elementClass: FlintFormatNumberElement,
    react: React,
});

export type FlintFormatNumberProps = React.ComponentProps<typeof FlintFormatNumber>;
