// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/list/flint-list.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintListItemAvatar as FlintListItemAvatarElement } from '@getufy/flint-ui/list/flint-list';

export const FlintListItemAvatar = createComponent({
    tagName: 'flint-list-item-avatar',
    elementClass: FlintListItemAvatarElement,
    react: React,
});

export type FlintListItemAvatarProps = React.ComponentProps<typeof FlintListItemAvatar>;
