// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/list/flint-list.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintListSubheader as FlintListSubheaderElement } from 'flint-ui/list/flint-list';

export const FlintListSubheader = createComponent({
    tagName: 'flint-list-subheader',
    elementClass: FlintListSubheaderElement,
    react: React,
});

export type FlintListSubheaderProps = React.ComponentProps<typeof FlintListSubheader>;
