// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintMenubarRadioItem as FlintMenubarRadioItemElement } from '@getufy/flint-ui/menubar/flint-menubar';

export const FlintMenubarRadioItem = createComponent({
    tagName: 'flint-menubar-radio-item',
    elementClass: FlintMenubarRadioItemElement,
    react: React,
    events: {
        onFlintMenubarRadioSelect: 'flint-menubar-radio-select' as EventName<CustomEvent>,
    },
});

export type FlintMenubarRadioItemProps = React.ComponentProps<typeof FlintMenubarRadioItem>;
