// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/input-otp/flint-input-otp.component.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintInputOtp as FlintInputOtpElement } from '@getufy/flint-ui/input-otp/flint-input-otp';
import { FlintInputOtpEvents } from '../events/flint-input-otp.js';

export interface FlintOtpChangeDetail {
    value: string;
}

export interface FlintOtpCompleteDetail {
    value: string;
}

/**
 * Accessible one-time password input with copy/paste support.
Manages a hidden native `<input>` and syncs each `flint-input-otp-slot`
with the appropriate character and active-cursor state.
 *
 * @slot (default) - Accepts `flint-input-otp-group`, `flint-input-otp-separator`, and `flint-input-otp-slot` elements.
 */
export interface FlintInputOtpProps extends Omit<React.HTMLAttributes<FlintInputOtpElement>, 'defaultValue'> {
    /** Current OTP value. Reflects to attribute for external observation. */
    value?: string;
    /** Initial uncontrolled value. Has no effect after the first render. */
    defaultValue?: string;
    /** Total number of character slots. */
    maxLength?: number;
    /** Per-character regex pattern string. Characters failing the test are */
    pattern?: string;
    /** Disables the OTP input. */
    disabled?: boolean;
    /** Form field name used when submitting form data. */
    name?: string;
    /** Marks the OTP input as required for form validation. */
    required?: boolean;
    /** Accessible label for the hidden input (used as aria-label). */
    label?: string;
    /** Optional description text for the hidden input (used as aria-describedby). */
    description?: string;
    /** Fired on every value change. `detail: { value: string }`. */
    onFlintOtpChange?: (event: CustomEvent<FlintOtpChangeDetail>) => void;
    /** Fired when `maxLength` chars have been entered. `detail: { value: string }`. */
    onFlintOtpComplete?: (event: CustomEvent<FlintOtpCompleteDetail>) => void;
}

export const FlintInputOtp = createComponent({
    tagName: 'flint-input-otp',
    elementClass: FlintInputOtpElement,
    react: React,
    events: {
        onClick: 'click' as EventName<MouseEvent>,
        onDoubleClick: 'dblclick' as EventName<MouseEvent>,
        onContextMenu: 'contextmenu' as EventName<MouseEvent>,
        onMouseDown: 'mousedown' as EventName<MouseEvent>,
        onMouseUp: 'mouseup' as EventName<MouseEvent>,
        onMouseEnter: 'mouseenter' as EventName<MouseEvent>,
        onMouseLeave: 'mouseleave' as EventName<MouseEvent>,
        onMouseMove: 'mousemove' as EventName<MouseEvent>,
        onMouseOver: 'mouseover' as EventName<MouseEvent>,
        onMouseOut: 'mouseout' as EventName<MouseEvent>,
        onKeyDown: 'keydown' as EventName<KeyboardEvent>,
        onKeyUp: 'keyup' as EventName<KeyboardEvent>,
        onFocus: 'focus' as EventName<FocusEvent>,
        onBlur: 'blur' as EventName<FocusEvent>,
        onInput: 'input' as EventName<Event>,
        onChange: 'change' as EventName<Event>,
        onSubmit: 'submit' as EventName<Event>,
        onReset: 'reset' as EventName<Event>,
        onScroll: 'scroll' as EventName<Event>,
        onWheel: 'wheel' as EventName<WheelEvent>,
        onTouchStart: 'touchstart' as EventName<TouchEvent>,
        onTouchEnd: 'touchend' as EventName<TouchEvent>,
        onTouchMove: 'touchmove' as EventName<TouchEvent>,
        onTouchCancel: 'touchcancel' as EventName<TouchEvent>,
        onPointerDown: 'pointerdown' as EventName<PointerEvent>,
        onPointerUp: 'pointerup' as EventName<PointerEvent>,
        onPointerMove: 'pointermove' as EventName<PointerEvent>,
        onPointerEnter: 'pointerenter' as EventName<PointerEvent>,
        onPointerLeave: 'pointerleave' as EventName<PointerEvent>,
        onPointerOver: 'pointerover' as EventName<PointerEvent>,
        onPointerOut: 'pointerout' as EventName<PointerEvent>,
        onPointerCancel: 'pointercancel' as EventName<PointerEvent>,
        onDrag: 'drag' as EventName<DragEvent>,
        onDragStart: 'dragstart' as EventName<DragEvent>,
        onDragEnd: 'dragend' as EventName<DragEvent>,
        onDragEnter: 'dragenter' as EventName<DragEvent>,
        onDragLeave: 'dragleave' as EventName<DragEvent>,
        onDragOver: 'dragover' as EventName<DragEvent>,
        onDrop: 'drop' as EventName<DragEvent>,
        onCopy: 'copy' as EventName<ClipboardEvent>,
        onCut: 'cut' as EventName<ClipboardEvent>,
        onPaste: 'paste' as EventName<ClipboardEvent>,
        onAnimationStart: 'animationstart' as EventName<AnimationEvent>,
        onAnimationEnd: 'animationend' as EventName<AnimationEvent>,
        onAnimationIteration: 'animationiteration' as EventName<AnimationEvent>,
        onTransitionEnd: 'transitionend' as EventName<TransitionEvent>,
        onFlintOtpChange: FlintInputOtpEvents.OTP_CHANGE as EventName<CustomEvent<FlintOtpChangeDetail>>,
        onFlintOtpComplete: FlintInputOtpEvents.OTP_COMPLETE as EventName<CustomEvent<FlintOtpCompleteDetail>>,
    },
}) as unknown as React.ForwardRefExoticComponent<FlintInputOtpProps & React.RefAttributes<FlintInputOtpElement>>;
