// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/flint-item.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintItemSeparator as FlintItemSeparatorElement } from '@getufy/flint-ui/item/flint-item';

export const FlintItemSeparator = createComponent({
    tagName: 'flint-item-separator',
    elementClass: FlintItemSeparatorElement,
    react: React,
});

export type FlintItemSeparatorProps = React.ComponentProps<typeof FlintItemSeparator>;
