// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/list/flint-list.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintListItemIcon as FlintListItemIconElement } from 'flint-ui/list/flint-list';

export const FlintListItemIcon = createComponent({
    tagName: 'flint-list-item-icon',
    elementClass: FlintListItemIconElement,
    react: React,
});

export type FlintListItemIconProps = React.ComponentProps<typeof FlintListItemIcon>;
