// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/radio/flint-radio.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { FlintRadio as FlintRadioElement } from 'flint-ui/radio/flint-radio';

export const FlintRadio = createComponent({
    tagName: 'flint-radio',
    elementClass: FlintRadioElement,
    react: React,
    events: {
        onFlintRadioSelect: 'flint-radio-select' as EventName<CustomEvent>,
    },
});

export type FlintRadioProps = React.ComponentProps<typeof FlintRadio>;
