// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/flint-menubar.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { FlintMenubarGroup as FlintMenubarGroupElement } from 'flint-ui/menubar/flint-menubar';

export const FlintMenubarGroup = createComponent({
    tagName: 'flint-menubar-group',
    elementClass: FlintMenubarGroupElement,
    react: React,
});

export type FlintMenubarGroupProps = React.ComponentProps<typeof FlintMenubarGroup>;
