// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/badge/ui-badge.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiBadge as UiBadgeElement } from 'storybook-lit/badge/ui-badge';

export const UiBadge = createComponent({
    tagName: 'ui-badge',
    elementClass: UiBadgeElement,
    react: React,
});

export type UiBadgeProps = React.ComponentProps<typeof UiBadge>;
