// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/box/ui-box.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiBox as UiBoxElement } from 'storybook-lit/box/ui-box';

export const UiBox = createComponent({
    tagName: 'ui-box',
    elementClass: UiBoxElement,
    react: React,
});

export type UiBoxProps = React.ComponentProps<typeof UiBox>;
