// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/breadcrumbs/ui-breadcrumbs.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiBreadcrumbs as UiBreadcrumbsElement } from 'storybook-lit/breadcrumbs/ui-breadcrumbs';

export const UiBreadcrumbs = createComponent({
    tagName: 'ui-breadcrumbs',
    elementClass: UiBreadcrumbsElement,
    react: React,
});

export type UiBreadcrumbsProps = React.ComponentProps<typeof UiBreadcrumbs>;
