// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/button/ui-button-group.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiButtonGroup as UiButtonGroupElement } from 'storybook-lit/button/ui-button-group';

export const UiButtonGroup = createComponent({
    tagName: 'ui-button-group',
    elementClass: UiButtonGroupElement,
    react: React,
});

export type UiButtonGroupProps = React.ComponentProps<typeof UiButtonGroup>;
