// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/carousel/ui-carousel.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiCarouselItem as UiCarouselItemElement } from 'storybook-lit/carousel/ui-carousel';

export const UiCarouselItem = createComponent({
    tagName: 'ui-carousel-item',
    elementClass: UiCarouselItemElement,
    react: React,
});

export type UiCarouselItemProps = React.ComponentProps<typeof UiCarouselItem>;
