// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/progress/ui-circular-progress.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiCircularProgress as UiCircularProgressElement } from 'storybook-lit/progress/ui-circular-progress';

export const UiCircularProgress = createComponent({
    tagName: 'ui-circular-progress',
    elementClass: UiCircularProgressElement,
    react: React,
});

export type UiCircularProgressProps = React.ComponentProps<typeof UiCircularProgress>;
