// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/collapsible/ui-collapsible.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiCollapsibleContent as UiCollapsibleContentElement } from 'storybook-lit/collapsible/ui-collapsible';

export const UiCollapsibleContent = createComponent({
    tagName: 'ui-collapsible-content',
    elementClass: UiCollapsibleContentElement,
    react: React,
});

export type UiCollapsibleContentProps = React.ComponentProps<typeof UiCollapsibleContent>;
