// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/ui-command.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiCommand as UiCommandElement } from 'storybook-lit/command/ui-command';

export const UiCommand = createComponent({
    tagName: 'ui-command',
    elementClass: UiCommandElement,
    react: React,
    events: {
        onUiCommandItemSelect: 'ui-command-item-select' as EventName<CustomEvent>,
    },
});

export type UiCommandProps = React.ComponentProps<typeof UiCommand>;
