// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/ui-command.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiCommandInput as UiCommandInputElement } from 'storybook-lit/command/ui-command';

export const UiCommandInput = createComponent({
    tagName: 'ui-command-input',
    elementClass: UiCommandInputElement,
    react: React,
});

export type UiCommandInputProps = React.ComponentProps<typeof UiCommandInput>;
