// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/collapsible/ui-collapsible.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiCollapsible as UiCollapsibleElement } from 'storybook-lit/collapsible/ui-collapsible';

export const UiCollapsible = createComponent({
    tagName: 'ui-collapsible',
    elementClass: UiCollapsibleElement,
    react: React,
    events: {
        onUiCollapsibleChange: 'ui-collapsible-change' as EventName<CustomEvent>,
    },
});

export type UiCollapsibleProps = React.ComponentProps<typeof UiCollapsible>;
