// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/collapsible/ui-collapsible.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiCollapsibleTrigger as UiCollapsibleTriggerElement } from 'storybook-lit/collapsible/ui-collapsible';

export const UiCollapsibleTrigger = createComponent({
    tagName: 'ui-collapsible-trigger',
    elementClass: UiCollapsibleTriggerElement,
    react: React,
});

export type UiCollapsibleTriggerProps = React.ComponentProps<typeof UiCollapsibleTrigger>;
