// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/ui-command.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiCommandItem as UiCommandItemElement } from 'storybook-lit/command/ui-command';

export const UiCommandItem = createComponent({
    tagName: 'ui-command-item',
    elementClass: UiCommandItemElement,
    react: React,
    events: {
        onUiCommandItemSelect: 'ui-command-item-select' as EventName<CustomEvent>,
    },
});

export type UiCommandItemProps = React.ComponentProps<typeof UiCommandItem>;
