// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/date-range-picker/ui-date-range-picker.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiDateRangePicker as UiDateRangePickerElement } from 'storybook-lit/date-range-picker/ui-date-range-picker';

export const UiDateRangePicker = createComponent({
    tagName: 'ui-date-range-picker',
    elementClass: UiDateRangePickerElement,
    react: React,
    events: {
        onRangeChange: 'range-change' as EventName<CustomEvent>,
    },
});

export type UiDateRangePickerProps = React.ComponentProps<typeof UiDateRangePicker>;
