// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/date-range-picker/ui-date-range-calendar.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiDateRangeCalendar as UiDateRangeCalendarElement } from 'storybook-lit/date-range-picker/ui-date-range-calendar';

export const UiDateRangeCalendar = createComponent({
    tagName: 'ui-date-range-calendar',
    elementClass: UiDateRangeCalendarElement,
    react: React,
    events: {
        onRangeSelect: 'range-select' as EventName<CustomEvent>,
    },
});

export type UiDateRangeCalendarProps = React.ComponentProps<typeof UiDateRangeCalendar>;
