// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/ui-time-picker.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiDigitalClock as UiDigitalClockElement } from 'storybook-lit/time-picker/ui-time-picker';

export const UiDigitalClock = createComponent({
    tagName: 'ui-digital-clock',
    elementClass: UiDigitalClockElement,
    react: React,
    events: {
        onChange: 'change' as EventName<CustomEvent>,
    },
});

export type UiDigitalClockProps = React.ComponentProps<typeof UiDigitalClock>;
