// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/ui-dialog.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiDialogActions as UiDialogActionsElement } from 'storybook-lit/dialog/ui-dialog';

export const UiDialogActions = createComponent({
    tagName: 'ui-dialog-actions',
    elementClass: UiDialogActionsElement,
    react: React,
});

export type UiDialogActionsProps = React.ComponentProps<typeof UiDialogActions>;
