// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/ui-dialog.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiDialogContent as UiDialogContentElement } from 'storybook-lit/dialog/ui-dialog';

export const UiDialogContent = createComponent({
    tagName: 'ui-dialog-content',
    elementClass: UiDialogContentElement,
    react: React,
});

export type UiDialogContentProps = React.ComponentProps<typeof UiDialogContent>;
