// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/empty/ui-empty.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiEmptyContent as UiEmptyContentElement } from 'storybook-lit/empty/ui-empty';

export const UiEmptyContent = createComponent({
    tagName: 'ui-empty-content',
    elementClass: UiEmptyContentElement,
    react: React,
});

export type UiEmptyContentProps = React.ComponentProps<typeof UiEmptyContent>;
