// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/empty/ui-empty.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiEmptyMedia as UiEmptyMediaElement } from 'storybook-lit/empty/ui-empty';

export const UiEmptyMedia = createComponent({
    tagName: 'ui-empty-media',
    elementClass: UiEmptyMediaElement,
    react: React,
});

export type UiEmptyMediaProps = React.ComponentProps<typeof UiEmptyMedia>;
