// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/format-date/ui-format-date.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiFormatDate as UiFormatDateElement } from 'storybook-lit/format-date/ui-format-date';

export const UiFormatDate = createComponent({
    tagName: 'ui-format-date',
    elementClass: UiFormatDateElement,
    react: React,
});

export type UiFormatDateProps = React.ComponentProps<typeof UiFormatDate>;
