// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/grid/ui-grid.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiGrid as UiGridElement } from 'storybook-lit/grid/ui-grid';

export const UiGrid = createComponent({
    tagName: 'ui-grid',
    elementClass: UiGridElement,
    react: React,
});

export type UiGridProps = React.ComponentProps<typeof UiGrid>;
