// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/hover-card/ui-hover-card.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiHoverCardContent as UiHoverCardContentElement } from 'storybook-lit/hover-card/ui-hover-card';

export const UiHoverCardContent = createComponent({
    tagName: 'ui-hover-card-content',
    elementClass: UiHoverCardContentElement,
    react: React,
});

export type UiHoverCardContentProps = React.ComponentProps<typeof UiHoverCardContent>;
