// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/image-list/ui-image-list-item.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiImageListItem as UiImageListItemElement } from 'storybook-lit/image-list/ui-image-list-item';

export const UiImageListItem = createComponent({
    tagName: 'ui-image-list-item',
    elementClass: UiImageListItemElement,
    react: React,
});

export type UiImageListItemProps = React.ComponentProps<typeof UiImageListItem>;
