// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/image-list/ui-image-list.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiImageList as UiImageListElement } from 'storybook-lit/image-list/ui-image-list';

export const UiImageList = createComponent({
    tagName: 'ui-image-list',
    elementClass: UiImageListElement,
    react: React,
});

export type UiImageListProps = React.ComponentProps<typeof UiImageList>;
