// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/input-otp/ui-input-otp.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiInputOtp as UiInputOtpElement } from 'storybook-lit/input-otp/ui-input-otp';

export const UiInputOtp = createComponent({
    tagName: 'ui-input-otp',
    elementClass: UiInputOtpElement,
    react: React,
    events: {
        onUiOtpChange: 'ui-otp-change' as EventName<CustomEvent>,
        onUiOtpComplete: 'ui-otp-complete' as EventName<CustomEvent>,
    },
});

export type UiInputOtpProps = React.ComponentProps<typeof UiInputOtp>;
