// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/input/ui-input.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiInput as UiInputElement } from 'storybook-lit/input/ui-input';

export const UiInput = createComponent({
    tagName: 'ui-input',
    elementClass: UiInputElement,
    react: React,
    events: {
        onUiInputInput: 'ui-input-input' as EventName<CustomEvent>,
        onUiInputChange: 'ui-input-change' as EventName<CustomEvent>,
    },
});

export type UiInputProps = React.ComponentProps<typeof UiInput>;
