// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/ui-item.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiItemActions as UiItemActionsElement } from 'storybook-lit/item/ui-item';

export const UiItemActions = createComponent({
    tagName: 'ui-item-actions',
    elementClass: UiItemActionsElement,
    react: React,
});

export type UiItemActionsProps = React.ComponentProps<typeof UiItemActions>;
