// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/ui-item.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiItemFooter as UiItemFooterElement } from 'storybook-lit/item/ui-item';

export const UiItemFooter = createComponent({
    tagName: 'ui-item-footer',
    elementClass: UiItemFooterElement,
    react: React,
});

export type UiItemFooterProps = React.ComponentProps<typeof UiItemFooter>;
