// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/list/ui-list.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiListItemIcon as UiListItemIconElement } from 'storybook-lit/list/ui-list';

export const UiListItemIcon = createComponent({
    tagName: 'ui-list-item-icon',
    elementClass: UiListItemIconElement,
    react: React,
});

export type UiListItemIconProps = React.ComponentProps<typeof UiListItemIcon>;
