// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/list/ui-list.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiListItemButton as UiListItemButtonElement } from 'storybook-lit/list/ui-list';

export const UiListItemButton = createComponent({
    tagName: 'ui-list-item-button',
    elementClass: UiListItemButtonElement,
    react: React,
});

export type UiListItemButtonProps = React.ComponentProps<typeof UiListItemButton>;
