// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiMenubarSeparator as UiMenubarSeparatorElement } from 'storybook-lit/menubar/ui-menubar';

export const UiMenubarSeparator = createComponent({
    tagName: 'ui-menubar-separator',
    elementClass: UiMenubarSeparatorElement,
    react: React,
});

export type UiMenubarSeparatorProps = React.ComponentProps<typeof UiMenubarSeparator>;
