// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menu/ui-menu.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiMenuDivider as UiMenuDividerElement } from 'storybook-lit/menu/ui-menu';

export const UiMenuDivider = createComponent({
    tagName: 'ui-menu-divider',
    elementClass: UiMenuDividerElement,
    react: React,
});

export type UiMenuDividerProps = React.ComponentProps<typeof UiMenuDivider>;
