// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiMenubarRadioItem as UiMenubarRadioItemElement } from 'storybook-lit/menubar/ui-menubar';

export const UiMenubarRadioItem = createComponent({
    tagName: 'ui-menubar-radio-item',
    elementClass: UiMenubarRadioItemElement,
    react: React,
});

export type UiMenubarRadioItemProps = React.ComponentProps<typeof UiMenubarRadioItem>;
