// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menu/ui-menu.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiMenuGroup as UiMenuGroupElement } from 'storybook-lit/menu/ui-menu';

export const UiMenuGroup = createComponent({
    tagName: 'ui-menu-group',
    elementClass: UiMenuGroupElement,
    react: React,
});

export type UiMenuGroupProps = React.ComponentProps<typeof UiMenuGroup>;
