// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiMenubarSubContent as UiMenubarSubContentElement } from 'storybook-lit/menubar/ui-menubar';

export const UiMenubarSubContent = createComponent({
    tagName: 'ui-menubar-sub-content',
    elementClass: UiMenubarSubContentElement,
    react: React,
});

export type UiMenubarSubContentProps = React.ComponentProps<typeof UiMenubarSubContent>;
