// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/ui-time-picker.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiMobileTimePicker as UiMobileTimePickerElement } from 'storybook-lit/time-picker/ui-time-picker';

export const UiMobileTimePicker = createComponent({
    tagName: 'ui-mobile-time-picker',
    elementClass: UiMobileTimePickerElement,
    react: React,
    events: {
        onChange: 'change' as EventName<CustomEvent>,
    },
});

export type UiMobileTimePickerProps = React.ComponentProps<typeof UiMobileTimePicker>;
