// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/navigation-menu/ui-navigation-menu-item.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiNavigationMenuItem as UiNavigationMenuItemElement } from 'storybook-lit/navigation-menu/ui-navigation-menu-item';

export const UiNavigationMenuItem = createComponent({
    tagName: 'ui-navigation-menu-item',
    elementClass: UiNavigationMenuItemElement,
    react: React,
    events: {
        onUiNavigationMenuTriggerClick: 'ui-navigation-menu-trigger-click' as EventName<CustomEvent>,
        onUiNavigationMenuContentToggle: 'ui-navigation-menu-content-toggle' as EventName<CustomEvent>,
    },
});

export type UiNavigationMenuItemProps = React.ComponentProps<typeof UiNavigationMenuItem>;
