// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/navigation-menu/ui-navigation-menu-content.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiNavigationMenuContent as UiNavigationMenuContentElement } from 'storybook-lit/navigation-menu/ui-navigation-menu-content';

export const UiNavigationMenuContent = createComponent({
    tagName: 'ui-navigation-menu-content',
    elementClass: UiNavigationMenuContentElement,
    react: React,
    events: {
        onUiNavigationMenuContentToggle: 'ui-navigation-menu-content-toggle' as EventName<CustomEvent>,
    },
});

export type UiNavigationMenuContentProps = React.ComponentProps<typeof UiNavigationMenuContent>;
