// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/navigation-menu/ui-navigation-menu-link.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiNavigationMenuLink as UiNavigationMenuLinkElement } from 'storybook-lit/navigation-menu/ui-navigation-menu-link';

export const UiNavigationMenuLink = createComponent({
    tagName: 'ui-navigation-menu-link',
    elementClass: UiNavigationMenuLinkElement,
    react: React,
});

export type UiNavigationMenuLinkProps = React.ComponentProps<typeof UiNavigationMenuLink>;
