// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/navigation-menu/ui-navigation-menu.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiNavigationMenu as UiNavigationMenuElement } from 'storybook-lit/navigation-menu/ui-navigation-menu';

export const UiNavigationMenu = createComponent({
    tagName: 'ui-navigation-menu',
    elementClass: UiNavigationMenuElement,
    react: React,
});

export type UiNavigationMenuProps = React.ComponentProps<typeof UiNavigationMenu>;
