// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/rating/ui-rating.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiRating as UiRatingElement } from 'storybook-lit/rating/ui-rating';

export const UiRating = createComponent({
    tagName: 'ui-rating',
    elementClass: UiRatingElement,
    react: React,
    events: {
        onUiRatingChange: 'ui-rating-change' as EventName<CustomEvent>,
    },
});

export type UiRatingProps = React.ComponentProps<typeof UiRating>;
