// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tree-view/ui-simple-tree-view.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiSimpleTreeView as UiSimpleTreeViewElement } from 'storybook-lit/tree-view/ui-simple-tree-view';

export const UiSimpleTreeView = createComponent({
    tagName: 'ui-simple-tree-view',
    elementClass: UiSimpleTreeViewElement,
    react: React,
    events: {
        onExpandedItemsChange: 'expanded-items-change' as EventName<CustomEvent>,
        onItemClick: 'item-click' as EventName<CustomEvent>,
    },
});

export type UiSimpleTreeViewProps = React.ComponentProps<typeof UiSimpleTreeView>;
