// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/date-range-picker/ui-single-input-date-range-field.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiSingleInputDateRangeField as UiSingleInputDateRangeFieldElement } from 'storybook-lit/date-range-picker/ui-single-input-date-range-field';

export const UiSingleInputDateRangeField = createComponent({
    tagName: 'ui-single-input-date-range-field',
    elementClass: UiSingleInputDateRangeFieldElement,
    react: React,
    events: {
        onRangeClear: 'range-clear' as EventName<CustomEvent>,
        onRangeChange: 'range-change' as EventName<CustomEvent>,
    },
});

export type UiSingleInputDateRangeFieldProps = React.ComponentProps<typeof UiSingleInputDateRangeField>;
