// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/speed-dial/ui-speed-dial.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiSpeedDialAction as UiSpeedDialActionElement } from 'storybook-lit/speed-dial/ui-speed-dial';

export const UiSpeedDialAction = createComponent({
    tagName: 'ui-speed-dial-action',
    elementClass: UiSpeedDialActionElement,
    react: React,
    events: {
        onUiSpeedDialActionClick: 'ui-speed-dial-action-click' as EventName<CustomEvent>,
    },
});

export type UiSpeedDialActionProps = React.ComponentProps<typeof UiSpeedDialAction>;
