// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/split-panel/ui-split-panel.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiSplitPanel as UiSplitPanelElement } from 'storybook-lit/split-panel/ui-split-panel';

export const UiSplitPanel = createComponent({
    tagName: 'ui-split-panel',
    elementClass: UiSplitPanelElement,
    react: React,
    events: {
        onUiSplitPanelReposition: 'ui-split-panel-reposition' as EventName<CustomEvent>,
    },
});

export type UiSplitPanelProps = React.ComponentProps<typeof UiSplitPanel>;
