// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/stepper/ui-stepper.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiStepLabel as UiStepLabelElement } from 'storybook-lit/stepper/ui-stepper';

export const UiStepLabel = createComponent({
    tagName: 'ui-step-label',
    elementClass: UiStepLabelElement,
    react: React,
});

export type UiStepLabelProps = React.ComponentProps<typeof UiStepLabel>;
