// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/table/ui-table-sort-label.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiTableSortLabel as UiTableSortLabelElement } from 'storybook-lit/table/ui-table-sort-label';

export const UiTableSortLabel = createComponent({
    tagName: 'ui-table-sort-label',
    elementClass: UiTableSortLabelElement,
    react: React,
});

export type UiTableSortLabelProps = React.ComponentProps<typeof UiTableSortLabel>;
