// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/table/ui-table.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiTableContainer as UiTableContainerElement } from 'storybook-lit/table/ui-table';

export const UiTableContainer = createComponent({
    tagName: 'ui-table-container',
    elementClass: UiTableContainerElement,
    react: React,
});

export type UiTableContainerProps = React.ComponentProps<typeof UiTableContainer>;
