// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/table/ui-table.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiTableBody as UiTableBodyElement } from 'storybook-lit/table/ui-table';

export const UiTableBody = createComponent({
    tagName: 'ui-table-body',
    elementClass: UiTableBodyElement,
    react: React,
});

export type UiTableBodyProps = React.ComponentProps<typeof UiTableBody>;
