// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/table/ui-table.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiTable as UiTableElement } from 'storybook-lit/table/ui-table';

export const UiTable = createComponent({
    tagName: 'ui-table',
    elementClass: UiTableElement,
    react: React,
});

export type UiTableProps = React.ComponentProps<typeof UiTable>;
