// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/textarea/ui-textarea.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiTextarea as UiTextareaElement } from 'storybook-lit/textarea/ui-textarea';

export const UiTextarea = createComponent({
    tagName: 'ui-textarea',
    elementClass: UiTextareaElement,
    react: React,
    events: {
        onUiTextareaInput: 'ui-textarea-input' as EventName<CustomEvent>,
        onUiTextareaChange: 'ui-textarea-change' as EventName<CustomEvent>,
    },
});

export type UiTextareaProps = React.ComponentProps<typeof UiTextarea>;
