// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tooltip/ui-tooltip.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiTooltip as UiTooltipElement } from 'storybook-lit/tooltip/ui-tooltip';

export const UiTooltip = createComponent({
    tagName: 'ui-tooltip',
    elementClass: UiTooltipElement,
    react: React,
});

export type UiTooltipProps = React.ComponentProps<typeof UiTooltip>;
