// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/button/ui-toggle-button-group.ts

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { UiToggleButtonGroup as UiToggleButtonGroupElement } from 'storybook-lit/button/ui-toggle-button-group';

export const UiToggleButtonGroup = createComponent({
    tagName: 'ui-toggle-button-group',
    elementClass: UiToggleButtonGroupElement,
    react: React,
    events: {
        onUiToggleButtonGroupChange: 'ui-toggle-button-group-change' as EventName<CustomEvent>,
    },
});

export type UiToggleButtonGroupProps = React.ComponentProps<typeof UiToggleButtonGroup>;
