// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/visually-hidden/ui-visually-hidden.ts

import React from 'react';
import { createComponent } from '@lit/react';
import { UiVisuallyHidden as UiVisuallyHiddenElement } from 'storybook-lit/visually-hidden/ui-visually-hidden';

export const UiVisuallyHidden = createComponent({
    tagName: 'ui-visually-hidden',
    elementClass: UiVisuallyHiddenElement,
    react: React,
});

export type UiVisuallyHiddenProps = React.ComponentProps<typeof UiVisuallyHidden>;
