/**
 * Code generators for React wrappers using @lit/react's createComponent().
 */
import type { ComponentMeta, EventMeta } from './types.js';
import { isSimpleType } from './parse-lit.js';

/** Core package name — React wrappers import from this package. */
const CORE_PKG = '@getufy/flint-ui';

/**
 * React HTML event handler prop names that exist on React.HTMLAttributes.
 * If a Lit event maps to one of these, the explicit interface must use Omit
 * to avoid TS2430 (interface incorrectly extends).
 */
const REACT_HTML_EVENT_PROPS = new Set([
    'onCopy', 'onCut', 'onPaste', 'onCompositionEnd', 'onCompositionStart', 'onCompositionUpdate',
    'onFocus', 'onBlur', 'onChange', 'onInput', 'onSubmit', 'onReset', 'onInvalid',
    'onClick', 'onContextMenu', 'onDoubleClick', 'onDrag', 'onDragEnd', 'onDragEnter',
    'onDragLeave', 'onDragOver', 'onDragStart', 'onDrop', 'onMouseDown', 'onMouseEnter',
    'onMouseLeave', 'onMouseMove', 'onMouseOut', 'onMouseOver', 'onMouseUp',
    'onSelect', 'onTouchCancel', 'onTouchEnd', 'onTouchMove', 'onTouchStart',
    'onScroll', 'onWheel', 'onKeyDown', 'onKeyPress', 'onKeyUp',
    'onAnimationStart', 'onAnimationEnd', 'onAnimationIteration',
    'onTransitionEnd', 'onLoad', 'onError', 'onAbort',
]);

// ─── helpers ────────────────────────────────────────────────────────────────

/**
 * Convert a source file path to a package sub-path import.
 * e.g. 'src/button/flint-button.component.ts' → '@getufy/flint-ui/button/flint-button'
 * Strips 'src/' prefix, '.component.ts' or '.ts' suffix.
 */
function packageImport(sourceFile: string): string {
    const stripped = sourceFile
        .replace(/^src\//, '')
        .replace(/\.component\.ts$/, '')
        .replace(/\.ts$/, '');
    return `${CORE_PKG}/${stripped}`;
}

// ─── event constants file ────────────────────────────────────────────────────

/**
 * Generate the content of `react/src/events/<tagname>.ts`.
 * Contains a const object mapping short keys → DOM event name strings.
 *
 * Example output:
 *   export const FlintSwitchEvents = {
 *     CHANGE: 'flint-switch-change',
 *   } as const;
 */
export function generateEventsFile(meta: ComponentMeta): string {
    if (meta.events.length === 0) return '';

    const constName = meta.className + 'Events';
    const entries = meta.events
        .map(e => `    ${e.constKey}: '${e.domName}',`)
        .join('\n');

    return (
        `// Auto-generated — do not edit\n` +
        `export const ${constName} = {\n${entries}\n} as const;\n`
    );
}

// ─── React wrapper component (using @lit/react) ────────────────────────────

/** Compute the detail interface name for a React event prop. */
function detailInterfaceName(reactProp: string): string {
    return reactProp.replace(/^on/, '') + 'Detail';
}

/** Get the event type annotation string for a given event. */
function eventTypeRef(e: EventMeta): string {
    if (e.detailType && e.detailType !== 'unknown') {
        if (e.detailType.startsWith('{')) {
            return `CustomEvent<${detailInterfaceName(e.reactProp)}>`;
        }
        return `CustomEvent<${e.detailType}>`;
    }
    return 'CustomEvent';
}

/**
 * Generate the content of `react/src/components/<ClassName>.tsx`.
 *
 * Uses @lit/react's createComponent() which handles:
 * - Property syncing (no useEffect flicker)
 * - Event forwarding with proper typing
 * - Ref forwarding
 * - React 18 + 19 compatibility
 *
 * Generates explicit prop interfaces for full IDE IntelliSense and
 * typed event detail generics for type-safe event handlers.
 */
export function generateWrapper(
    meta: ComponentMeta,
    /** Absolute path to the components output dir */
    _outDir: string,
    /** Absolute path to the events output dir */
    _eventsDir: string,
): string {
    const { tagName, className, events, sourceFile, props, slots, description } = meta;

    const srcImport = packageImport(sourceFile);
    const hasEvents = events.length > 0;

    const lines: string[] = [];

    lines.push(`// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`);
    lines.push(`// Source: ${sourceFile}`);
    lines.push('');
    lines.push(`import React from 'react';`);
    lines.push(`import { createComponent${hasEvents ? ', type EventName' : ''} } from '@lit/react';`);
    lines.push(`import { ${className} as ${className}Element } from '${srcImport}';`);
    lines.push('');

    // ── Event detail interfaces ──
    for (const e of events) {
        if (e.detailType && e.detailType !== 'unknown' && e.detailType.startsWith('{')) {
            const name = detailInterfaceName(e.reactProp);
            const body = e.detailType
                .slice(1, -1) // strip outer { }
                .split(';')
                .filter(s => s.trim())
                .map(s => `    ${s.trim()};`)
                .join('\n');
            lines.push(`export interface ${name} {`);
            lines.push(body);
            lines.push(`}`);
            lines.push('');
        }
    }

    // ── Explicit props interface ──
    // JSDoc with description and slot documentation
    const jsdocLines: string[] = [];
    if (description) jsdocLines.push(` * ${description}`);
    if (slots.length > 0) {
        if (jsdocLines.length > 0) jsdocLines.push(` *`);
        for (const s of slots) {
            const slotDisplay = s.name || '(default)';
            jsdocLines.push(` * @slot ${slotDisplay}${s.description ? ` - ${s.description}` : ''}`);
        }
    }
    if (jsdocLines.length > 0) {
        lines.push(`/**`);
        for (const l of jsdocLines) lines.push(l);
        lines.push(` */`);
    }

    // Determine if any event props conflict with React.HTMLAttributes
    const conflictingProps = events
        .map(e => e.reactProp)
        .filter(p => REACT_HTML_EVENT_PROPS.has(p));
    // Also check component props that might conflict with HTMLAttributes
    const htmlAttrConflicts = props
        .map(p => p.name)
        .filter(p => ['className', 'style', 'id', 'title', 'lang', 'dir', 'hidden', 'role', 'slot', 'tabIndex', 'color', 'defaultValue', 'defaultChecked'].includes(p));
    const allConflicts = [...new Set([...conflictingProps, ...htmlAttrConflicts])];

    if (allConflicts.length > 0) {
        const omitKeys = allConflicts.map(k => `'${k}'`).join(' | ');
        lines.push(`export interface ${className}Props extends Omit<React.HTMLAttributes<${className}Element>, ${omitKeys}> {`);
    } else {
        lines.push(`export interface ${className}Props extends React.HTMLAttributes<${className}Element> {`);
    }

    // Component-specific props
    for (const p of props) {
        if (p.description) {
            lines.push(`    /** ${p.description} */`);
        }
        const type = isSimpleType(p.tsType)
            ? p.tsType
            : `${className}Element['${p.name}']`;
        lines.push(`    ${p.name}?: ${type};`);
    }

    // Event handler props
    for (const e of events) {
        if (e.description) {
            lines.push(`    /** ${e.description} */`);
        }
        lines.push(`    ${e.reactProp}?: (event: ${eventTypeRef(e)}) => void;`);
    }

    lines.push(`}`);
    lines.push('');

    // ── createComponent call with type cast ──
    lines.push(`export const ${className} = createComponent({`);
    lines.push(`    tagName: '${tagName}',`);
    lines.push(`    elementClass: ${className}Element,`);
    lines.push(`    react: React,`);

    if (hasEvents) {
        lines.push(`    events: {`);
        for (const e of events) {
            lines.push(`        ${e.reactProp}: '${e.domName}' as EventName<${eventTypeRef(e)}>,`);
        }
        lines.push(`    },`);
    }

    lines.push(
        `}) as unknown as React.ForwardRefExoticComponent<${className}Props & React.RefAttributes<${className}Element>>;`,
    );
    lines.push('');

    return lines.join('\n');
}

// ─── barrel index ────────────────────────────────────────────────────────────

/** Get detail interface names for a component's events. */
function getDetailExports(c: ComponentMeta): string[] {
    return c.events
        .filter(e => e.detailType && e.detailType !== 'unknown' && e.detailType.startsWith('{'))
        .map(e => e.reactProp.replace(/^on/, '') + 'Detail');
}

/** Generate `react/src/index.ts` re-exporting all components and events. */
export function generateIndex(components: ComponentMeta[]): string {
    const lines: string[] = [
        `// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`,
        '',
    ];
    // De-duplicate class names and detail types (multiple components may share detail interfaces)
    const seen = new Set<string>();
    for (const c of components) {
        if (seen.has(c.className)) continue;
        seen.add(c.className);
        const detailExports = getDetailExports(c).filter(d => !seen.has(d));
        for (const d of detailExports) seen.add(d);
        const extras = detailExports.length ? `, ${detailExports.map(d => `type ${d}`).join(', ')}` : '';
        lines.push(`export { ${c.className}, type ${c.className}Props${extras} } from './components/${c.className}.js';`);
    }
    lines.push('');
    lines.push(`export * from './events/index.js';`);
    lines.push('');
    return lines.join('\n');
}

/** Generate `react/src/events/index.ts` re-exporting all event constants. */
export function generateEventsIndex(components: ComponentMeta[]): string {
    const lines: string[] = [
        `// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`,
        '',
    ];
    const seen = new Set<string>();
    for (const c of components) {
        if (c.events.length === 0) continue;
        if (seen.has(c.tagName)) continue;
        seen.add(c.tagName);
        lines.push(`export { ${c.className}Events } from './${c.tagName}.js';`);
    }
    lines.push('');
    return lines.join('\n');
}

// ─── per-component barrels ──────────────────────────────────────────────────

/**
 * Extract the component directory name from a sourceFile path.
 * e.g. 'src/button/flint-button.ts' → 'button'
 */
function componentDir(sourceFile: string): string {
    const parts = sourceFile.replace(/^src\//, '').split('/');
    return parts[0];
}

/**
 * Group components by their source directory.
 * Returns a Map of directory name → ComponentMeta[].
 */
export function groupByDirectory(components: ComponentMeta[]): Map<string, ComponentMeta[]> {
    const groups = new Map<string, ComponentMeta[]>();
    for (const c of components) {
        const dir = componentDir(c.sourceFile);
        if (!groups.has(dir)) groups.set(dir, []);
        groups.get(dir)!.push(c);
    }
    return groups;
}

/**
 * Generate a per-component barrel file (e.g. `react/src/button.ts`)
 * that re-exports all wrappers from that component directory.
 */
export function generateComponentBarrel(components: ComponentMeta[]): string {
    const lines: string[] = [
        `// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`,
        '',
    ];
    const seen = new Set<string>();
    for (const c of components) {
        if (seen.has(c.className)) continue;
        seen.add(c.className);
        const detailExports = getDetailExports(c).filter(d => !seen.has(d));
        for (const d of detailExports) seen.add(d);
        const extras = detailExports.length ? `, ${detailExports.map(d => `type ${d}`).join(', ')}` : '';
        lines.push(`export { ${c.className}, type ${c.className}Props${extras} } from './components/${c.className}.js';`);
    }
    // Also re-export any events from these components
    for (const c of components) {
        if (c.events.length === 0) continue;
        if (seen.has(c.tagName + '_events')) continue;
        seen.add(c.tagName + '_events');
        lines.push(`export { ${c.className}Events } from './events/${c.tagName}.js';`);
    }
    lines.push('');
    return lines.join('\n');
}

/**
 * Generate the `exports` map for the React package.json.
 * Includes the root '.' export and per-component exports.
 */
export function generateExportsMap(components: ComponentMeta[]): Record<string, { types: string; import: string }> {
    const exports: Record<string, { types: string; import: string }> = {
        '.': {
            types: './dist/index.d.ts',
            import: './dist/index.js',
        },
    };

    const groups = groupByDirectory(components);
    for (const dir of [...groups.keys()].sort()) {
        exports[`./${dir}`] = {
            types: `./dist/${dir}.d.ts`,
            import: `./dist/${dir}.js`,
        };
    }

    return exports;
}

/**
 * Generate `react/src/custom-elements.d.ts`.
 * Augments the JSX namespace so TypeScript accepts custom-element tags.
 * Uses module augmentation for React 19 compatibility.
 */
export function generateJsxDeclarations(components: ComponentMeta[]): string {
    const lines: string[] = [
        `// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`,
        '',
        `import 'react';`,
        '',
        `declare module 'react' {`,
        `    namespace JSX {`,
        `        interface IntrinsicElements {`,
    ];

    const seen = new Set<string>();
    for (const c of components) {
        if (seen.has(c.tagName)) continue;
        seen.add(c.tagName);
        lines.push(
            `            '${c.tagName}': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;`,
        );
    }

    lines.push(`        }`);
    lines.push(`    }`);
    lines.push(`}`);
    lines.push('');
    return lines.join('\n');
}
