/**
 * Code generators for React wrappers and event-constants files.
 */
import type { ComponentMeta, EventMeta } from './types.js';

// ─── helpers ────────────────────────────────────────────────────────────────

/**
 * Build the relative path from an output file to the source file.
 *
 * outDir:    'react/src/components'
 * sourceFile: 'src/switch/ui-switch.ts'  (relative to project root)
 * → '../../../src/switch/ui-switch.js'
 */
export function relativeImport(fromDir: string, toFile: string): string {
    const fromParts = fromDir.split('/');
    const toParts = toFile.replace(/\.ts$/, '.js').split('/');

    let common = 0;
    while (
        common < fromParts.length &&
        common < toParts.length &&
        fromParts[common] === toParts[common]
    ) {
        common++;
    }

    const ups = fromParts.length - common;
    const downs = toParts.slice(common);
    const prefix = ups === 0 ? './' : '../'.repeat(ups);
    return prefix + downs.join('/');
}

// ─── event constants file ────────────────────────────────────────────────────

/**
 * Generate the content of `react/src/events/<tagname>.ts`.
 * Contains a const object mapping short keys → DOM event name strings.
 *
 * Example output:
 *   export const UiSwitchEvents = {
 *     CHANGE: 'ui-switch-change',
 *   } as const;
 */
export function generateEventsFile(meta: ComponentMeta): string {
    if (meta.events.length === 0) return '';

    const constName = meta.className + 'Events';
    const entries = meta.events
        .map(e => `    ${e.constKey}: '${e.domName}',`)
        .join('\n');

    return (
        `// Auto-generated — do not edit\n` +
        `export const ${constName} = {\n${entries}\n} as const;\n`
    );
}

// ─── React wrapper component ─────────────────────────────────────────────────

/**
 * Generate the content of `react/src/components/<ClassName>.tsx`.
 *
 * Produces a fully typed React.forwardRef wrapper that:
 * - Imports and side-effect-registers the Lit custom element
 * - Syncs all @property values using useEffect
 * - Attaches/detaches custom event listeners using useEffect
 */
export function generateWrapper(
    meta: ComponentMeta,
    /** outDir relative to project root, e.g. 'react/src/components' */
    outDir: string,
    /** events outDir relative to project root, e.g. 'react/src/events' */
    eventsDir: string,
): string {
    const { tagName, className, props, events, sourceFile } = meta;

    const srcImport = relativeImport(outDir, sourceFile);
    const hasEvents = events.length > 0;
    const eventsConstName = className + 'Events';
    const eventsImport = hasEvents
        ? relativeImport(outDir, `${eventsDir}/${tagName}.ts`)
        : null;

    // Build props interface
    const propLines = props.map(p => `    ${p.name}?: ${p.tsType};`);
    const eventLines = events.map(
        e => `    ${e.reactProp}?: (event: CustomEvent) => void;`,
    );

    // Names of all Lit-specific prop keys (to destructure from incoming props)
    const litPropNames = props.map(p => p.name);
    const eventPropNames = events.map(e => e.reactProp);

    // Property sync effect deps
    const propDeps = litPropNames.length > 0 ? `[${litPropNames.join(', ')}]` : '[]';

    // Property sync body
    const propSyncLines = props.map(
        p => `        if (${p.name} !== undefined) (el as unknown as ${className}Element).${p.name} = ${p.name};`,
    );

    // Event listener useEffect blocks (one per event for clean deps)
    const eventEffects = events.map(e => {
        const evRef = hasEvents ? `${eventsConstName}.${e.constKey}` : `'${e.domName}'`;
        return (
            `    React.useEffect(() => {\n` +
            `        const el = elRef.current;\n` +
            `        if (!el || !${e.reactProp}) return;\n` +
            `        const fn = ${e.reactProp} as EventListener;\n` +
            `        el.addEventListener(${evRef}, fn);\n` +
            `        return () => el.removeEventListener(${evRef}, fn);\n` +
            `    }, [${e.reactProp}]);\n`
        );
    });

    // Destructure list for the forwardRef body
    const allDestructured = [...litPropNames, ...eventPropNames, 'children', '...htmlProps'];

    const lines: string[] = [];

    lines.push(`// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`);
    lines.push(`// Source: ${sourceFile}`);
    lines.push('');
    lines.push(`import React from 'react';`);
    lines.push(`import type { ${className} as ${className}Element } from '${srcImport}';`);
    if (hasEvents && eventsImport) {
        lines.push(`import { ${eventsConstName} } from '${eventsImport}';`);
    }
    lines.push(`// Register the custom element`);
    lines.push(`import '${srcImport}';`);
    lines.push('');

    // Props interface
    if (propLines.length > 0 || eventLines.length > 0) {
        lines.push(`export interface ${className}Props extends React.HTMLAttributes<HTMLElement> {`);
        propLines.forEach(l => lines.push(l));
        eventLines.forEach(l => lines.push(l));
        lines.push(`}`);
    } else {
        lines.push(`export type ${className}Props = React.HTMLAttributes<HTMLElement>;`);
    }
    lines.push('');

    // forwardRef component
    lines.push(`export const ${className} = React.forwardRef<${className}Element, ${className}Props>(`);
    lines.push(`    function ${className}(`);
    lines.push(`        { ${allDestructured.join(', ')} }: ${className}Props,`);
    lines.push(`        ref: React.ForwardedRef<${className}Element>,`);
    lines.push(`    ) {`);
    lines.push(`        const innerRef = React.useRef<${className}Element>(null);`);
    lines.push(`        const elRef = (ref as React.RefObject<${className}Element>) ?? innerRef;`);
    lines.push('');

    // Prop sync effect
    if (propSyncLines.length > 0) {
        lines.push(`        React.useEffect(() => {`);
        lines.push(`            const el = elRef.current;`);
        lines.push(`            if (!el) return;`);
        propSyncLines.forEach(l => lines.push(l));
        lines.push(`        }, ${propDeps});`);
        lines.push('');
    }

    // Event effects
    eventEffects.forEach(block => {
        // Indent the block by 4 spaces (it already has 4 at the start)
        block.split('\n').forEach(l => lines.push('    ' + l));
    });

    // JSX return — React 19 passes props to custom elements natively
    lines.push(`        return (`);
    lines.push(`            <${tagName} ref={elRef} {...htmlProps}>`);
    lines.push(`                {children}`);
    lines.push(`            </${tagName}>`);
    lines.push(`        );`);
    lines.push(`    },`);
    lines.push(`);`);
    lines.push('');
    lines.push(`${className}.displayName = '${className}';`);
    lines.push('');

    return lines.join('\n');
}

// ─── barrel index ────────────────────────────────────────────────────────────

/** Generate `react/src/index.ts` re-exporting all components and events. */
export function generateIndex(components: ComponentMeta[]): string {
    const lines: string[] = [
        `// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`,
        '',
    ];
    // De-duplicate class names (multiple files could share a class name in edge cases)
    const seen = new Set<string>();
    for (const c of components) {
        if (seen.has(c.className)) continue;
        seen.add(c.className);
        lines.push(`export { ${c.className}, type ${c.className}Props } from './components/${c.className}.js';`);
    }
    lines.push('');
    lines.push(`export * from './events/index.js';`);
    lines.push('');
    return lines.join('\n');
}

/** Generate `react/src/events/index.ts` re-exporting all event constants. */
export function generateEventsIndex(components: ComponentMeta[]): string {
    const lines: string[] = [
        `// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`,
        '',
    ];
    const seen = new Set<string>();
    for (const c of components) {
        if (c.events.length === 0) continue;
        if (seen.has(c.tagName)) continue;
        seen.add(c.tagName);
        lines.push(`export { ${c.className}Events } from './${c.tagName}.js';`);
    }
    lines.push('');
    return lines.join('\n');
}

/**
 * Generate `react/src/custom-elements.d.ts`.
 * Augments the JSX namespace so TypeScript accepts custom-element tags.
 */
export function generateJsxDeclarations(components: ComponentMeta[]): string {
    const lines: string[] = [
        `// Auto-generated by scripts/generate-react-wrappers.ts — do not edit`,
        `import React from 'react';`,
        '',
        `declare global {`,
        `    namespace JSX {`,
        `        interface IntrinsicElements {`,
    ];

    const seen = new Set<string>();
    for (const c of components) {
        if (seen.has(c.tagName)) continue;
        seen.add(c.tagName);
        lines.push(
            `            '${c.tagName}': React.HTMLAttributes<HTMLElement> & { ref?: React.Ref<unknown> };`,
        );
    }

    lines.push(`        }`);
    lines.push(`    }`);
    lines.push(`}`);
    lines.push('');
    return lines.join('\n');
}
