// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/accordion/ui-accordion.ts

import React from 'react';
import type { UiAccordion as UiAccordionElement } from '../../../src/accordion/ui-accordion.js';
import { UiAccordionEvents } from '../events/ui-accordion.js';
// Register the custom element
import '../../../src/accordion/ui-accordion.js';

export interface UiAccordionProps extends React.HTMLAttributes<HTMLElement> {
    expanded?: boolean;
    disabled?: boolean;
    onUiAccordionChange?: (event: CustomEvent) => void;
}

export const UiAccordion = React.forwardRef<UiAccordionElement, UiAccordionProps>(
    function UiAccordion(
        { expanded, disabled, onUiAccordionChange, children, ...htmlProps }: UiAccordionProps,
        ref: React.ForwardedRef<UiAccordionElement>,
    ) {
        const innerRef = React.useRef<UiAccordionElement>(null);
        const elRef = (ref as React.RefObject<UiAccordionElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (expanded !== undefined) (el as unknown as UiAccordionElement).expanded = expanded;
        if (disabled !== undefined) (el as unknown as UiAccordionElement).disabled = disabled;
        }, [expanded, disabled]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiAccordionChange) return;
            const fn = onUiAccordionChange as EventListener;
            el.addEventListener(UiAccordionEvents.CHANGE, fn);
            return () => el.removeEventListener(UiAccordionEvents.CHANGE, fn);
        }, [onUiAccordionChange]);
    
        return (
            <ui-accordion ref={elRef} {...htmlProps}>
                {children}
            </ui-accordion>
        );
    },
);

UiAccordion.displayName = 'UiAccordion';
