// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/accordion/ui-accordion.ts

import React from 'react';
import type { UiAccordionSummary as UiAccordionSummaryElement } from '../../../src/accordion/ui-accordion.js';
import { UiAccordionSummaryEvents } from '../events/ui-accordion-summary.js';
// Register the custom element
import '../../../src/accordion/ui-accordion.js';

export interface UiAccordionSummaryProps extends React.HTMLAttributes<HTMLElement> {
    onUiAccordionToggle?: (event: CustomEvent) => void;
}

export const UiAccordionSummary = React.forwardRef<UiAccordionSummaryElement, UiAccordionSummaryProps>(
    function UiAccordionSummary(
        { onUiAccordionToggle, children, ...htmlProps }: UiAccordionSummaryProps,
        ref: React.ForwardedRef<UiAccordionSummaryElement>,
    ) {
        const innerRef = React.useRef<UiAccordionSummaryElement>(null);
        const elRef = (ref as React.RefObject<UiAccordionSummaryElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiAccordionToggle) return;
            const fn = onUiAccordionToggle as EventListener;
            el.addEventListener(UiAccordionSummaryEvents.ACCORDION_TOGGLE, fn);
            return () => el.removeEventListener(UiAccordionSummaryEvents.ACCORDION_TOGGLE, fn);
        }, [onUiAccordionToggle]);
    
        return (
            <ui-accordion-summary ref={elRef} {...htmlProps}>
                {children}
            </ui-accordion-summary>
        );
    },
);

UiAccordionSummary.displayName = 'UiAccordionSummary';
