// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/app-bar/ui-app-bar.ts

import React from 'react';
import type { UiAppBar as UiAppBarElement } from '../../../src/app-bar/ui-app-bar.js';
// Register the custom element
import '../../../src/app-bar/ui-app-bar.js';

export interface UiAppBarProps extends React.HTMLAttributes<HTMLElement> {
    title?: string;
    position?: 'static' | 'fixed' | 'absolute' | 'sticky';
    variant?: 'regular' | 'outlined';
}

export const UiAppBar = React.forwardRef<UiAppBarElement, UiAppBarProps>(
    function UiAppBar(
        { title, position, variant, children, ...htmlProps }: UiAppBarProps,
        ref: React.ForwardedRef<UiAppBarElement>,
    ) {
        const innerRef = React.useRef<UiAppBarElement>(null);
        const elRef = (ref as React.RefObject<UiAppBarElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (title !== undefined) (el as unknown as UiAppBarElement).title = title;
        if (position !== undefined) (el as unknown as UiAppBarElement).position = position;
        if (variant !== undefined) (el as unknown as UiAppBarElement).variant = variant;
        }, [title, position, variant]);

        return (
            <ui-app-bar ref={elRef} {...htmlProps}>
                {children}
            </ui-app-bar>
        );
    },
);

UiAppBar.displayName = 'UiAppBar';
