// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/autocomplete/ui-autocomplete.ts

import React from 'react';
import type { UiAutocomplete as UiAutocompleteElement } from '../../../src/autocomplete/ui-autocomplete.js';
import { UiAutocompleteEvents } from '../events/ui-autocomplete.js';
// Register the custom element
import '../../../src/autocomplete/ui-autocomplete.js';

export interface UiAutocompleteProps extends React.HTMLAttributes<HTMLElement> {
    options?: AutocompleteOption[];
    freeSolo?: boolean;
    disabled?: boolean;
    value?: string;
    placeholder?: string;
    onChange?: (event: CustomEvent) => void;
}

export const UiAutocomplete = React.forwardRef<UiAutocompleteElement, UiAutocompleteProps>(
    function UiAutocomplete(
        { options, freeSolo, disabled, value, placeholder, onChange, children, ...htmlProps }: UiAutocompleteProps,
        ref: React.ForwardedRef<UiAutocompleteElement>,
    ) {
        const innerRef = React.useRef<UiAutocompleteElement>(null);
        const elRef = (ref as React.RefObject<UiAutocompleteElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (options !== undefined) (el as unknown as UiAutocompleteElement).options = options;
        if (freeSolo !== undefined) (el as unknown as UiAutocompleteElement).freeSolo = freeSolo;
        if (disabled !== undefined) (el as unknown as UiAutocompleteElement).disabled = disabled;
        if (value !== undefined) (el as unknown as UiAutocompleteElement).value = value;
        if (placeholder !== undefined) (el as unknown as UiAutocompleteElement).placeholder = placeholder;
        }, [options, freeSolo, disabled, value, placeholder]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onChange) return;
            const fn = onChange as EventListener;
            el.addEventListener(UiAutocompleteEvents.CHANGE, fn);
            return () => el.removeEventListener(UiAutocompleteEvents.CHANGE, fn);
        }, [onChange]);
    
        return (
            <ui-autocomplete ref={elRef} {...htmlProps}>
                {children}
            </ui-autocomplete>
        );
    },
);

UiAutocomplete.displayName = 'UiAutocomplete';
