// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/backdrop/ui-backdrop.ts

import React from 'react';
import type { UiBackdrop as UiBackdropElement } from '../../../src/backdrop/ui-backdrop.js';
import { UiBackdropEvents } from '../events/ui-backdrop.js';
// Register the custom element
import '../../../src/backdrop/ui-backdrop.js';

export interface UiBackdropProps extends React.HTMLAttributes<HTMLElement> {
    open?: boolean;
    invisible?: boolean;
    container?: boolean;
    onClose?: (event: CustomEvent) => void;
}

export const UiBackdrop = React.forwardRef<UiBackdropElement, UiBackdropProps>(
    function UiBackdrop(
        { open, invisible, container, onClose, children, ...htmlProps }: UiBackdropProps,
        ref: React.ForwardedRef<UiBackdropElement>,
    ) {
        const innerRef = React.useRef<UiBackdropElement>(null);
        const elRef = (ref as React.RefObject<UiBackdropElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (open !== undefined) (el as unknown as UiBackdropElement).open = open;
        if (invisible !== undefined) (el as unknown as UiBackdropElement).invisible = invisible;
        if (container !== undefined) (el as unknown as UiBackdropElement).container = container;
        }, [open, invisible, container]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onClose) return;
            const fn = onClose as EventListener;
            el.addEventListener(UiBackdropEvents.CLOSE, fn);
            return () => el.removeEventListener(UiBackdropEvents.CLOSE, fn);
        }, [onClose]);
    
        return (
            <ui-backdrop ref={elRef} {...htmlProps}>
                {children}
            </ui-backdrop>
        );
    },
);

UiBackdrop.displayName = 'UiBackdrop';
