// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/box/ui-box.ts

import React from 'react';
import type { UiBox as UiBoxElement } from '../../../src/box/ui-box.js';
// Register the custom element
import '../../../src/box/ui-box.js';

export interface UiBoxProps extends React.HTMLAttributes<HTMLElement> {
    component?: string;
    m?: string;
    mt?: string;
    mr?: string;
    mb?: string;
    ml?: string;
    mx?: string;
    my?: string;
    p?: string;
    pt?: string;
    pr?: string;
    pb?: string;
    pl?: string;
    px?: string;
    py?: string;
    display?: string;
    flexDirection?: string;
    alignItems?: string;
    justifyContent?: string;
    flexWrap?: string;
    flexBasis?: string;
    flexGrow?: string;
    flexShrink?: string;
    gap?: string;
    bgcolor?: string;
    color?: string;
    border?: string;
    borderRadius?: string;
    boxShadow?: string;
    width?: string;
    height?: string;
}

export const UiBox = React.forwardRef<UiBoxElement, UiBoxProps>(
    function UiBox(
        { component, m, mt, mr, mb, ml, mx, my, p, pt, pr, pb, pl, px, py, display, flexDirection, alignItems, justifyContent, flexWrap, flexBasis, flexGrow, flexShrink, gap, bgcolor, color, border, borderRadius, boxShadow, width, height, children, ...htmlProps }: UiBoxProps,
        ref: React.ForwardedRef<UiBoxElement>,
    ) {
        const innerRef = React.useRef<UiBoxElement>(null);
        const elRef = (ref as React.RefObject<UiBoxElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (component !== undefined) (el as unknown as UiBoxElement).component = component;
        if (m !== undefined) (el as unknown as UiBoxElement).m = m;
        if (mt !== undefined) (el as unknown as UiBoxElement).mt = mt;
        if (mr !== undefined) (el as unknown as UiBoxElement).mr = mr;
        if (mb !== undefined) (el as unknown as UiBoxElement).mb = mb;
        if (ml !== undefined) (el as unknown as UiBoxElement).ml = ml;
        if (mx !== undefined) (el as unknown as UiBoxElement).mx = mx;
        if (my !== undefined) (el as unknown as UiBoxElement).my = my;
        if (p !== undefined) (el as unknown as UiBoxElement).p = p;
        if (pt !== undefined) (el as unknown as UiBoxElement).pt = pt;
        if (pr !== undefined) (el as unknown as UiBoxElement).pr = pr;
        if (pb !== undefined) (el as unknown as UiBoxElement).pb = pb;
        if (pl !== undefined) (el as unknown as UiBoxElement).pl = pl;
        if (px !== undefined) (el as unknown as UiBoxElement).px = px;
        if (py !== undefined) (el as unknown as UiBoxElement).py = py;
        if (display !== undefined) (el as unknown as UiBoxElement).display = display;
        if (flexDirection !== undefined) (el as unknown as UiBoxElement).flexDirection = flexDirection;
        if (alignItems !== undefined) (el as unknown as UiBoxElement).alignItems = alignItems;
        if (justifyContent !== undefined) (el as unknown as UiBoxElement).justifyContent = justifyContent;
        if (flexWrap !== undefined) (el as unknown as UiBoxElement).flexWrap = flexWrap;
        if (flexBasis !== undefined) (el as unknown as UiBoxElement).flexBasis = flexBasis;
        if (flexGrow !== undefined) (el as unknown as UiBoxElement).flexGrow = flexGrow;
        if (flexShrink !== undefined) (el as unknown as UiBoxElement).flexShrink = flexShrink;
        if (gap !== undefined) (el as unknown as UiBoxElement).gap = gap;
        if (bgcolor !== undefined) (el as unknown as UiBoxElement).bgcolor = bgcolor;
        if (color !== undefined) (el as unknown as UiBoxElement).color = color;
        if (border !== undefined) (el as unknown as UiBoxElement).border = border;
        if (borderRadius !== undefined) (el as unknown as UiBoxElement).borderRadius = borderRadius;
        if (boxShadow !== undefined) (el as unknown as UiBoxElement).boxShadow = boxShadow;
        if (width !== undefined) (el as unknown as UiBoxElement).width = width;
        if (height !== undefined) (el as unknown as UiBoxElement).height = height;
        }, [component, m, mt, mr, mb, ml, mx, my, p, pt, pr, pb, pl, px, py, display, flexDirection, alignItems, justifyContent, flexWrap, flexBasis, flexGrow, flexShrink, gap, bgcolor, color, border, borderRadius, boxShadow, width, height]);

        return (
            <ui-box ref={elRef} {...htmlProps}>
                {children}
            </ui-box>
        );
    },
);

UiBox.displayName = 'UiBox';
