// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/bottom-navigation/ui-bottom-navigation.ts

import React from 'react';
import type { UiBottomNavigation as UiBottomNavigationElement } from '../../../src/bottom-navigation/ui-bottom-navigation.js';
import { UiBottomNavigationEvents } from '../events/ui-bottom-navigation.js';
// Register the custom element
import '../../../src/bottom-navigation/ui-bottom-navigation.js';

export interface UiBottomNavigationProps extends React.HTMLAttributes<HTMLElement> {
    value?: unknown;
    showLabels?: boolean;
    onUiBottomNavigationChange?: (event: CustomEvent) => void;
}

export const UiBottomNavigation = React.forwardRef<UiBottomNavigationElement, UiBottomNavigationProps>(
    function UiBottomNavigation(
        { value, showLabels, onUiBottomNavigationChange, children, ...htmlProps }: UiBottomNavigationProps,
        ref: React.ForwardedRef<UiBottomNavigationElement>,
    ) {
        const innerRef = React.useRef<UiBottomNavigationElement>(null);
        const elRef = (ref as React.RefObject<UiBottomNavigationElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (value !== undefined) (el as unknown as UiBottomNavigationElement).value = value;
        if (showLabels !== undefined) (el as unknown as UiBottomNavigationElement).showLabels = showLabels;
        }, [value, showLabels]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiBottomNavigationChange) return;
            const fn = onUiBottomNavigationChange as EventListener;
            el.addEventListener(UiBottomNavigationEvents.CHANGE, fn);
            return () => el.removeEventListener(UiBottomNavigationEvents.CHANGE, fn);
        }, [onUiBottomNavigationChange]);
    
        return (
            <ui-bottom-navigation ref={elRef} {...htmlProps}>
                {children}
            </ui-bottom-navigation>
        );
    },
);

UiBottomNavigation.displayName = 'UiBottomNavigation';
