// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/button/ui-button.ts

import React from 'react';
import type { UiButton as UiButtonElement } from '../../../src/button/ui-button.js';
// Register the custom element
import '../../../src/button/ui-button.js';

export interface UiButtonProps extends React.HTMLAttributes<HTMLElement> {
    variant?: 'primary' | 'secondary' | 'destructive';
    size?: 'small' | 'medium' | 'large';
    disabled?: boolean;
    fullWidth?: boolean;
}

export const UiButton = React.forwardRef<UiButtonElement, UiButtonProps>(
    function UiButton(
        { variant, size, disabled, fullWidth, children, ...htmlProps }: UiButtonProps,
        ref: React.ForwardedRef<UiButtonElement>,
    ) {
        const innerRef = React.useRef<UiButtonElement>(null);
        const elRef = (ref as React.RefObject<UiButtonElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (variant !== undefined) (el as unknown as UiButtonElement).variant = variant;
        if (size !== undefined) (el as unknown as UiButtonElement).size = size;
        if (disabled !== undefined) (el as unknown as UiButtonElement).disabled = disabled;
        if (fullWidth !== undefined) (el as unknown as UiButtonElement).fullWidth = fullWidth;
        }, [variant, size, disabled, fullWidth]);

        return (
            <ui-button ref={elRef} {...htmlProps}>
                {children}
            </ui-button>
        );
    },
);

UiButton.displayName = 'UiButton';
