// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/card/ui-card-action-area.ts

import React from 'react';
import type { UiCardActionArea as UiCardActionAreaElement } from '../../../src/card/ui-card-action-area.js';
// Register the custom element
import '../../../src/card/ui-card-action-area.js';

export type UiCardActionAreaProps = React.HTMLAttributes<HTMLElement>;

export const UiCardActionArea = React.forwardRef<UiCardActionAreaElement, UiCardActionAreaProps>(
    function UiCardActionArea(
        { children, ...htmlProps }: UiCardActionAreaProps,
        ref: React.ForwardedRef<UiCardActionAreaElement>,
    ) {
        const innerRef = React.useRef<UiCardActionAreaElement>(null);
        const elRef = (ref as React.RefObject<UiCardActionAreaElement>) ?? innerRef;

        return (
            <ui-card-action-area ref={elRef} {...htmlProps}>
                {children}
            </ui-card-action-area>
        );
    },
);

UiCardActionArea.displayName = 'UiCardActionArea';
