// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/carousel/ui-carousel.ts

import React from 'react';
import type { UiCarousel as UiCarouselElement } from '../../../src/carousel/ui-carousel.js';
import { UiCarouselEvents } from '../events/ui-carousel.js';
// Register the custom element
import '../../../src/carousel/ui-carousel.js';

export interface UiCarouselProps extends React.HTMLAttributes<HTMLElement> {
    loop?: boolean;
    orientation?: 'horizontal' | 'vertical';
    autoplay?: number;
    itemsPerView?: number;
    onUiCarouselChange?: (event: CustomEvent) => void;
}

export const UiCarousel = React.forwardRef<UiCarouselElement, UiCarouselProps>(
    function UiCarousel(
        { loop, orientation, autoplay, itemsPerView, onUiCarouselChange, children, ...htmlProps }: UiCarouselProps,
        ref: React.ForwardedRef<UiCarouselElement>,
    ) {
        const innerRef = React.useRef<UiCarouselElement>(null);
        const elRef = (ref as React.RefObject<UiCarouselElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (loop !== undefined) (el as unknown as UiCarouselElement).loop = loop;
        if (orientation !== undefined) (el as unknown as UiCarouselElement).orientation = orientation;
        if (autoplay !== undefined) (el as unknown as UiCarouselElement).autoplay = autoplay;
        if (itemsPerView !== undefined) (el as unknown as UiCarouselElement).itemsPerView = itemsPerView;
        }, [loop, orientation, autoplay, itemsPerView]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiCarouselChange) return;
            const fn = onUiCarouselChange as EventListener;
            el.addEventListener(UiCarouselEvents.CHANGE, fn);
            return () => el.removeEventListener(UiCarouselEvents.CHANGE, fn);
        }, [onUiCarouselChange]);
    
        return (
            <ui-carousel ref={elRef} {...htmlProps}>
                {children}
            </ui-carousel>
        );
    },
);

UiCarousel.displayName = 'UiCarousel';
