// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/progress/ui-circular-progress.ts

import React from 'react';
import type { UiCircularProgress as UiCircularProgressElement } from '../../../src/progress/ui-circular-progress.js';
// Register the custom element
import '../../../src/progress/ui-circular-progress.js';

export interface UiCircularProgressProps extends React.HTMLAttributes<HTMLElement> {
    variant?: 'determinate' | 'indeterminate';
    value?: number;
    size?: number;
    thickness?: number;
    color?: 'primary' | 'success' | 'error' | 'warning';
    label?: string;
}

export const UiCircularProgress = React.forwardRef<UiCircularProgressElement, UiCircularProgressProps>(
    function UiCircularProgress(
        { variant, value, size, thickness, color, label, children, ...htmlProps }: UiCircularProgressProps,
        ref: React.ForwardedRef<UiCircularProgressElement>,
    ) {
        const innerRef = React.useRef<UiCircularProgressElement>(null);
        const elRef = (ref as React.RefObject<UiCircularProgressElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (variant !== undefined) (el as unknown as UiCircularProgressElement).variant = variant;
        if (value !== undefined) (el as unknown as UiCircularProgressElement).value = value;
        if (size !== undefined) (el as unknown as UiCircularProgressElement).size = size;
        if (thickness !== undefined) (el as unknown as UiCircularProgressElement).thickness = thickness;
        if (color !== undefined) (el as unknown as UiCircularProgressElement).color = color;
        if (label !== undefined) (el as unknown as UiCircularProgressElement).label = label;
        }, [variant, value, size, thickness, color, label]);

        return (
            <ui-circular-progress ref={elRef} {...htmlProps}>
                {children}
            </ui-circular-progress>
        );
    },
);

UiCircularProgress.displayName = 'UiCircularProgress';
