// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/collapsible/ui-collapsible.ts

import React from 'react';
import type { UiCollapsibleContent as UiCollapsibleContentElement } from '../../../src/collapsible/ui-collapsible.js';
// Register the custom element
import '../../../src/collapsible/ui-collapsible.js';

export interface UiCollapsibleContentProps extends React.HTMLAttributes<HTMLElement> {
    open?: boolean;
}

export const UiCollapsibleContent = React.forwardRef<UiCollapsibleContentElement, UiCollapsibleContentProps>(
    function UiCollapsibleContent(
        { open, children, ...htmlProps }: UiCollapsibleContentProps,
        ref: React.ForwardedRef<UiCollapsibleContentElement>,
    ) {
        const innerRef = React.useRef<UiCollapsibleContentElement>(null);
        const elRef = (ref as React.RefObject<UiCollapsibleContentElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (open !== undefined) (el as unknown as UiCollapsibleContentElement).open = open;
        }, [open]);

        return (
            <ui-collapsible-content ref={elRef} {...htmlProps}>
                {children}
            </ui-collapsible-content>
        );
    },
);

UiCollapsibleContent.displayName = 'UiCollapsibleContent';
