// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/ui-command.ts

import React from 'react';
import type { UiCommandInput as UiCommandInputElement } from '../../../src/command/ui-command.js';
// Register the custom element
import '../../../src/command/ui-command.js';

export interface UiCommandInputProps extends React.HTMLAttributes<HTMLElement> {
    placeholder?: string;
    value?: string;
}

export const UiCommandInput = React.forwardRef<UiCommandInputElement, UiCommandInputProps>(
    function UiCommandInput(
        { placeholder, value, children, ...htmlProps }: UiCommandInputProps,
        ref: React.ForwardedRef<UiCommandInputElement>,
    ) {
        const innerRef = React.useRef<UiCommandInputElement>(null);
        const elRef = (ref as React.RefObject<UiCommandInputElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (placeholder !== undefined) (el as unknown as UiCommandInputElement).placeholder = placeholder;
        if (value !== undefined) (el as unknown as UiCommandInputElement).value = value;
        }, [placeholder, value]);

        return (
            <ui-command-input ref={elRef} {...htmlProps}>
                {children}
            </ui-command-input>
        );
    },
);

UiCommandInput.displayName = 'UiCommandInput';
