// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/ui-command.ts

import React from 'react';
import type { UiCommandGroup as UiCommandGroupElement } from '../../../src/command/ui-command.js';
// Register the custom element
import '../../../src/command/ui-command.js';

export interface UiCommandGroupProps extends React.HTMLAttributes<HTMLElement> {
    heading?: string;
}

export const UiCommandGroup = React.forwardRef<UiCommandGroupElement, UiCommandGroupProps>(
    function UiCommandGroup(
        { heading, children, ...htmlProps }: UiCommandGroupProps,
        ref: React.ForwardedRef<UiCommandGroupElement>,
    ) {
        const innerRef = React.useRef<UiCommandGroupElement>(null);
        const elRef = (ref as React.RefObject<UiCommandGroupElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (heading !== undefined) (el as unknown as UiCommandGroupElement).heading = heading;
        }, [heading]);

        return (
            <ui-command-group ref={elRef} {...htmlProps}>
                {children}
            </ui-command-group>
        );
    },
);

UiCommandGroup.displayName = 'UiCommandGroup';
