// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/ui-command.ts

import React from 'react';
import type { UiCommandShortcut as UiCommandShortcutElement } from '../../../src/command/ui-command.js';
// Register the custom element
import '../../../src/command/ui-command.js';

export type UiCommandShortcutProps = React.HTMLAttributes<HTMLElement>;

export const UiCommandShortcut = React.forwardRef<UiCommandShortcutElement, UiCommandShortcutProps>(
    function UiCommandShortcut(
        { children, ...htmlProps }: UiCommandShortcutProps,
        ref: React.ForwardedRef<UiCommandShortcutElement>,
    ) {
        const innerRef = React.useRef<UiCommandShortcutElement>(null);
        const elRef = (ref as React.RefObject<UiCommandShortcutElement>) ?? innerRef;

        return (
            <ui-command-shortcut ref={elRef} {...htmlProps}>
                {children}
            </ui-command-shortcut>
        );
    },
);

UiCommandShortcut.displayName = 'UiCommandShortcut';
