// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/command/ui-command.ts

import React from 'react';
import type { UiCommandList as UiCommandListElement } from '../../../src/command/ui-command.js';
// Register the custom element
import '../../../src/command/ui-command.js';

export type UiCommandListProps = React.HTMLAttributes<HTMLElement>;

export const UiCommandList = React.forwardRef<UiCommandListElement, UiCommandListProps>(
    function UiCommandList(
        { children, ...htmlProps }: UiCommandListProps,
        ref: React.ForwardedRef<UiCommandListElement>,
    ) {
        const innerRef = React.useRef<UiCommandListElement>(null);
        const elRef = (ref as React.RefObject<UiCommandListElement>) ?? innerRef;

        return (
            <ui-command-list ref={elRef} {...htmlProps}>
                {children}
            </ui-command-list>
        );
    },
);

UiCommandList.displayName = 'UiCommandList';
