// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/ui-time-picker.ts

import React from 'react';
import type { UiDesktopTimePicker as UiDesktopTimePickerElement } from '../../../src/time-picker/ui-time-picker.js';
import { UiDesktopTimePickerEvents } from '../events/ui-desktop-time-picker.js';
// Register the custom element
import '../../../src/time-picker/ui-time-picker.js';

export interface UiDesktopTimePickerProps extends React.HTMLAttributes<HTMLElement> {
    value?: string;
    label?: string;
    ampm?: boolean;
    seconds?: boolean;
    disabled?: boolean;
    readonly?: boolean;
    error?: boolean;
    helperText?: string;
    onChange?: (event: CustomEvent) => void;
}

export const UiDesktopTimePicker = React.forwardRef<UiDesktopTimePickerElement, UiDesktopTimePickerProps>(
    function UiDesktopTimePicker(
        { value, label, ampm, seconds, disabled, readonly, error, helperText, onChange, children, ...htmlProps }: UiDesktopTimePickerProps,
        ref: React.ForwardedRef<UiDesktopTimePickerElement>,
    ) {
        const innerRef = React.useRef<UiDesktopTimePickerElement>(null);
        const elRef = (ref as React.RefObject<UiDesktopTimePickerElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (value !== undefined) (el as unknown as UiDesktopTimePickerElement).value = value;
        if (label !== undefined) (el as unknown as UiDesktopTimePickerElement).label = label;
        if (ampm !== undefined) (el as unknown as UiDesktopTimePickerElement).ampm = ampm;
        if (seconds !== undefined) (el as unknown as UiDesktopTimePickerElement).seconds = seconds;
        if (disabled !== undefined) (el as unknown as UiDesktopTimePickerElement).disabled = disabled;
        if (readonly !== undefined) (el as unknown as UiDesktopTimePickerElement).readonly = readonly;
        if (error !== undefined) (el as unknown as UiDesktopTimePickerElement).error = error;
        if (helperText !== undefined) (el as unknown as UiDesktopTimePickerElement).helperText = helperText;
        }, [value, label, ampm, seconds, disabled, readonly, error, helperText]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onChange) return;
            const fn = onChange as EventListener;
            el.addEventListener(UiDesktopTimePickerEvents.CHANGE, fn);
            return () => el.removeEventListener(UiDesktopTimePickerEvents.CHANGE, fn);
        }, [onChange]);
    
        return (
            <ui-desktop-time-picker ref={elRef} {...htmlProps}>
                {children}
            </ui-desktop-time-picker>
        );
    },
);

UiDesktopTimePicker.displayName = 'UiDesktopTimePicker';
