// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/ui-time-picker.ts

import React from 'react';
import type { UiDigitalClock as UiDigitalClockElement } from '../../../src/time-picker/ui-time-picker.js';
import { UiDigitalClockEvents } from '../events/ui-digital-clock.js';
// Register the custom element
import '../../../src/time-picker/ui-time-picker.js';

export interface UiDigitalClockProps extends React.HTMLAttributes<HTMLElement> {
    value?: string;
    step?: number;
    ampm?: boolean;
    onChange?: (event: CustomEvent) => void;
}

export const UiDigitalClock = React.forwardRef<UiDigitalClockElement, UiDigitalClockProps>(
    function UiDigitalClock(
        { value, step, ampm, onChange, children, ...htmlProps }: UiDigitalClockProps,
        ref: React.ForwardedRef<UiDigitalClockElement>,
    ) {
        const innerRef = React.useRef<UiDigitalClockElement>(null);
        const elRef = (ref as React.RefObject<UiDigitalClockElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (value !== undefined) (el as unknown as UiDigitalClockElement).value = value;
        if (step !== undefined) (el as unknown as UiDigitalClockElement).step = step;
        if (ampm !== undefined) (el as unknown as UiDigitalClockElement).ampm = ampm;
        }, [value, step, ampm]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onChange) return;
            const fn = onChange as EventListener;
            el.addEventListener(UiDigitalClockEvents.CHANGE, fn);
            return () => el.removeEventListener(UiDigitalClockEvents.CHANGE, fn);
        }, [onChange]);
    
        return (
            <ui-digital-clock ref={elRef} {...htmlProps}>
                {children}
            </ui-digital-clock>
        );
    },
);

UiDigitalClock.displayName = 'UiDigitalClock';
