// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/divider/ui-divider.ts

import React from 'react';
import type { UiDivider as UiDividerElement } from '../../../src/divider/ui-divider.js';
// Register the custom element
import '../../../src/divider/ui-divider.js';

export interface UiDividerProps extends React.HTMLAttributes<HTMLElement> {
    orientation?: 'horizontal' | 'vertical';
    variant?: 'full' | 'middle' | 'inset';
    weight?: 'light' | 'medium' | 'heavy';
    textAlign?: 'left' | 'center' | 'right';
}

export const UiDivider = React.forwardRef<UiDividerElement, UiDividerProps>(
    function UiDivider(
        { orientation, variant, weight, textAlign, children, ...htmlProps }: UiDividerProps,
        ref: React.ForwardedRef<UiDividerElement>,
    ) {
        const innerRef = React.useRef<UiDividerElement>(null);
        const elRef = (ref as React.RefObject<UiDividerElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (orientation !== undefined) (el as unknown as UiDividerElement).orientation = orientation;
        if (variant !== undefined) (el as unknown as UiDividerElement).variant = variant;
        if (weight !== undefined) (el as unknown as UiDividerElement).weight = weight;
        if (textAlign !== undefined) (el as unknown as UiDividerElement).textAlign = textAlign;
        }, [orientation, variant, weight, textAlign]);

        return (
            <ui-divider ref={elRef} {...htmlProps}>
                {children}
            </ui-divider>
        );
    },
);

UiDivider.displayName = 'UiDivider';
