// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/ui-dialog.ts

import React from 'react';
import type { UiDialogContentText as UiDialogContentTextElement } from '../../../src/dialog/ui-dialog.js';
// Register the custom element
import '../../../src/dialog/ui-dialog.js';

export type UiDialogContentTextProps = React.HTMLAttributes<HTMLElement>;

export const UiDialogContentText = React.forwardRef<UiDialogContentTextElement, UiDialogContentTextProps>(
    function UiDialogContentText(
        { children, ...htmlProps }: UiDialogContentTextProps,
        ref: React.ForwardedRef<UiDialogContentTextElement>,
    ) {
        const innerRef = React.useRef<UiDialogContentTextElement>(null);
        const elRef = (ref as React.RefObject<UiDialogContentTextElement>) ?? innerRef;

        return (
            <ui-dialog-content-text ref={elRef} {...htmlProps}>
                {children}
            </ui-dialog-content-text>
        );
    },
);

UiDialogContentText.displayName = 'UiDialogContentText';
