// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/dialog/ui-dialog.ts

import React from 'react';
import type { UiDialog as UiDialogElement } from '../../../src/dialog/ui-dialog.js';
import { UiDialogEvents } from '../events/ui-dialog.js';
// Register the custom element
import '../../../src/dialog/ui-dialog.js';

export interface UiDialogProps extends React.HTMLAttributes<HTMLElement> {
    open?: boolean;
    transition?: 'scale' | 'slide-up' | 'slide-down';
    disableBackdropClose?: boolean;
    onClose?: (event: CustomEvent) => void;
}

export const UiDialog = React.forwardRef<UiDialogElement, UiDialogProps>(
    function UiDialog(
        { open, transition, disableBackdropClose, onClose, children, ...htmlProps }: UiDialogProps,
        ref: React.ForwardedRef<UiDialogElement>,
    ) {
        const innerRef = React.useRef<UiDialogElement>(null);
        const elRef = (ref as React.RefObject<UiDialogElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (open !== undefined) (el as unknown as UiDialogElement).open = open;
        if (transition !== undefined) (el as unknown as UiDialogElement).transition = transition;
        if (disableBackdropClose !== undefined) (el as unknown as UiDialogElement).disableBackdropClose = disableBackdropClose;
        }, [open, transition, disableBackdropClose]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onClose) return;
            const fn = onClose as EventListener;
            el.addEventListener(UiDialogEvents.CLOSE, fn);
            return () => el.removeEventListener(UiDialogEvents.CLOSE, fn);
        }, [onClose]);
    
        return (
            <ui-dialog ref={elRef} {...htmlProps}>
                {children}
            </ui-dialog>
        );
    },
);

UiDialog.displayName = 'UiDialog';
