// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/empty/ui-empty.ts

import React from 'react';
import type { UiEmptyDescription as UiEmptyDescriptionElement } from '../../../src/empty/ui-empty.js';
// Register the custom element
import '../../../src/empty/ui-empty.js';

export type UiEmptyDescriptionProps = React.HTMLAttributes<HTMLElement>;

export const UiEmptyDescription = React.forwardRef<UiEmptyDescriptionElement, UiEmptyDescriptionProps>(
    function UiEmptyDescription(
        { children, ...htmlProps }: UiEmptyDescriptionProps,
        ref: React.ForwardedRef<UiEmptyDescriptionElement>,
    ) {
        const innerRef = React.useRef<UiEmptyDescriptionElement>(null);
        const elRef = (ref as React.RefObject<UiEmptyDescriptionElement>) ?? innerRef;

        return (
            <ui-empty-description ref={elRef} {...htmlProps}>
                {children}
            </ui-empty-description>
        );
    },
);

UiEmptyDescription.displayName = 'UiEmptyDescription';
