// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/empty/ui-empty.ts

import React from 'react';
import type { UiEmpty as UiEmptyElement } from '../../../src/empty/ui-empty.js';
// Register the custom element
import '../../../src/empty/ui-empty.js';

export type UiEmptyProps = React.HTMLAttributes<HTMLElement>;

export const UiEmpty = React.forwardRef<UiEmptyElement, UiEmptyProps>(
    function UiEmpty(
        { children, ...htmlProps }: UiEmptyProps,
        ref: React.ForwardedRef<UiEmptyElement>,
    ) {
        const innerRef = React.useRef<UiEmptyElement>(null);
        const elRef = (ref as React.RefObject<UiEmptyElement>) ?? innerRef;

        return (
            <ui-empty ref={elRef} {...htmlProps}>
                {children}
            </ui-empty>
        );
    },
);

UiEmpty.displayName = 'UiEmpty';
