// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/empty/ui-empty.ts

import React from 'react';
import type { UiEmptyMedia as UiEmptyMediaElement } from '../../../src/empty/ui-empty.js';
// Register the custom element
import '../../../src/empty/ui-empty.js';

export interface UiEmptyMediaProps extends React.HTMLAttributes<HTMLElement> {
    variant?: 'default' | 'icon';
}

export const UiEmptyMedia = React.forwardRef<UiEmptyMediaElement, UiEmptyMediaProps>(
    function UiEmptyMedia(
        { variant, children, ...htmlProps }: UiEmptyMediaProps,
        ref: React.ForwardedRef<UiEmptyMediaElement>,
    ) {
        const innerRef = React.useRef<UiEmptyMediaElement>(null);
        const elRef = (ref as React.RefObject<UiEmptyMediaElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (variant !== undefined) (el as unknown as UiEmptyMediaElement).variant = variant;
        }, [variant]);

        return (
            <ui-empty-media ref={elRef} {...htmlProps}>
                {children}
            </ui-empty-media>
        );
    },
);

UiEmptyMedia.displayName = 'UiEmptyMedia';
