// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/fab/ui-fab.ts

import React from 'react';
import type { UiFab as UiFabElement } from '../../../src/fab/ui-fab.js';
// Register the custom element
import '../../../src/fab/ui-fab.js';

export interface UiFabProps extends React.HTMLAttributes<HTMLElement> {
    extended?: boolean;
    disabled?: boolean;
    label?: string;
    position?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left' | 'static';
}

export const UiFab = React.forwardRef<UiFabElement, UiFabProps>(
    function UiFab(
        { extended, disabled, label, position, children, ...htmlProps }: UiFabProps,
        ref: React.ForwardedRef<UiFabElement>,
    ) {
        const innerRef = React.useRef<UiFabElement>(null);
        const elRef = (ref as React.RefObject<UiFabElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (extended !== undefined) (el as unknown as UiFabElement).extended = extended;
        if (disabled !== undefined) (el as unknown as UiFabElement).disabled = disabled;
        if (label !== undefined) (el as unknown as UiFabElement).label = label;
        if (position !== undefined) (el as unknown as UiFabElement).position = position;
        }, [extended, disabled, label, position]);

        return (
            <ui-fab ref={elRef} {...htmlProps}>
                {children}
            </ui-fab>
        );
    },
);

UiFab.displayName = 'UiFab';
