// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/hover-card/ui-hover-card.ts

import React from 'react';
import type { UiHoverCardContent as UiHoverCardContentElement } from '../../../src/hover-card/ui-hover-card.js';
// Register the custom element
import '../../../src/hover-card/ui-hover-card.js';

export interface UiHoverCardContentProps extends React.HTMLAttributes<HTMLElement> {
    side?: 'top' | 'right' | 'bottom' | 'left';
    align?: 'start' | 'center' | 'end';
    open?: boolean;
}

export const UiHoverCardContent = React.forwardRef<UiHoverCardContentElement, UiHoverCardContentProps>(
    function UiHoverCardContent(
        { side, align, open, children, ...htmlProps }: UiHoverCardContentProps,
        ref: React.ForwardedRef<UiHoverCardContentElement>,
    ) {
        const innerRef = React.useRef<UiHoverCardContentElement>(null);
        const elRef = (ref as React.RefObject<UiHoverCardContentElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (side !== undefined) (el as unknown as UiHoverCardContentElement).side = side;
        if (align !== undefined) (el as unknown as UiHoverCardContentElement).align = align;
        if (open !== undefined) (el as unknown as UiHoverCardContentElement).open = open;
        }, [side, align, open]);

        return (
            <ui-hover-card-content ref={elRef} {...htmlProps}>
                {children}
            </ui-hover-card-content>
        );
    },
);

UiHoverCardContent.displayName = 'UiHoverCardContent';
