// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/hover-card/ui-hover-card.ts

import React from 'react';
import type { UiHoverCard as UiHoverCardElement } from '../../../src/hover-card/ui-hover-card.js';
// Register the custom element
import '../../../src/hover-card/ui-hover-card.js';

export interface UiHoverCardProps extends React.HTMLAttributes<HTMLElement> {
    openDelay?: number;
    closeDelay?: number;
}

export const UiHoverCard = React.forwardRef<UiHoverCardElement, UiHoverCardProps>(
    function UiHoverCard(
        { openDelay, closeDelay, children, ...htmlProps }: UiHoverCardProps,
        ref: React.ForwardedRef<UiHoverCardElement>,
    ) {
        const innerRef = React.useRef<UiHoverCardElement>(null);
        const elRef = (ref as React.RefObject<UiHoverCardElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (openDelay !== undefined) (el as unknown as UiHoverCardElement).openDelay = openDelay;
        if (closeDelay !== undefined) (el as unknown as UiHoverCardElement).closeDelay = closeDelay;
        }, [openDelay, closeDelay]);

        return (
            <ui-hover-card ref={elRef} {...htmlProps}>
                {children}
            </ui-hover-card>
        );
    },
);

UiHoverCard.displayName = 'UiHoverCard';
