// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/input-otp/ui-input-otp.ts

import React from 'react';
import type { UiInputOtpSlot as UiInputOtpSlotElement } from '../../../src/input-otp/ui-input-otp.js';
// Register the custom element
import '../../../src/input-otp/ui-input-otp.js';

export interface UiInputOtpSlotProps extends React.HTMLAttributes<HTMLElement> {
    index?: number;
    char?: string;
    active?: boolean;
    invalid?: boolean;
}

export const UiInputOtpSlot = React.forwardRef<UiInputOtpSlotElement, UiInputOtpSlotProps>(
    function UiInputOtpSlot(
        { index, char, active, invalid, children, ...htmlProps }: UiInputOtpSlotProps,
        ref: React.ForwardedRef<UiInputOtpSlotElement>,
    ) {
        const innerRef = React.useRef<UiInputOtpSlotElement>(null);
        const elRef = (ref as React.RefObject<UiInputOtpSlotElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (index !== undefined) (el as unknown as UiInputOtpSlotElement).index = index;
        if (char !== undefined) (el as unknown as UiInputOtpSlotElement).char = char;
        if (active !== undefined) (el as unknown as UiInputOtpSlotElement).active = active;
        if (invalid !== undefined) (el as unknown as UiInputOtpSlotElement).invalid = invalid;
        }, [index, char, active, invalid]);

        return (
            <ui-input-otp-slot ref={elRef} {...htmlProps}>
                {children}
            </ui-input-otp-slot>
        );
    },
);

UiInputOtpSlot.displayName = 'UiInputOtpSlot';
