// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/ui-item.ts

import React from 'react';
import type { UiItemFooter as UiItemFooterElement } from '../../../src/item/ui-item.js';
// Register the custom element
import '../../../src/item/ui-item.js';

export type UiItemFooterProps = React.HTMLAttributes<HTMLElement>;

export const UiItemFooter = React.forwardRef<UiItemFooterElement, UiItemFooterProps>(
    function UiItemFooter(
        { children, ...htmlProps }: UiItemFooterProps,
        ref: React.ForwardedRef<UiItemFooterElement>,
    ) {
        const innerRef = React.useRef<UiItemFooterElement>(null);
        const elRef = (ref as React.RefObject<UiItemFooterElement>) ?? innerRef;

        return (
            <ui-item-footer ref={elRef} {...htmlProps}>
                {children}
            </ui-item-footer>
        );
    },
);

UiItemFooter.displayName = 'UiItemFooter';
