// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/ui-item.ts

import React from 'react';
import type { UiItemMedia as UiItemMediaElement } from '../../../src/item/ui-item.js';
// Register the custom element
import '../../../src/item/ui-item.js';

export interface UiItemMediaProps extends React.HTMLAttributes<HTMLElement> {
    variant?: 'default' | 'icon' | 'image';
}

export const UiItemMedia = React.forwardRef<UiItemMediaElement, UiItemMediaProps>(
    function UiItemMedia(
        { variant, children, ...htmlProps }: UiItemMediaProps,
        ref: React.ForwardedRef<UiItemMediaElement>,
    ) {
        const innerRef = React.useRef<UiItemMediaElement>(null);
        const elRef = (ref as React.RefObject<UiItemMediaElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (variant !== undefined) (el as unknown as UiItemMediaElement).variant = variant;
        }, [variant]);

        return (
            <ui-item-media ref={elRef} {...htmlProps}>
                {children}
            </ui-item-media>
        );
    },
);

UiItemMedia.displayName = 'UiItemMedia';
