// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/ui-item.ts

import React from 'react';
import type { UiItemHeader as UiItemHeaderElement } from '../../../src/item/ui-item.js';
// Register the custom element
import '../../../src/item/ui-item.js';

export type UiItemHeaderProps = React.HTMLAttributes<HTMLElement>;

export const UiItemHeader = React.forwardRef<UiItemHeaderElement, UiItemHeaderProps>(
    function UiItemHeader(
        { children, ...htmlProps }: UiItemHeaderProps,
        ref: React.ForwardedRef<UiItemHeaderElement>,
    ) {
        const innerRef = React.useRef<UiItemHeaderElement>(null);
        const elRef = (ref as React.RefObject<UiItemHeaderElement>) ?? innerRef;

        return (
            <ui-item-header ref={elRef} {...htmlProps}>
                {children}
            </ui-item-header>
        );
    },
);

UiItemHeader.displayName = 'UiItemHeader';
