// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/item/ui-item.ts

import React from 'react';
import type { UiItemGroup as UiItemGroupElement } from '../../../src/item/ui-item.js';
// Register the custom element
import '../../../src/item/ui-item.js';

export type UiItemGroupProps = React.HTMLAttributes<HTMLElement>;

export const UiItemGroup = React.forwardRef<UiItemGroupElement, UiItemGroupProps>(
    function UiItemGroup(
        { children, ...htmlProps }: UiItemGroupProps,
        ref: React.ForwardedRef<UiItemGroupElement>,
    ) {
        const innerRef = React.useRef<UiItemGroupElement>(null);
        const elRef = (ref as React.RefObject<UiItemGroupElement>) ?? innerRef;

        return (
            <ui-item-group ref={elRef} {...htmlProps}>
                {children}
            </ui-item-group>
        );
    },
);

UiItemGroup.displayName = 'UiItemGroup';
