// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/list/ui-list.ts

import React from 'react';
import type { UiListItemIcon as UiListItemIconElement } from '../../../src/list/ui-list.js';
// Register the custom element
import '../../../src/list/ui-list.js';

export type UiListItemIconProps = React.HTMLAttributes<HTMLElement>;

export const UiListItemIcon = React.forwardRef<UiListItemIconElement, UiListItemIconProps>(
    function UiListItemIcon(
        { children, ...htmlProps }: UiListItemIconProps,
        ref: React.ForwardedRef<UiListItemIconElement>,
    ) {
        const innerRef = React.useRef<UiListItemIconElement>(null);
        const elRef = (ref as React.RefObject<UiListItemIconElement>) ?? innerRef;

        return (
            <ui-list-item-icon ref={elRef} {...htmlProps}>
                {children}
            </ui-list-item-icon>
        );
    },
);

UiListItemIcon.displayName = 'UiListItemIcon';
