// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import type { UiMenubarTrigger as UiMenubarTriggerElement } from '../../../src/menubar/ui-menubar.js';
// Register the custom element
import '../../../src/menubar/ui-menubar.js';

export interface UiMenubarTriggerProps extends React.HTMLAttributes<HTMLElement> {
    active?: boolean;
    disabled?: boolean;
}

export const UiMenubarTrigger = React.forwardRef<UiMenubarTriggerElement, UiMenubarTriggerProps>(
    function UiMenubarTrigger(
        { active, disabled, children, ...htmlProps }: UiMenubarTriggerProps,
        ref: React.ForwardedRef<UiMenubarTriggerElement>,
    ) {
        const innerRef = React.useRef<UiMenubarTriggerElement>(null);
        const elRef = (ref as React.RefObject<UiMenubarTriggerElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (active !== undefined) (el as unknown as UiMenubarTriggerElement).active = active;
        if (disabled !== undefined) (el as unknown as UiMenubarTriggerElement).disabled = disabled;
        }, [active, disabled]);

        return (
            <ui-menubar-trigger ref={elRef} {...htmlProps}>
                {children}
            </ui-menubar-trigger>
        );
    },
);

UiMenubarTrigger.displayName = 'UiMenubarTrigger';
