// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import type { UiMenubarSubContent as UiMenubarSubContentElement } from '../../../src/menubar/ui-menubar.js';
// Register the custom element
import '../../../src/menubar/ui-menubar.js';

export interface UiMenubarSubContentProps extends React.HTMLAttributes<HTMLElement> {
    open?: boolean;
}

export const UiMenubarSubContent = React.forwardRef<UiMenubarSubContentElement, UiMenubarSubContentProps>(
    function UiMenubarSubContent(
        { open, children, ...htmlProps }: UiMenubarSubContentProps,
        ref: React.ForwardedRef<UiMenubarSubContentElement>,
    ) {
        const innerRef = React.useRef<UiMenubarSubContentElement>(null);
        const elRef = (ref as React.RefObject<UiMenubarSubContentElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (open !== undefined) (el as unknown as UiMenubarSubContentElement).open = open;
        }, [open]);

        return (
            <ui-menubar-sub-content ref={elRef} {...htmlProps}>
                {children}
            </ui-menubar-sub-content>
        );
    },
);

UiMenubarSubContent.displayName = 'UiMenubarSubContent';
