// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menu/ui-menu.ts

import React from 'react';
import type { UiMenuGroup as UiMenuGroupElement } from '../../../src/menu/ui-menu.js';
// Register the custom element
import '../../../src/menu/ui-menu.js';

export interface UiMenuGroupProps extends React.HTMLAttributes<HTMLElement> {
    label?: string;
}

export const UiMenuGroup = React.forwardRef<UiMenuGroupElement, UiMenuGroupProps>(
    function UiMenuGroup(
        { label, children, ...htmlProps }: UiMenuGroupProps,
        ref: React.ForwardedRef<UiMenuGroupElement>,
    ) {
        const innerRef = React.useRef<UiMenuGroupElement>(null);
        const elRef = (ref as React.RefObject<UiMenuGroupElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (label !== undefined) (el as unknown as UiMenuGroupElement).label = label;
        }, [label]);

        return (
            <ui-menu-group ref={elRef} {...htmlProps}>
                {children}
            </ui-menu-group>
        );
    },
);

UiMenuGroup.displayName = 'UiMenuGroup';
