// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menu/ui-menu.ts

import React from 'react';
import type { UiMenu as UiMenuElement } from '../../../src/menu/ui-menu.js';
import { UiMenuEvents } from '../events/ui-menu.js';
// Register the custom element
import '../../../src/menu/ui-menu.js';

export interface UiMenuProps extends React.HTMLAttributes<HTMLElement> {
    open?: boolean;
    placement?: string;
    closeOnSelect?: boolean;
    scrollable?: boolean;
    label?: string;
    onUiMenuClose?: (event: CustomEvent) => void;
}

export const UiMenu = React.forwardRef<UiMenuElement, UiMenuProps>(
    function UiMenu(
        { open, placement, closeOnSelect, scrollable, label, onUiMenuClose, children, ...htmlProps }: UiMenuProps,
        ref: React.ForwardedRef<UiMenuElement>,
    ) {
        const innerRef = React.useRef<UiMenuElement>(null);
        const elRef = (ref as React.RefObject<UiMenuElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (open !== undefined) (el as unknown as UiMenuElement).open = open;
        if (placement !== undefined) (el as unknown as UiMenuElement).placement = placement;
        if (closeOnSelect !== undefined) (el as unknown as UiMenuElement).closeOnSelect = closeOnSelect;
        if (scrollable !== undefined) (el as unknown as UiMenuElement).scrollable = scrollable;
        if (label !== undefined) (el as unknown as UiMenuElement).label = label;
        }, [open, placement, closeOnSelect, scrollable, label]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiMenuClose) return;
            const fn = onUiMenuClose as EventListener;
            el.addEventListener(UiMenuEvents.CLOSE, fn);
            return () => el.removeEventListener(UiMenuEvents.CLOSE, fn);
        }, [onUiMenuClose]);
    
        return (
            <ui-menu ref={elRef} {...htmlProps}>
                {children}
            </ui-menu>
        );
    },
);

UiMenu.displayName = 'UiMenu';
