// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import type { UiMenubarItem as UiMenubarItemElement } from '../../../src/menubar/ui-menubar.js';
import { UiMenubarItemEvents } from '../events/ui-menubar-item.js';
// Register the custom element
import '../../../src/menubar/ui-menubar.js';

export interface UiMenubarItemProps extends React.HTMLAttributes<HTMLElement> {
    disabled?: boolean;
    highlighted?: boolean;
    inset?: boolean;
    value?: string;
    onUiMenubarItemSelect?: (event: CustomEvent) => void;
}

export const UiMenubarItem = React.forwardRef<UiMenubarItemElement, UiMenubarItemProps>(
    function UiMenubarItem(
        { disabled, highlighted, inset, value, onUiMenubarItemSelect, children, ...htmlProps }: UiMenubarItemProps,
        ref: React.ForwardedRef<UiMenubarItemElement>,
    ) {
        const innerRef = React.useRef<UiMenubarItemElement>(null);
        const elRef = (ref as React.RefObject<UiMenubarItemElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (disabled !== undefined) (el as unknown as UiMenubarItemElement).disabled = disabled;
        if (highlighted !== undefined) (el as unknown as UiMenubarItemElement).highlighted = highlighted;
        if (inset !== undefined) (el as unknown as UiMenubarItemElement).inset = inset;
        if (value !== undefined) (el as unknown as UiMenubarItemElement).value = value;
        }, [disabled, highlighted, inset, value]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiMenubarItemSelect) return;
            const fn = onUiMenubarItemSelect as EventListener;
            el.addEventListener(UiMenubarItemEvents.SELECT, fn);
            return () => el.removeEventListener(UiMenubarItemEvents.SELECT, fn);
        }, [onUiMenubarItemSelect]);
    
        return (
            <ui-menubar-item ref={elRef} {...htmlProps}>
                {children}
            </ui-menubar-item>
        );
    },
);

UiMenubarItem.displayName = 'UiMenubarItem';
