// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import type { UiMenubar as UiMenubarElement } from '../../../src/menubar/ui-menubar.js';
// Register the custom element
import '../../../src/menubar/ui-menubar.js';

export interface UiMenubarProps extends React.HTMLAttributes<HTMLElement> {
    label?: string;
}

export const UiMenubar = React.forwardRef<UiMenubarElement, UiMenubarProps>(
    function UiMenubar(
        { label, children, ...htmlProps }: UiMenubarProps,
        ref: React.ForwardedRef<UiMenubarElement>,
    ) {
        const innerRef = React.useRef<UiMenubarElement>(null);
        const elRef = (ref as React.RefObject<UiMenubarElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (label !== undefined) (el as unknown as UiMenubarElement).label = label;
        }, [label]);

        return (
            <ui-menubar ref={elRef} {...htmlProps}>
                {children}
            </ui-menubar>
        );
    },
);

UiMenubar.displayName = 'UiMenubar';
