// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import type { UiMenubarContent as UiMenubarContentElement } from '../../../src/menubar/ui-menubar.js';
// Register the custom element
import '../../../src/menubar/ui-menubar.js';

export interface UiMenubarContentProps extends React.HTMLAttributes<HTMLElement> {
    open?: boolean;
}

export const UiMenubarContent = React.forwardRef<UiMenubarContentElement, UiMenubarContentProps>(
    function UiMenubarContent(
        { open, children, ...htmlProps }: UiMenubarContentProps,
        ref: React.ForwardedRef<UiMenubarContentElement>,
    ) {
        const innerRef = React.useRef<UiMenubarContentElement>(null);
        const elRef = (ref as React.RefObject<UiMenubarContentElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (open !== undefined) (el as unknown as UiMenubarContentElement).open = open;
        }, [open]);

        return (
            <ui-menubar-content ref={elRef} {...htmlProps}>
                {children}
            </ui-menubar-content>
        );
    },
);

UiMenubarContent.displayName = 'UiMenubarContent';
