// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/menubar/ui-menubar.ts

import React from 'react';
import type { UiMenubarCheckboxItem as UiMenubarCheckboxItemElement } from '../../../src/menubar/ui-menubar.js';
import { UiMenubarCheckboxItemEvents } from '../events/ui-menubar-checkbox-item.js';
// Register the custom element
import '../../../src/menubar/ui-menubar.js';

export interface UiMenubarCheckboxItemProps extends React.HTMLAttributes<HTMLElement> {
    checked?: boolean;
    disabled?: boolean;
    highlighted?: boolean;
    value?: string;
    onUiMenubarCheckboxChange?: (event: CustomEvent) => void;
}

export const UiMenubarCheckboxItem = React.forwardRef<UiMenubarCheckboxItemElement, UiMenubarCheckboxItemProps>(
    function UiMenubarCheckboxItem(
        { checked, disabled, highlighted, value, onUiMenubarCheckboxChange, children, ...htmlProps }: UiMenubarCheckboxItemProps,
        ref: React.ForwardedRef<UiMenubarCheckboxItemElement>,
    ) {
        const innerRef = React.useRef<UiMenubarCheckboxItemElement>(null);
        const elRef = (ref as React.RefObject<UiMenubarCheckboxItemElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (checked !== undefined) (el as unknown as UiMenubarCheckboxItemElement).checked = checked;
        if (disabled !== undefined) (el as unknown as UiMenubarCheckboxItemElement).disabled = disabled;
        if (highlighted !== undefined) (el as unknown as UiMenubarCheckboxItemElement).highlighted = highlighted;
        if (value !== undefined) (el as unknown as UiMenubarCheckboxItemElement).value = value;
        }, [checked, disabled, highlighted, value]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiMenubarCheckboxChange) return;
            const fn = onUiMenubarCheckboxChange as EventListener;
            el.addEventListener(UiMenubarCheckboxItemEvents.MENUBAR_CHECKBOX_CHANGE, fn);
            return () => el.removeEventListener(UiMenubarCheckboxItemEvents.MENUBAR_CHECKBOX_CHANGE, fn);
        }, [onUiMenubarCheckboxChange]);
    
        return (
            <ui-menubar-checkbox-item ref={elRef} {...htmlProps}>
                {children}
            </ui-menubar-checkbox-item>
        );
    },
);

UiMenubarCheckboxItem.displayName = 'UiMenubarCheckboxItem';
