// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/ui-time-picker.ts

import React from 'react';
import type { UiMultiSectionDigitalClock as UiMultiSectionDigitalClockElement } from '../../../src/time-picker/ui-time-picker.js';
import { UiMultiSectionDigitalClockEvents } from '../events/ui-multi-section-digital-clock.js';
// Register the custom element
import '../../../src/time-picker/ui-time-picker.js';

export interface UiMultiSectionDigitalClockProps extends React.HTMLAttributes<HTMLElement> {
    value?: string;
    ampm?: boolean;
    seconds?: boolean;
    onChange?: (event: CustomEvent) => void;
}

export const UiMultiSectionDigitalClock = React.forwardRef<UiMultiSectionDigitalClockElement, UiMultiSectionDigitalClockProps>(
    function UiMultiSectionDigitalClock(
        { value, ampm, seconds, onChange, children, ...htmlProps }: UiMultiSectionDigitalClockProps,
        ref: React.ForwardedRef<UiMultiSectionDigitalClockElement>,
    ) {
        const innerRef = React.useRef<UiMultiSectionDigitalClockElement>(null);
        const elRef = (ref as React.RefObject<UiMultiSectionDigitalClockElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (value !== undefined) (el as unknown as UiMultiSectionDigitalClockElement).value = value;
        if (ampm !== undefined) (el as unknown as UiMultiSectionDigitalClockElement).ampm = ampm;
        if (seconds !== undefined) (el as unknown as UiMultiSectionDigitalClockElement).seconds = seconds;
        }, [value, ampm, seconds]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onChange) return;
            const fn = onChange as EventListener;
            el.addEventListener(UiMultiSectionDigitalClockEvents.CHANGE, fn);
            return () => el.removeEventListener(UiMultiSectionDigitalClockEvents.CHANGE, fn);
        }, [onChange]);
    
        return (
            <ui-multi-section-digital-clock ref={elRef} {...htmlProps}>
                {children}
            </ui-multi-section-digital-clock>
        );
    },
);

UiMultiSectionDigitalClock.displayName = 'UiMultiSectionDigitalClock';
