// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/rating/ui-rating.ts

import React from 'react';
import type { UiRating as UiRatingElement } from '../../../src/rating/ui-rating.js';
import { UiRatingEvents } from '../events/ui-rating.js';
// Register the custom element
import '../../../src/rating/ui-rating.js';

export interface UiRatingProps extends React.HTMLAttributes<HTMLElement> {
    value?: number;
    max?: number;
    readonly?: boolean;
    disabled?: boolean;
    clearable?: boolean;
    defaultValue?: number;
    size?: 'sm' | 'md' | 'lg';
    name?: string;
    label?: string;
    precision?: 1 | 0.5;
    onUiRatingChange?: (event: CustomEvent) => void;
}

export const UiRating = React.forwardRef<UiRatingElement, UiRatingProps>(
    function UiRating(
        { value, max, readonly, disabled, clearable, defaultValue, size, name, label, precision, onUiRatingChange, children, ...htmlProps }: UiRatingProps,
        ref: React.ForwardedRef<UiRatingElement>,
    ) {
        const innerRef = React.useRef<UiRatingElement>(null);
        const elRef = (ref as React.RefObject<UiRatingElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (value !== undefined) (el as unknown as UiRatingElement).value = value;
        if (max !== undefined) (el as unknown as UiRatingElement).max = max;
        if (readonly !== undefined) (el as unknown as UiRatingElement).readonly = readonly;
        if (disabled !== undefined) (el as unknown as UiRatingElement).disabled = disabled;
        if (clearable !== undefined) (el as unknown as UiRatingElement).clearable = clearable;
        if (defaultValue !== undefined) (el as unknown as UiRatingElement).defaultValue = defaultValue;
        if (size !== undefined) (el as unknown as UiRatingElement).size = size;
        if (name !== undefined) (el as unknown as UiRatingElement).name = name;
        if (label !== undefined) (el as unknown as UiRatingElement).label = label;
        if (precision !== undefined) (el as unknown as UiRatingElement).precision = precision;
        }, [value, max, readonly, disabled, clearable, defaultValue, size, name, label, precision]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiRatingChange) return;
            const fn = onUiRatingChange as EventListener;
            el.addEventListener(UiRatingEvents.CHANGE, fn);
            return () => el.removeEventListener(UiRatingEvents.CHANGE, fn);
        }, [onUiRatingChange]);
    
        return (
            <ui-rating ref={elRef} {...htmlProps}>
                {children}
            </ui-rating>
        );
    },
);

UiRating.displayName = 'UiRating';
