// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/tree-view/ui-simple-tree-view.ts

import React from 'react';
import type { UiSimpleTreeView as UiSimpleTreeViewElement } from '../../../src/tree-view/ui-simple-tree-view.js';
import { UiSimpleTreeViewEvents } from '../events/ui-simple-tree-view.js';
// Register the custom element
import '../../../src/tree-view/ui-simple-tree-view.js';

export interface UiSimpleTreeViewProps extends React.HTMLAttributes<HTMLElement> {
    disabledItemsFocusable?: boolean;
    onItemClick?: (itemId: string) => void;
    expandedItems?: string[];
    defaultExpandedItems?: string[];
    onExpandedItemsChange?: (itemIds: string[]) => void;
    expansionTrigger?: 'content' | 'iconContainer';
    onExpandedItemsChange?: (event: CustomEvent) => void;
    onItemClick?: (event: CustomEvent) => void;
}

export const UiSimpleTreeView = React.forwardRef<UiSimpleTreeViewElement, UiSimpleTreeViewProps>(
    function UiSimpleTreeView(
        { disabledItemsFocusable, onItemClick, expandedItems, defaultExpandedItems, onExpandedItemsChange, expansionTrigger, onExpandedItemsChange, onItemClick, children, ...htmlProps }: UiSimpleTreeViewProps,
        ref: React.ForwardedRef<UiSimpleTreeViewElement>,
    ) {
        const innerRef = React.useRef<UiSimpleTreeViewElement>(null);
        const elRef = (ref as React.RefObject<UiSimpleTreeViewElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (disabledItemsFocusable !== undefined) (el as unknown as UiSimpleTreeViewElement).disabledItemsFocusable = disabledItemsFocusable;
        if (onItemClick !== undefined) (el as unknown as UiSimpleTreeViewElement).onItemClick = onItemClick;
        if (expandedItems !== undefined) (el as unknown as UiSimpleTreeViewElement).expandedItems = expandedItems;
        if (defaultExpandedItems !== undefined) (el as unknown as UiSimpleTreeViewElement).defaultExpandedItems = defaultExpandedItems;
        if (onExpandedItemsChange !== undefined) (el as unknown as UiSimpleTreeViewElement).onExpandedItemsChange = onExpandedItemsChange;
        if (expansionTrigger !== undefined) (el as unknown as UiSimpleTreeViewElement).expansionTrigger = expansionTrigger;
        }, [disabledItemsFocusable, onItemClick, expandedItems, defaultExpandedItems, onExpandedItemsChange, expansionTrigger]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onExpandedItemsChange) return;
            const fn = onExpandedItemsChange as EventListener;
            el.addEventListener(UiSimpleTreeViewEvents.EXPANDED_ITEMS_CHANGE, fn);
            return () => el.removeEventListener(UiSimpleTreeViewEvents.EXPANDED_ITEMS_CHANGE, fn);
        }, [onExpandedItemsChange]);
    
        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onItemClick) return;
            const fn = onItemClick as EventListener;
            el.addEventListener(UiSimpleTreeViewEvents.ITEM_CLICK, fn);
            return () => el.removeEventListener(UiSimpleTreeViewEvents.ITEM_CLICK, fn);
        }, [onItemClick]);
    
        return (
            <ui-simple-tree-view ref={elRef} {...htmlProps}>
                {children}
            </ui-simple-tree-view>
        );
    },
);

UiSimpleTreeView.displayName = 'UiSimpleTreeView';
