// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/skeleton/ui-skeleton.ts

import React from 'react';
import type { UiSkeleton as UiSkeletonElement } from '../../../src/skeleton/ui-skeleton.js';
// Register the custom element
import '../../../src/skeleton/ui-skeleton.js';

export interface UiSkeletonProps extends React.HTMLAttributes<HTMLElement> {
    dark?: boolean;
    animation?: 'pulse' | 'wave' | 'none';
    variant?: 'text' | 'circular' | 'rectangular' | 'rounded';
    width?: string;
    height?: string;
    label?: string;
}

export const UiSkeleton = React.forwardRef<UiSkeletonElement, UiSkeletonProps>(
    function UiSkeleton(
        { dark, animation, variant, width, height, label, children, ...htmlProps }: UiSkeletonProps,
        ref: React.ForwardedRef<UiSkeletonElement>,
    ) {
        const innerRef = React.useRef<UiSkeletonElement>(null);
        const elRef = (ref as React.RefObject<UiSkeletonElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (dark !== undefined) (el as unknown as UiSkeletonElement).dark = dark;
        if (animation !== undefined) (el as unknown as UiSkeletonElement).animation = animation;
        if (variant !== undefined) (el as unknown as UiSkeletonElement).variant = variant;
        if (width !== undefined) (el as unknown as UiSkeletonElement).width = width;
        if (height !== undefined) (el as unknown as UiSkeletonElement).height = height;
        if (label !== undefined) (el as unknown as UiSkeletonElement).label = label;
        }, [dark, animation, variant, width, height, label]);

        return (
            <ui-skeleton ref={elRef} {...htmlProps}>
                {children}
            </ui-skeleton>
        );
    },
);

UiSkeleton.displayName = 'UiSkeleton';
