// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/slider/ui-slider.ts

import React from 'react';
import type { UiSlider as UiSliderElement } from '../../../src/slider/ui-slider.js';
import { UiSliderEvents } from '../events/ui-slider.js';
// Register the custom element
import '../../../src/slider/ui-slider.js';

export interface UiSliderProps extends React.HTMLAttributes<HTMLElement> {
    value?: number;
    defaultValue?: number | undefined;
    min?: number;
    max?: number;
    step?: number;
    disabled?: boolean;
    label?: string;
    showValue?: boolean;
    vertical?: boolean;
    size?: Size;
    name?: string;
    formatValue?: ((v: number) => string) | undefined;
    onUiSliderChange?: (event: CustomEvent) => void;
}

export const UiSlider = React.forwardRef<UiSliderElement, UiSliderProps>(
    function UiSlider(
        { value, defaultValue, min, max, step, disabled, label, showValue, vertical, size, name, formatValue, onUiSliderChange, children, ...htmlProps }: UiSliderProps,
        ref: React.ForwardedRef<UiSliderElement>,
    ) {
        const innerRef = React.useRef<UiSliderElement>(null);
        const elRef = (ref as React.RefObject<UiSliderElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (value !== undefined) (el as unknown as UiSliderElement).value = value;
        if (defaultValue !== undefined) (el as unknown as UiSliderElement).defaultValue = defaultValue;
        if (min !== undefined) (el as unknown as UiSliderElement).min = min;
        if (max !== undefined) (el as unknown as UiSliderElement).max = max;
        if (step !== undefined) (el as unknown as UiSliderElement).step = step;
        if (disabled !== undefined) (el as unknown as UiSliderElement).disabled = disabled;
        if (label !== undefined) (el as unknown as UiSliderElement).label = label;
        if (showValue !== undefined) (el as unknown as UiSliderElement).showValue = showValue;
        if (vertical !== undefined) (el as unknown as UiSliderElement).vertical = vertical;
        if (size !== undefined) (el as unknown as UiSliderElement).size = size;
        if (name !== undefined) (el as unknown as UiSliderElement).name = name;
        if (formatValue !== undefined) (el as unknown as UiSliderElement).formatValue = formatValue;
        }, [value, defaultValue, min, max, step, disabled, label, showValue, vertical, size, name, formatValue]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiSliderChange) return;
            const fn = onUiSliderChange as EventListener;
            el.addEventListener(UiSliderEvents.CHANGE, fn);
            return () => el.removeEventListener(UiSliderEvents.CHANGE, fn);
        }, [onUiSliderChange]);
    
        return (
            <ui-slider ref={elRef} {...htmlProps}>
                {children}
            </ui-slider>
        );
    },
);

UiSlider.displayName = 'UiSlider';
