// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/snackbar/ui-snackbar.ts

import React from 'react';
import type { UiSnackbar as UiSnackbarElement } from '../../../src/snackbar/ui-snackbar.js';
import { UiSnackbarEvents } from '../events/ui-snackbar.js';
// Register the custom element
import '../../../src/snackbar/ui-snackbar.js';

export interface UiSnackbarProps extends React.HTMLAttributes<HTMLElement> {
    open?: boolean;
    message?: string;
    autoHideDuration?: number;
    anchorOrigin?: 'top-left' | 'top-center' | 'top-right' |
        'bottom-left' | 'bottom-center' | 'bottom-right';
    pauseOnHover?: boolean;
    closable?: boolean;
    variant?: 'default' | 'info' | 'success' | 'warning' | 'error';
    onUiSnackbarOpen?: (event: CustomEvent) => void;
    onUiSnackbarClose?: (event: CustomEvent) => void;
}

export const UiSnackbar = React.forwardRef<UiSnackbarElement, UiSnackbarProps>(
    function UiSnackbar(
        { open, message, autoHideDuration, anchorOrigin, pauseOnHover, closable, variant, onUiSnackbarOpen, onUiSnackbarClose, children, ...htmlProps }: UiSnackbarProps,
        ref: React.ForwardedRef<UiSnackbarElement>,
    ) {
        const innerRef = React.useRef<UiSnackbarElement>(null);
        const elRef = (ref as React.RefObject<UiSnackbarElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (open !== undefined) (el as unknown as UiSnackbarElement).open = open;
        if (message !== undefined) (el as unknown as UiSnackbarElement).message = message;
        if (autoHideDuration !== undefined) (el as unknown as UiSnackbarElement).autoHideDuration = autoHideDuration;
        if (anchorOrigin !== undefined) (el as unknown as UiSnackbarElement).anchorOrigin = anchorOrigin;
        if (pauseOnHover !== undefined) (el as unknown as UiSnackbarElement).pauseOnHover = pauseOnHover;
        if (closable !== undefined) (el as unknown as UiSnackbarElement).closable = closable;
        if (variant !== undefined) (el as unknown as UiSnackbarElement).variant = variant;
        }, [open, message, autoHideDuration, anchorOrigin, pauseOnHover, closable, variant]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiSnackbarOpen) return;
            const fn = onUiSnackbarOpen as EventListener;
            el.addEventListener(UiSnackbarEvents.OPEN, fn);
            return () => el.removeEventListener(UiSnackbarEvents.OPEN, fn);
        }, [onUiSnackbarOpen]);
    
        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onUiSnackbarClose) return;
            const fn = onUiSnackbarClose as EventListener;
            el.addEventListener(UiSnackbarEvents.CLOSE, fn);
            return () => el.removeEventListener(UiSnackbarEvents.CLOSE, fn);
        }, [onUiSnackbarClose]);
    
        return (
            <ui-snackbar ref={elRef} {...htmlProps}>
                {children}
            </ui-snackbar>
        );
    },
);

UiSnackbar.displayName = 'UiSnackbar';
