// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/stepper/ui-stepper.ts

import React from 'react';
import type { UiStepLabel as UiStepLabelElement } from '../../../src/stepper/ui-stepper.js';
// Register the custom element
import '../../../src/stepper/ui-stepper.js';

export interface UiStepLabelProps extends React.HTMLAttributes<HTMLElement> {
    active?: boolean;
    disabled?: boolean;
    error?: boolean;
}

export const UiStepLabel = React.forwardRef<UiStepLabelElement, UiStepLabelProps>(
    function UiStepLabel(
        { active, disabled, error, children, ...htmlProps }: UiStepLabelProps,
        ref: React.ForwardedRef<UiStepLabelElement>,
    ) {
        const innerRef = React.useRef<UiStepLabelElement>(null);
        const elRef = (ref as React.RefObject<UiStepLabelElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (active !== undefined) (el as unknown as UiStepLabelElement).active = active;
        if (disabled !== undefined) (el as unknown as UiStepLabelElement).disabled = disabled;
        if (error !== undefined) (el as unknown as UiStepLabelElement).error = error;
        }, [active, disabled, error]);

        return (
            <ui-step-label ref={elRef} {...htmlProps}>
                {children}
            </ui-step-label>
        );
    },
);

UiStepLabel.displayName = 'UiStepLabel';
