// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/table/ui-table.ts

import React from 'react';
import type { UiTableFooter as UiTableFooterElement } from '../../../src/table/ui-table.js';
// Register the custom element
import '../../../src/table/ui-table.js';

export type UiTableFooterProps = React.HTMLAttributes<HTMLElement>;

export const UiTableFooter = React.forwardRef<UiTableFooterElement, UiTableFooterProps>(
    function UiTableFooter(
        { children, ...htmlProps }: UiTableFooterProps,
        ref: React.ForwardedRef<UiTableFooterElement>,
    ) {
        const innerRef = React.useRef<UiTableFooterElement>(null);
        const elRef = (ref as React.RefObject<UiTableFooterElement>) ?? innerRef;

        return (
            <ui-table-footer ref={elRef} {...htmlProps}>
                {children}
            </ui-table-footer>
        );
    },
);

UiTableFooter.displayName = 'UiTableFooter';
