// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/text-field/ui-text-field.ts

import React from 'react';
import type { UiTextField as UiTextFieldElement } from '../../../src/text-field/ui-text-field.js';
import { UiTextFieldEvents } from '../events/ui-text-field.js';
// Register the custom element
import '../../../src/text-field/ui-text-field.js';

export interface UiTextFieldProps extends React.HTMLAttributes<HTMLElement> {
    label?: string;
    value?: string;
    placeholder?: string;
    type?: string;
    variant?: 'outlined' | 'filled';
    disabled?: boolean;
    error?: boolean;
    helperText?: string;
    errorMessage?: string;
    onInput?: (event: CustomEvent) => void;
    onChange?: (event: CustomEvent) => void;
}

export const UiTextField = React.forwardRef<UiTextFieldElement, UiTextFieldProps>(
    function UiTextField(
        { label, value, placeholder, type, variant, disabled, error, helperText, errorMessage, onInput, onChange, children, ...htmlProps }: UiTextFieldProps,
        ref: React.ForwardedRef<UiTextFieldElement>,
    ) {
        const innerRef = React.useRef<UiTextFieldElement>(null);
        const elRef = (ref as React.RefObject<UiTextFieldElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (label !== undefined) (el as unknown as UiTextFieldElement).label = label;
        if (value !== undefined) (el as unknown as UiTextFieldElement).value = value;
        if (placeholder !== undefined) (el as unknown as UiTextFieldElement).placeholder = placeholder;
        if (type !== undefined) (el as unknown as UiTextFieldElement).type = type;
        if (variant !== undefined) (el as unknown as UiTextFieldElement).variant = variant;
        if (disabled !== undefined) (el as unknown as UiTextFieldElement).disabled = disabled;
        if (error !== undefined) (el as unknown as UiTextFieldElement).error = error;
        if (helperText !== undefined) (el as unknown as UiTextFieldElement).helperText = helperText;
        if (errorMessage !== undefined) (el as unknown as UiTextFieldElement).errorMessage = errorMessage;
        }, [label, value, placeholder, type, variant, disabled, error, helperText, errorMessage]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onInput) return;
            const fn = onInput as EventListener;
            el.addEventListener(UiTextFieldEvents.INPUT, fn);
            return () => el.removeEventListener(UiTextFieldEvents.INPUT, fn);
        }, [onInput]);
    
        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onChange) return;
            const fn = onChange as EventListener;
            el.addEventListener(UiTextFieldEvents.CHANGE, fn);
            return () => el.removeEventListener(UiTextFieldEvents.CHANGE, fn);
        }, [onChange]);
    
        return (
            <ui-text-field ref={elRef} {...htmlProps}>
                {children}
            </ui-text-field>
        );
    },
);

UiTextField.displayName = 'UiTextField';
