// Auto-generated by scripts/generate-react-wrappers.ts — do not edit
// Source: src/time-picker/ui-time-picker.ts

import React from 'react';
import type { UiTimePicker as UiTimePickerElement } from '../../../src/time-picker/ui-time-picker.js';
import { UiTimePickerEvents } from '../events/ui-time-picker.js';
// Register the custom element
import '../../../src/time-picker/ui-time-picker.js';

export interface UiTimePickerProps extends React.HTMLAttributes<HTMLElement> {
    value?: string;
    label?: string;
    variant?: 'desktop' | 'mobile' | 'static' | 'auto';
    ampm?: boolean;
    seconds?: boolean;
    disabled?: boolean;
    error?: boolean;
    helperText?: string;
    onChange?: (event: CustomEvent) => void;
}

export const UiTimePicker = React.forwardRef<UiTimePickerElement, UiTimePickerProps>(
    function UiTimePicker(
        { value, label, variant, ampm, seconds, disabled, error, helperText, onChange, children, ...htmlProps }: UiTimePickerProps,
        ref: React.ForwardedRef<UiTimePickerElement>,
    ) {
        const innerRef = React.useRef<UiTimePickerElement>(null);
        const elRef = (ref as React.RefObject<UiTimePickerElement>) ?? innerRef;

        React.useEffect(() => {
            const el = elRef.current;
            if (!el) return;
        if (value !== undefined) (el as unknown as UiTimePickerElement).value = value;
        if (label !== undefined) (el as unknown as UiTimePickerElement).label = label;
        if (variant !== undefined) (el as unknown as UiTimePickerElement).variant = variant;
        if (ampm !== undefined) (el as unknown as UiTimePickerElement).ampm = ampm;
        if (seconds !== undefined) (el as unknown as UiTimePickerElement).seconds = seconds;
        if (disabled !== undefined) (el as unknown as UiTimePickerElement).disabled = disabled;
        if (error !== undefined) (el as unknown as UiTimePickerElement).error = error;
        if (helperText !== undefined) (el as unknown as UiTimePickerElement).helperText = helperText;
        }, [value, label, variant, ampm, seconds, disabled, error, helperText]);

        React.useEffect(() => {
            const el = elRef.current;
            if (!el || !onChange) return;
            const fn = onChange as EventListener;
            el.addEventListener(UiTimePickerEvents.CHANGE, fn);
            return () => el.removeEventListener(UiTimePickerEvents.CHANGE, fn);
        }, [onChange]);
    
        return (
            <ui-time-picker ref={elRef} {...htmlProps}>
                {children}
            </ui-time-picker>
        );
    },
);

UiTimePicker.displayName = 'UiTimePicker';
